#1001 Added script to find a python executable, and use it for all calls to process.py
stfc/PSyclone pull request #1012
Opened 2020-11-26 03:59 UTC by hiker

As discussed in #1001 . I decided not to try to install process.py (under whatever name), since I think it's better not to 'pollute' the user's PATH with unnecessary binaries. Once we install the psydata libraries (i.e. the lib directory), all makefiles use relative references to the scripts, so they all should work without any change.

2020-11-30 09:11 UTC, arporter requested changes
All Makefiles under lib have been changed.
Fix is straightforward and makes sense.
This branch works OK for me on a WSL2 installation (which only has python3).
I have no Mac to test this on so, for completeness, please could either @deardenchris or @christophermaynard checkout this branch on their Mac, `cd lib/nan_test` and do `make` and check that there are no errors.
Apart from that that there are just a few minor typos and a missing license/copyright.

2020-11-30 09:11 UTC, arporter commented on lib/get_python.sh
> +#!/usr/bin/bash
Please add copyright/license info.

2020-11-30 09:11 UTC, arporter commented on lib/get_python.sh
> +# This scripts find an executable python command. On
"This script finds an..."

2020-11-30 09:11 UTC, arporter commented on lib/get_python.sh
> +exit -1
Missing new-line.

2020-11-30 09:45 UTC, deardenchris commented
Hi Andy, I've just tried this on my Mac. I found that I had to change `#!/usr/bin/bash` in `get_python.sh` to `#!/bin/bash` otherwise I got the error `/bin/sh: ../get_python.sh: /usr/bin/bash: bad interpreter: No such file or directory`. Although regardless of whether I make the change or not to `get_python.sh`, the same output is produced in the nan_test directory (i.e. the same .mod files and object files) so I think the build is OK?

2020-11-30 09:56 UTC, hiker commented
At least on ubuntu there is also ``/bin/bash``, so that might work for everything? Alternatively, google indicates that ``#!/usr/bin/env bash`` might be a portable option (https://forums.fedoraforum.org/showthread.php?302429-BASH-vs-SHELL-usr-bin-bash-vs-bin-bash&s=f6d965a4a5d5cc63b68910950adbbbcd&p=1720154#post1720154) ... but it also mentions that 'nearly always' ``env`` is ``/usr/bin/env``

So, since on all platforms it seems that `/bin/bash`` works, I'll just use this.

2020-12-01 07:14 UTC, hiker commented on lib/get_python.sh
> +#!/usr/bin/bash
Done.

2020-12-01 07:14 UTC, hiker commented on lib/get_python.sh
> +# This scripts find an executable python command. On
Oops.

2020-12-01 07:14 UTC, hiker commented on lib/get_python.sh
> +exit -1
Done.

2020-12-01 07:27 UTC, hiker commented
I've changed it to ``/bin/bash``, which seems to work on nearly all systems (I tried various systems at BOM, and all had ``/bin/bash``). Ready for next review.

2020-12-01 08:16 UTC, arporter requested changes
All requested changes have been made but the script now refers to `/usr/bash` when I think it should be `/bin/bash`?

2020-12-01 08:16 UTC, arporter commented on lib/get_python.sh
> +#!/usr/bash
Should this be `/bin/bash`?

2020-12-01 09:39 UTC, arporter approved these changes
All good now.

2020-12-01 13:09 UTC, merged