(closes #1025) remove travis
stfc/PSyclone pull request #1026
Opened 2020-12-08 10:43 UTC by arporter

2020-12-08 11:17 UTC, arporter commented
This is ready for review. I think the continuous-integration/travis-ci check above is still present because I hadn't disabled the Travis webhook. I've done that now.

2020-12-08 11:26 UTC, arporter commented
Just a note to say I've updated the wiki pages (reviewing and releasing instructions) to remove mentions of Travis.

2020-12-08 16:02 UTC, arporter commented
I realised I needed to edit the settings relating to the protection of the 'master' branch on GitHub. I've now made the various Actions 'required' and removed that tag from the Travis-related checks.

2020-12-11 00:19 UTC, rupertford requested changes
Looks good. I just have one small inline request and could you also please take a look at the reference to Travis in  `examples/common.mk` and remove.

2020-12-11 00:19 UTC, rupertford commented on .github/workflows/python-package.yml
> +        # pip install external/fparser
Change the comment to "If you want to install the version of .... (from pypi) then uncomment the fparser install line below".

2020-12-11 00:19 UTC, rupertford commented on doc/developer_guide/working_practises.rst
> +approximately 45 minutes of CPU time, ideally we would avoid
Its 15 minutes isn't it?

2020-12-11 08:29 UTC, arporter commented
I thought I'd found every mention of Travis! I've fixed the one in common.mk and addressed your other comments.

2020-12-11 08:46 UTC, rupertford approved these changes
All issues have been addressed. CI and codecov are happy. Approving.

2020-12-11 09:39 UTC, merged