colour adjacent face bug [closes issue 1033]
stfc/PSyclone pull request #1036
Opened 2020-12-21 23:55 UTC by rupertford

2020-12-22 00:00 UTC, rupertford commented
At the moment the symbol table is not being used for the variables `cell`, `colour` or `cmap`. I therefore continued to use strings in this PR as moving to using a symbol table would have involved changing additional classes and adding new tests which would have taken the changes beyond the purpose of this PR.

2020-12-22 00:38 UTC, rupertford commented
OK, ready for first review. Probably from @arporter or @TeranIvy

2021-01-05 09:03 UTC, TeranIvy commented
I am happy to take this and I will ask Christine to try it.

2021-01-12 11:22 UTC, TeranIvy requested changes
Nice simple PR. Looks good and produces correct code in LFRic.
- Changes are covered with tests and are `pycodestyle` and `pylint` clean.
- Tests with compilation pass.
- Examples run and documentation builds.

 There is only one inline remark and I would also kindly ask the developer to bring the branch up-to-date with the master (including the recent `fparser` update). Apart from that we are ready to go.

2021-01-12 11:22 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +    # Check that we index the stencil dofmap appropriately
s/stencil dofmap/adjacent face dofmap/g

2021-01-12 23:11 UTC, rupertford commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +    # Check that we index the stencil dofmap appropriately
Oops, thanks.

2021-01-12 23:19 UTC, rupertford commented
Brought the branch up-to-date and addressed the reviewers comments. Ready for next review subject to GHA being happy.

2021-01-13 10:35 UTC, TeranIvy approved these changes
Thanks for making changes! All well now. Proceeding to merge.

2021-01-13 11:12 UTC, merged