Remove support for GH_ORIENTATION in LFRic API (for #960)
stfc/PSyclone pull request #1059
Opened 2021-01-19 11:25 UTC by TeranIvy

2021-01-20 18:02 UTC, TeranIvy commented
Taking the branch back for a moment to update it.

2021-01-25 11:42 UTC, rupertford requested changes
Nicely done.
Just a couple of very minor changes needed and a question. Please see inline comments.

2021-01-25 19:36 UTC, TeranIvy commented on doc/user_guide/dynamo0p3.rst
> +   3) For each operation on the function space (``basis``, ``diff_basis``),
Oops! Done.

2021-01-25 19:39 UTC, TeranIvy commented on src/psyclone/domain/lfric/function_space.py
> +    VALID_METAFUNC_NAMES = VALID_EVALUATOR_NAMES
Yes, evaluators are a subset of metafuncs. Metafuncs could include other contents in future so I think is better to have separate names.

2021-01-25 19:41 UTC, TeranIvy commented on src/psyclone/dynamo0p3.py
> +                         DynBoundaryConditions,
As a nitpicky person I completely agree 😃 Removed.

2021-01-25 20:04 UTC, TeranIvy commented on src/psyclone/tests/dependency_test.py
> -def test_lfric_stub_args3():
Yes, you're right. I reinstated it and modified it to work with `testkern_any_discontinuous_space_op_1_mod.f90` that also has a "read" and a "write" operator.

2021-01-25 20:17 UTC, TeranIvy commented on src/psyclone/dynamo0p3.py
> +                         DynBoundaryConditions,
There were some `pylint` errors in `dynamo0p3.py` from a recent change on master (wrong indentation) so I fixed that, too.

2021-01-25 20:55 UTC, TeranIvy commented
Addressed review comments and merged the latest master. Ready for another review from @rupertford.

2021-01-26 01:10 UTC, rupertford commented on src/psyclone/tests/dependency_test.py
> -def test_lfric_stub_args3():
Great, thanks.

2021-01-26 12:25 UTC, rupertford approved these changes
All issues have been addressed.
documentation builds and changes look good
all changes conform to pycodestyle and pylint
Approving.

2021-01-26 13:02 UTC, merged