194 region stencils (Supersedes PR #1046)
stfc/PSyclone pull request #1060
Opened 2021-01-19 17:21 UTC by andrewcoughtrie

Created a branch to deal with the accidental inclusion of submodule data. Supersedes PR #1046. 

Responding to the [review](https://github.com/stfc/PSyclone/pull/1046#pullrequestreview-570479752) on #1046.

2021-01-20 18:04 UTC, andrewcoughtrie commented
@arporter I've put the changes requested in PR#1046 in their own commits to hopefully make it easier for you to review them.

2021-01-21 09:18 UTC, andrewcoughtrie commented
Had to fix pycodestyle issues I forgot about, done now.

2021-01-21 10:03 UTC, arporter requested changes
Thanks for making those changes, especially for moving the stencil tests - I hadn't realised just how big a job that was.
Updated documentation builds fine and looks good.
Tests and examples all OK with compilation.
There are just a few pylint things to fix in the new test file and then this can be merged.

2021-01-21 10:34 UTC, andrewcoughtrie commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +import pytest
I don't get any complaints from pylint about this, I can reorder them but I don't know what order it wants. Is it complaining about the order of the imports overall?

2021-01-21 10:34 UTC, andrewcoughtrie commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +# Author: A. Coughtrie, Met Office
Done.

2021-01-21 10:36 UTC, andrewcoughtrie commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +''' Module containing tests of LFRic stencils through the Dynamo0.3 API '''
Not sure what you mean for this. "Module containing tests of LFRic stencils through the **s/Dynamo0.3/LFRic/** API" is that what I should change it to?

2021-01-21 10:36 UTC, andrewcoughtrie commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +DEFAULT_CFG_FILE = os.path.join(ROOT_PATH, "config", "psyclone.cfg")
Deleted.

2021-01-21 10:36 UTC, andrewcoughtrie commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +ROOT_PATH = os.path.dirname(os.path.dirname(os.path.dirname(
Deleted

2021-01-21 11:15 UTC, andrewcoughtrie commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +''' Module containing tests of LFRic stencils through the Dynamo0.3 API '''
@TeranIvy explained your use of sed short hand, I get it now.

2021-01-21 11:38 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +''' Module containing tests of LFRic stencils through the Dynamo0.3 API '''
Apologies - I forgot I might not have used that on you before!

2021-01-21 11:42 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +import pytest
`domain/lfric/lfric_stencil_tests.py:45:0: C0411: third party import "import pytest" should be placed before "import fparser" (wrong-import-order)`

2021-01-21 11:55 UTC, andrewcoughtrie commented on src/psyclone/tests/domain/lfric/lfric_stencil_tests.py
> +import pytest
Done

2021-01-22 08:43 UTC, arporter approved these changes
All requested changes have been made. Proceeding to merge.

2021-01-22 09:04 UTC, merged