Remove check on dimensioning symbols (closes #1089)
stfc/PSyclone pull request #1101
Opened 2021-02-03 12:28 UTC by arporter

2021-02-03 13:17 UTC, arporter commented
This PR simply removes the check that dimensioning symbols are not local and not constant. (Since we currently actually have no way of reliably checking whether or not a symbol is local.)

2021-02-11 15:30 UTC, arporter commented
Once this PR is on, PSyclone can process every file bar one in the NEMO oce+ice configuration we're using. The one that we can't process (`obs_utils.f90`) is actually because fparser can't parse it - there's an access of a 1D array named `idim` that fparser incorrectly identifies as a call to the IDIM intrinsic which should have two arguments. Since it's only a 1D array, fparser reports a syntax error.

2021-02-15 09:04 UTC, sergisiso requested changes
@arporter I am not totally convinced that the checks couldn't be done if the interfaces were improved as discussed in the issue comments but I appreciate these need to be removed for now.

I propose renaming this PR to "towards 1089" instead of "closes", adding a TODO where the checking code was, and bring the removed tests back but mark them both with an xfail to this issue number. Would that be OK?

2021-02-16 15:11 UTC, arporter commented on src/psyclone/psyir/symbols/datatypes.py
> +        from psyclone.psyir.symbols import Symbol
Oh yes, if I import it from `psyir.symbols.symbol` then we avoid the circular import.

2021-02-16 15:16 UTC, arporter commented
I've done as you suggested and put back the test I'd removed, along with a comment in the source file itself. Note that one of the tests was outdated so it has still been deleted. Hopefully ready for another look.

2021-02-17 08:42 UTC, sergisiso approved these changes
@arporter Thanks for taking the suggestion, I think the distinction of a local and a global used as a local will need to be done at some point, and then we can revisit this check.

The PR is ready. It mostly remove code lines, all lines are covered and tests pass. There are no formatting/styling issues. Documentation is not necessary. There are new TODOs to the issue as the issue is not going to be closed.

2021-02-17 10:32 UTC, merged