Correct "GH_WRITE" to "intent(inout)" in kernels (for #1003)
stfc/PSyclone pull request #1117
Opened 2021-02-09 10:45 UTC by TeranIvy

According to Fortran rules the field and operator data arguments in kernels should have `intent(inout)` as they are always defined outside of kernels. However, we currently generate `intent(out)` in LFRic kernels for arguments that have `GH_WRITE` access. This PR corrects the generation and access rules for `GH_WRITE` access to `intent(inout)`.

2021-02-09 12:03 UTC, rupertford commented
Hi @TeranIvy, I thought that if basic types were passed in to a subroutine and were only written then they should be intent(out). What am I missing?

2021-02-09 12:13 UTC, TeranIvy commented
> 
> 
> Hi @TeranIvy, I thought that if basic types were passed in to a subroutine and were only written then they should be intent(out). What am I missing?

@rupertford, the whole of a field array is passed into a kernel, but the kernel only modifies one of the columns. Some compilers with some compile options will overwrite the full array of `intent(out)`, so the intent needs to be `inout`. Steve M. changed this in LFRic trunk a few weeks ago ([LFRic ticket 2397](https://code.metoffice.gov.uk/trac/lfric/ticket/2397)) so this PR brings PSyclone rules (mainly kernel stub generation) up to date.

2021-02-09 12:17 UTC, rupertford commented
> > Hi @TeranIvy, I thought that if basic types were passed in to a subroutine and were only written then they should be intent(out). What am I missing?
> 
> @rupertford, the whole of a field and operator arrays are passed into a kernel, but the kernel only modifies one of the columns. Some compilers with some compile options will overwrite the full array of `intent(out)`, so the intent needs to be `inout` even for `GH_WRITE`. Steve M. changed this in LFRic trunk a few weeks ago ([LFRic ticket 2397](https://code.metoffice.gov.uk/trac/lfric/ticket/2397)) so this PR brings PSyclone rules (mainly kernel stub generation) up to date.

Ah, yes that makes sense. We're only writing to some of the data. Thanks.

2021-02-22 12:02 UTC, arporter requested changes
Good work Iva. There are just a couple of small changes requested in line.
Updated documentation builds without problems.
All tests are OK, incl. compilation. Ditto examples.
Changes are covered.
Please could you bring the branch up-to-date with master.
I've checked for pycodestyle/pylint - see inline.

2021-02-22 16:10 UTC, TeranIvy commented on src/psyclone/dynamo0p3.py
> +                "In the LFRic API argument access must be one of {0}, but "
Done and updated the relevant tests.

2021-02-22 16:17 UTC, TeranIvy commented on src/psyclone/dynamo0p3.py
> +        elif self.access in write_accesses:
Changed to `if`.

2021-02-22 16:17 UTC, TeranIvy commented on src/psyclone/dynamo0p3.py
>          else:
Removed the `else` and left the `GenerationError` for an invalid access.

2021-02-22 17:04 UTC, TeranIvy commented
Addressed the review comments and brought the branch up-to-date with master.

2021-02-25 08:20 UTC, arporter approved these changes
All requested changes have been made.
Examples and tests still OK.
Docs still OK.

2021-02-25 08:46 UTC, merged