Fix RTD builds of UG and DG (closes #1127)
stfc/PSyclone pull request #1128
Opened 2021-02-16 14:49 UTC by arporter

According to https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files, `html_css_files` has been supported since version 1.8 of Sphinx so this change should be fine with older versions too.

2021-02-16 14:55 UTC, arporter commented
A tiny PR that just fixes the `conf.py` files of the User and Dev guides so that RTD works (because it's recent upgrade to 3.5.0 of Sphinx causes build failures).

2021-02-24 15:29 UTC, TeranIvy requested changes
I reproduced the error
```
    ctx['css_files'].sort(key=lambda js: js.priority)
AttributeError: 'str' object has no attribute 'priority'
```
when trying to build documentation on master with Sphinx 3.5.0. Interestingly enough, it doesn't happen with Sphinx 3.5.1. The changes in configuration file on the branch remove the error.
I can also confirm that the error is not present in (quite old) Sphinx 2.2.0 that we have in the LFRic Python.

There are two `pylint` errors about the constant name "needs_sphinx" not being upper case (see inline).

Tests run with compilation and examples run. Documentation builds on the branch with Sphinx 3.5.0, 3.5.1 and 2.2.0.

I get a warning with the developer guide, though:
```
checking consistency... $PSYCLONE_DIR/PSyclone/doc/developer_guide/developers_gocean1p0_stencils.rst: WARNING: document isn't included in any toctree
```
I am aware this warning is not related to this PR. Is there an issue for it that can be referenced in the developer guide?

2021-02-24 16:55 UTC, arporter commented on doc/developer_guide/conf.py
> +needs_sphinx = '1.8'
Since these are Sphinx keywords, I don't think I can do anything about this warning and obviously the same goes for `user_guide/conf.py`.

2021-02-24 17:02 UTC, arporter commented on doc/developer_guide/conf.py
> +needs_sphinx = '1.8'
Actually, that being so, I've just disabled the 'invalid-name' pylint warnings in the two files.

2021-02-24 17:40 UTC, TeranIvy commented on doc/developer_guide/conf.py
> +needs_sphinx = '1.8'
Good idea, as there are other lower-case Sphinx keywords.

2021-02-24 17:41 UTC, TeranIvy approved these changes
All well now. Proceeding to merge.

2021-02-24 18:13 UTC, merged