Add support for Fortran program in the PSyIR (closes #1137)
stfc/PSyclone pull request #1138
Opened 2021-02-28 22:16 UTC by rupertford

2021-02-28 23:50 UTC, rupertford commented
I think this is ready for first review from @sergisiso

2021-03-01 23:06 UTC, sergisiso requested changes
@rupertford There is just some picky comments but the code looks good and is 100% covered, tests pass also with compilation, no TODOs pending, no documentation is needed and no formatting issues are introduced. Should be ready when the comments are addressed.

2021-03-01 23:25 UTC, rupertford commented on src/psyclone/psyir/backend/fortran.py
> +            name = "program"
Updated.

2021-03-01 23:53 UTC, rupertford commented on src/psyclone/tests/psyir/frontend/fparser2_main_program_handler_test.py
> +    assert psyir.parent is None
Yes this is a good point. Actually this was already the case before this PR as we could also already have `Routine` with `is_program=False` as a top level node. There are two relevant things I would like to say about this from a Fortran code point of view
1) I think the top level for Fortran codes should probably be a FileContainer (or similar name) which is a Container as this maps naturally to a `Program` in the Fortran spec, which can contain one or more modules, programs, subroutines and functions (with a constraint that there can be at most one program). The idea of a File containing Routines (classes, functions, procedures, etc) and being used to scope symbols is also used in other languages, so is pretty generic.
2) Whilst we don't have examples of this type of code at the moment, a Fortran program, subroutine and function can encapsulate other subroutines and functions in the same way that modules do (although I'm not sure about variable scoping in these cases i.e. if there is an equivalent of module scope). Therefore we need a way of capturing this, which I think would naturally lead to integrating the concepts of Container and Routine somehow. One option would be to say that a Routine is a Container, but there are a number of options!

2021-03-02 00:00 UTC, rupertford commented
Ready for next review from @sergisiso subject to the CI being happy.

2021-03-02 08:13 UTC, sergisiso commented on src/psyclone/tests/psyir/frontend/fparser2_main_program_handler_test.py
> +    assert psyir.parent is None
Good points both

2021-03-02 08:14 UTC, sergisiso approved these changes
@rupertford This PR is ready to be merged

2021-03-02 09:06 UTC, merged