Moving scalar and field tests (for #1106)
stfc/PSyclone pull request #1196
Opened 2021-04-08 12:01 UTC by TeranIvy

Replaces the failed PR #1118.

2021-04-09 10:33 UTC, arporter requested changes
Looks good, it's really nice to see those file size coming down to something less embarrassing.
There are just a few superfluous comments that I couldn't bring myself to ignore. Once those are removed, this is ready to go.
All tests still OK with compilation. Total number of tests is the same as on master.

2021-04-09 10:33 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
> +# Imports
Please rm this line.

2021-04-09 10:33 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
> +# Tests for PSy-layer code generation for scalar arguments
This is already said in the docstring so please remove.

2021-04-09 10:33 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_scalar_mdata_test.py
> +# Imports
Please rm this line.

2021-04-09 10:33 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_scalar_mdata_test.py
> +# General scalar checks (argument type, data type, etc)
Please rm this line (plus some blank ones).

2021-04-09 10:33 UTC, arporter commented on src/psyclone/tests/dynamo0p3_test.py
> +# Tests
Please rm this line.

2021-04-09 20:55 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
> +# Imports
Done.

2021-04-09 20:55 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
> +# Tests for PSy-layer code generation for scalar arguments
Yep.

2021-04-09 20:56 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/lfric_scalar_mdata_test.py
> +# Imports
Done.

2021-04-09 20:56 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/lfric_scalar_mdata_test.py
> +# General scalar checks (argument type, data type, etc)
Done.

2021-04-12 08:36 UTC, arporter approved these changes
Requested changes have been made.
All tests and examples still OK.
All docs still build OK.
Proceeding to merge.

2021-04-12 09:23 UTC, merged