(towards #1208) Move Directive nodes from psyGen to their own files
stfc/PSyclone pull request #1327
Opened 2021-07-08 14:00 UTC by sergisiso

To keep the reviewer and the git conflict resolver sane I haven't modified any code inside the moved blocks besides the necessary import statements and doctring references.

Unfortunately the boundary between the directives and PSyclone concepts is not as clean as I thought (e.g. directives reference InvokeSchedule, kernels, ..) but this is not tacked in this PR (in fact some references are in the gen_code and may go away soon anyways)

2021-07-08 18:12 UTC, sergisiso commented
@arporter or @rupertford this is ready for review. The PR touches many lines but the changes are quite repetitive. The missing coverage lines are in the directives code that I moved, I will let the reviewer decide what I should do with them.

2021-07-13 16:02 UTC, arporter requested changes
Mammoth effort Sergi - many thanks for doing this. It feels really good to see psyGen.py shrinking.
I think ultimately we probably want a `psyir/nodes/directives` directory with separate classes in separate files (I note that the `acc_directives.py` is already 800 lines long although I guess it will shrink as we remove the gen_code stuff). However, I think this is a good step in that direction and I think it's important to get it on quickly as it has the potential for many conflicts :-) Therefore, I'm not requesting that you do that now.
All tests and examples are OK with compilation.
I can't find any outdated references to psyGen in the docs, tutorials, code or the tests (impressive).
Docs all build without new errors/warnings.
There are a few 'import outside top-level' warnings for the new acc_directive and omp_directive files, please could you fix.

2021-07-14 07:35 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +    :type parent: :py:class:`psyclone.psyit.nodes.Node`
Fixed

2021-07-14 07:37 UTC, sergisiso commented on src/psyclone/psyGen.py
> +from psyclone.f2pygen import CommentGen, CallGen, PSyIRGen, UseGen
Done

2021-07-14 07:40 UTC, sergisiso commented on src/psyclone/psyGen.py
> +        from psyclone.psyir.nodes import OMPDoDirective
I moved this up

2021-07-14 07:42 UTC, sergisiso commented on src/psyclone/psyir/backend/c.py
> +        :type node: :py:class:`psyclone.psyir.nodes.Assigment`
Done

2021-07-14 07:42 UTC, sergisiso commented on src/psyclone/psyir/backend/sir.py
> +        :type node: :py:class:`psyclone.psyir.nodes.Assigment`
Done

2021-07-14 07:47 UTC, sergisiso commented on src/psyclone/psyir/nodes/acc_directives.py
> +''' This module contains the OpenACC Directives node implementation.'''
Done

2021-07-14 07:47 UTC, sergisiso commented on src/psyclone/psyir/nodes/acc_directives.py
> +        return "acc end data"
Done

2021-07-14 07:48 UTC, sergisiso commented on src/psyclone/psyir/nodes/directive.py
> +            self.ast_end = fp_parent.content[ast_start_index+1]
Done

2021-07-14 07:48 UTC, sergisiso commented on src/psyclone/psyir/nodes/omp_directives.py
> +''' This module contains the OpenMP Directives node implementation.'''
Done

2021-07-14 07:50 UTC, sergisiso commented on src/psyclone/psyir/nodes/omp_directives.py
> +from psyclone.core import AccessType, VariablesAccessInfo
Done I think

2021-07-14 07:53 UTC, sergisiso commented on src/psyclone/psyir/nodes/omp_directives.py
> +            end_text="end parallel do")
Done :)

2021-07-14 07:53 UTC, sergisiso commented on src/psyclone/psyir/transformations/psy_data_trans.py
> +from psyclone.psyGen import InvokeSchedule
Done

2021-07-14 07:55 UTC, sergisiso commented on src/psyclone/tests/nemo/transformations/openacc/kernels_directive_test.py
>  from psyclone.psyir.nodes import Assignment
Done

2021-07-14 07:57 UTC, sergisiso commented on src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
> +    from psyclone.psyir.nodes import OMPParallelDirective
Done

2021-07-14 07:57 UTC, sergisiso commented on src/psyclone/tests/nemo/transformations/openmp/openmp_test.py
>      from psyclone.transformations import OMPParallelLoopTrans
Done

2021-07-14 07:58 UTC, sergisiso commented on src/psyclone/tests/psyGen_test.py
> +# PSy,Invokes,Invoke, Kern,Arguments, Argument, KernelArgument
Done

2021-07-14 08:30 UTC, sergisiso commented
@arporter All comments addressed, this is ready for the next review.

2021-07-14 12:11 UTC, arporter approved these changes
All requested changes have been made.
All examples and tests are still OK with compilation.
Although some of the moved code is not covered, that's not the fault of this PR and as it's only moved I think we keep things simple and live with the lack of coverage.
Updated reference guide builds without new warnings.
This PR does not close #1208 so I've not searched the source for any refs to it.

2021-07-14 14:58 UTC, merged