Bring jupyter tutorials up-to-date (closes #1371)
stfc/PSyclone pull request #1372
Opened 2021-08-10 13:54 UTC by arporter

2021-08-11 07:11 UTC, arporter commented
This is ready for a first look now from @rupertford.

2021-08-12 00:01 UTC, rupertford requested changes
Thanks for doing this. There are just a few small issues. Note, I've also added a new issue (#1373) as the addition of directives into PSyIR is quite lax and can produce incorrect code pretty easily.

2021-08-12 07:20 UTC, arporter commented on tutorial/notebooks/introduction.ipynb
> +    "The nemo api takes a slightly different approach. In this case the input is the existing unmodified NEMO code. The reason for taking this approach is that the NEMO science developers do not want
Oops.

2021-08-12 07:34 UTC, arporter commented on tutorial/notebooks/introduction.ipynb
> +    "* an introduction to the lfric API;\n",
That's a good point. I've reworded some sections.

2021-08-12 07:35 UTC, arporter commented on tutorial/notebooks/nemo/nemo_example4.ipynb
> +    "_, _ = acc_kern_trans.apply(schedule.children[2:4])\n",
Yes, I tried that too :-)

2021-08-12 07:38 UTC, arporter commented on tutorial/notebooks/nemo/nemo_example4.ipynb
> +    "_, _ = acc_data_trans.apply([schedule.children[2]])"
Done.

2021-08-12 07:41 UTC, arporter commented on tutorial/notebooks/psyir/psyir_example1.ipynb
> +    "Every node in the PSyIR has a `view()` method which returns a text-based representation of itself and its children:"
Oops. I had the cell as `code` instead of `markdown` for some reason.

2021-08-12 07:42 UTC, arporter commented on tutorial/notebooks/psyir/psyir_example2.ipynb
> +    "if_block = psy.children[0].children[0]\n",
Yep, added.

2021-08-12 07:51 UTC, arporter commented on tutorial/notebooks/nemo/nemo_example3.ipynb
> +    "  allocate(a(jpi,jpj,jpk), b(jpi,jpj,jpk))\n",
Good point. I've extended it a bit to encourage (and help) users to start with an unmodified Schedule.

2021-08-12 07:58 UTC, arporter commented
Thanks for finding those problems. I've realised that GHA is *not* running the notebooks in the tutorial directory!

2021-08-12 08:57 UTC, arporter commented
OK, the CI is now running the tutorial notebooks and this is ready for another look...

2021-08-12 11:19 UTC, rupertford commented on tutorial/notebooks/nemo/nemo_example3.ipynb
> +    "  allocate(a(jpi,jpj,jpk), b(jpi,jpj,jpk))\n",
Unfortunately this is not enough and in fact the example as it is makes things more confusing. The NEMO api modifies the actual Fortran so if we use your example code the input fparser2 fortran now has a directive in it. This then gets parsed into PSyIR as a codeblock (comment) and the transformation fails saying there is a codeblock inside the loop. What we need to do is actually parse the Fortran again as well. If you could add the appropriate code to do that as part of the sample code that would be great.

2021-08-12 11:21 UTC, rupertford requested changes
Just one issue remaining, please see inline comment.

2021-08-12 20:56 UTC, arporter commented on tutorial/notebooks/nemo/nemo_example3.ipynb
> +    "  allocate(a(jpi,jpj,jpk), b(jpi,jpj,jpk))\n",
Oh yes, good point. Fixed now.

2021-08-12 20:58 UTC, arporter commented
This is ready to go again now. However I may have to just 'review' it myself...

2021-08-12 21:18 UTC, rupertford commented
I'm happy for you to put this on master if you have tested that the final change works as expected when doing the tutorial.

2021-08-13 07:55 UTC, arporter commented
All tests are clean and the tutorial notebooks are exercised. I've checked that editing the final cell in the 3rd part of the NEMO tutorial works as expected now that we start with a fresh parse tree.

2021-08-13 08:27 UTC, merged