(Towards #1374 ) Childless/Leaf directive
stfc/PSyclone pull request #1376
Opened 2021-08-17 11:29 UTC by LonelyCat124

This contains the initial childless/leaf directive implementation for #1374 . It is based upon the non-master branch, so is dependent on #1368 to be merged.

The idea is to handle directives which don't wrap around code, e.g.
```
!$omp taskwait
```
by removing the subtree which will never be used for codegen.

@arporter also thinks this can be applied to certain ACC directives, e.g. `ACCEnterDataDirective`. I don't see where the base implementation of that class uses its child schedule. Similarly for its child, `GOACCEnterDataDirective`. However, upon application to the `ACCEnterDataDirective` the build is faililng for a reason I don't understand. @sergisiso does this type of node seem reasonable to you?

2021-08-31 14:21 UTC, sergisiso requested changes
@AidanChalk I made a first look at the implementation and added a few inline comments. You will see the main comment is that I think we don't need all the intermediate node_str and dag_name methods as these should be abstract classes and probably don't need this functionality*.
(* I actually think that this 2 methods have to be slightly changed so they are only needed on the node super-class and avoid all the boilerplate code, but I will submit another issue for this) 

Other than the in-line comment I am still worried about OMPDirective not being a mixin, not because the code duplication which I think there isn't*, but because the `node.walk(OMPDirective)` will not pick up every OpenMP directive.
There are 2 solutions:
1) Is to change the name of OMPDirective and ACCDirective to OMPRegionDirective and ACCRegionDirective, so it is obvious in the walk method call that it will be missing things. But this will require to update all the `node.walk(OMPDirective)`-style code (some of it in scripts outside the codebase :/)
2) Use Mixin classes like:
```
class OMPDirective():
       _PREFIX = OMP

class OMPTaskwaitDirective(StandaloneDirective, OMPDirective):
     ... Same code ...

class OMPSerialDirective(RegionDirective, OMPDirective)
     ... Same code ...
```
and the same for the ACCDirectives tree.

\* I think the OMPDirective._get_reductions_list and the ACCDirective.validate_globals_constraints can both be moved to the generic RegionDirective as they are not specific of OMP or ACC. Also the node_str and dag_name as I mentioned earlier. So there is no code other than the prefix attribute for the Mixin which solve a few issues.

2021-08-31 14:48 UTC, LonelyCat124 commented
Ok - that makes sense I think. I'll try switching to Mixin classes and adjust the rest of the changes.

2021-08-31 15:09 UTC, sergisiso commented
Note that I created #1383, so if removing some intermediate dag_name and node_str creates some problems in this PR just leave them and it will be tacked in that next issue.

2021-09-02 14:06 UTC, LonelyCat124 commented on src/psyclone/psyir/backend/c.py
> +    def ompstandalonedirective_node(self, node):
I think the ompdirective_node already existed, I'll change this to RegionDirective and StandaloneDirective I think, it makes more sense and should work for ACC.

2021-09-02 14:37 UTC, sergisiso commented
You could put a `import pdb; pdb.set_trace()` in the visitor and it will open the debugger then when running the tests. Then you can check what is in the prefix attribute or do `bt` to get the backtrace.

Btw, have you removed the `_PREFIX = ""` in the generic directive, I think attributes on the first class resolution path have priority.

2021-09-02 14:41 UTC, LonelyCat124 commented
> Btw, have you removed the `_PREFIX = ""` in the generic directive?, I think attributes on the first class resolution path have priority.

This was the issue thanks!

2021-09-02 15:57 UTC, sergisiso commented
I see no reason to prevent the generation of C OpenACC pragmas if these are correct even if its a use case not fully tested yet.

2021-09-02 17:23 UTC, LonelyCat124 commented on src/psyclone/psyir/backend/c.py
> +        and the statements in between as a string (depending on the language).
Done

2021-09-02 17:26 UTC, LonelyCat124 commented on src/psyclone/psyir/backend/c.py
> +        # Note that {{ is replaced with a single { in the format call
Done

2021-09-02 17:27 UTC, LonelyCat124 commented on src/psyclone/psyir/backend/fortran.py
> +        the statements in between as a string (depending on the language).
Done

2021-09-02 17:28 UTC, LonelyCat124 commented on src/psyclone/psyir/backend/c.py
> +        result_list = ["#pragma {0}\n".format(node.begin_string())]
Done

2021-09-02 17:31 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/directive.py
>  ''' This module contains the Directive node implementation.'''
Done

2021-09-02 17:32 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/directive.py
> +    # The prefix to use when constructing this directive in Fortran
I've changed this comment (as I had to remove `_PREFIX`. Its a bit weird now though, not sure if `_PREFIX=None` would work with the new mixins or not.

2021-09-02 17:33 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/directive.py
> +    Based class for all Region Directive statements.
Done

2021-09-02 17:34 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/directive.py
> +                                                  parent=parent)
Done

2021-09-02 17:39 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/directive.py
> +__all__ = ["Directive", "RegionDirective", "StandaloneDirective"]
None of them can be put at the file top level (have checked) due to circular dependencies I think.

I think the error is changed to run like you've said now.

2021-09-02 17:39 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/omp_directives.py
> +    _children_valid_format = None
Done

2021-09-02 17:40 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/omp_directives.py
> +    _children_valid_format = None
Done

2021-09-02 17:41 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/directive.py
> +    _text_name = "Directive"
I think I've done this now.

2021-09-02 18:27 UTC, LonelyCat124 commented
Should I make the OMPRegion and OMPStandalone directives abstract classes again?

2021-09-02 18:30 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/omp_directives.py
> +class OMPDirective(RegionDirective):
I've removed them, I believe so.

2021-09-02 18:30 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/omp_directives.py
> +        return self.coloured_name(colour) + "[OMPStandalone]"
Done

2021-09-02 18:44 UTC, LonelyCat124 commented
Pylint is not super happy about the mixing classes as they have no public methods.

The `RegionDirective` expects the `_PREFIX` member to exist in its definition. The issue with this being in the mixin class is that it searches (as Sergi explained to me) the parent class up the Directives tree and finds that before using the Mixin's definition. I'm not sure what happens if I define _PREFIX as None here but I assume the same issue would arise. 
I think this is only a linting issue and the code works, but it seems a bit nasty. @sergisiso if I declared things as `class OMPStandaloneDirective(OMPDirective, StandaloneDirective)` would that solve the issue? Is that an appropriate fix if so?

2021-09-02 22:36 UTC, LonelyCat124 commented
Fingers crossed the tests all passs now :)

2021-09-03 09:24 UTC, sergisiso commented
@LonelyCat124 Changing the order of the classes is a good idea, give it a shoot to see if it improves things. If that allows adding the generic _PREFIX back it will be nicer from a OO point of view. But if not, no worries about the pylint issue if the reason, also you can ignore the "not enough methods" one.

2021-09-03 09:50 UTC, LonelyCat124 commented
The order swap seemed to work (at least for my local test runs) so I've done that and added `_PREFIX` back to the Directive class.

2021-09-08 11:03 UTC, sergisiso requested changes
@LonelyCat124 I like how the implementation turned out with the mixin and swaping the parent class order. This is almost ready, I just have some remaining issues when testing with "termcolor" and there are some minor clean ups to do (see comments about both things inline).

2021-09-08 11:32 UTC, LonelyCat124 commented on src/psyclone/psyir/backend/c.py
> +        '''This method is called when an REgionDirective instance is found in
Done

2021-09-08 11:32 UTC, LonelyCat124 commented on src/psyclone/psyir/backend/c.py
> +        print(type(node))
Yep, oops!

2021-09-08 11:38 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/acc_directives.py
> +    ''' Base mixin class for all OpenACC directive statements. '''
Done, though I changed class to class's (apparently the correct possessive of a singular class but looks weird to me anyway).

2021-09-08 11:39 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/omp_directives.py
> +    Base mixin class for all OpenMP-related directives.
Done

2021-09-08 11:59 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/nodes/directive_test.py
> +def test_childlessdirective_children_validation():
Done

2021-09-08 12:02 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/nodes/acc_directives_test.py
>  def test_accupdatedirective_begin_and_end_strings():
Done

2021-09-08 12:03 UTC, LonelyCat124 commented on src/psyclone/psyir/nodes/directive.py
> +    _text_name = "RegionDirective"
Done. Some tests are now flagged with TODO associated with #1383 as error messages no longer specify the class spawning the error message.

2021-09-08 18:29 UTC, LonelyCat124 commented
Ok, I think I fixed all the issues and merged the latest master.

2021-09-08 20:55 UTC, sergisiso approved these changes
@LonelyCat124 All comments addressed. Tests pass also with compilation, coverage of diff is complete, pycodestyle and pylint pass without relevant new issues. New classes/methods are well documented in docstrings, reference guide builds well and no additional documentation is needed. No TODOs remaining for this issues. This PR is ready to merge.

2021-09-08 22:33 UTC, merged