(closes #1383) Standardise and cleanup unneeded dag_name methods
stfc/PSyclone pull request #1409
Opened 2021-09-22 12:31 UTC by sergisiso

2021-09-22 13:03 UTC, sergisiso commented
@arporter @rupertford This is ready to review. It's the second PR to close #1383 , similar to the previous one I made the generic dag_name work as expected by most classes and then do a `grep -r "def dag_name" -A 10` and clean up all the methods that didn't do anything additional.

2021-09-23 13:59 UTC, arporter requested changes
Looks good Sergi.
All tests and examples OK with compilation.
All coverage is OK.
All docs build without new warnings.
Only major thing is whether we should remove `GOceanExtractNode` altogether as it doesn't implement any new functionality.
All changes are pycodestyle/pylint clean.

2021-09-23 13:59 UTC, arporter commented on src/psyclone/domain/gocean/nodes/gocean_extract_node.py
>      stand-alone driver program that can read the created output files.
This begs the question: do we need to subclass ExtractNode if we're not adding any functionality to it? I would suggest not but open the floor to @hiker and @rupertford for discussion.

2021-09-23 13:59 UTC, arporter commented on src/psyclone/psyir/nodes/node.py
> +        class and a index of its relative position to the parent Routine. If
s/a index/the index/

2021-09-23 13:59 UTC, arporter commented on src/psyclone/tests/psyir/nodes/node_test.py
> +    # Some classes have their won specialisation of the dag_name
s/won/own/

2021-09-27 13:39 UTC, sergisiso commented on src/psyclone/tests/psyir/nodes/node_test.py
> +    # Some classes have their won specialisation of the dag_name
Done

2021-09-27 13:39 UTC, sergisiso commented on src/psyclone/psyir/nodes/node.py
> +        class and a index of its relative position to the parent Routine. If
Done

2021-09-27 14:50 UTC, sergisiso commented
@arporter This is ready for another look.

2021-09-30 09:18 UTC, arporter requested changes
All requested changes have been made.
All tests and examples are OK with compilation.
All docs build without new warnings.
I'd taken the liberty of bringing this up-to-date with master but then I discovered that there are still two TODOs referencing 1383 in `directive_test.py`. Please could you investigate.

2021-09-30 10:01 UTC, sergisiso commented
@arporter Aha, this are meant to be referencing #1388, updated now. I also pinned jsonschema to fix CI issues with older python. This is ready for another look.

2021-09-30 19:09 UTC, merged