(closes #1456) Updates to PSyAD test harness to allow for precision.
stfc/PSyclone pull request #1476
Opened 2021-10-29 08:07 UTC by arporter

2021-11-05 21:44 UTC, rupertford requested changes
Good stuff. Suggestions are minor and mainly about the user guide. There is one suggestion to add another exception for the main psyad script. All code is pycodestyle and pylint clean apart from one highlighted case. All examples run, including the harness example - whoop!

2021-11-12 10:05 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +Test Harness
Done.

2021-11-12 10:13 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +The code generated for the test harness must perform the following steps:
Done.

2021-11-12 10:21 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +Some of these steps are described in more detail below.
Done.

2021-11-12 10:22 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +is set to match that of the active variables in the supplied TL kernel.
Done.

2021-11-12 10:22 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +will remain constant for both the TL and adjoint kernel calls). It may be
I've made it explicit.

2021-11-12 10:24 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +that this will require refinement in future, e.g. if there are kernels
Re-worded although I think dofmap arrays will be fine. I'm sure there are other things that might not be though.

2021-11-12 10:24 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +    INTEGER_TYPE, REAL_TYPE
You are correct.

2021-11-12 10:39 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +                raise NotImplementedError(
Done.

2021-11-12 10:40 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +                    "Found active variables of different datatype: '{0}' is "
Good point, done.

2021-11-12 10:42 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +def _get_active_variable_datatype(kernel, active_variables):
Done.

2021-11-12 10:43 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +    statements[0].preceding_comment = ("Initialise the kernel arguments and "
Yes, this is becoming a common problem (e.g. for the OpenCL code generation). I chose to do it this way as it keeps it language agnostic and saves us having to worry about how to distribute and build any supporting code.

2021-11-12 10:43 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> +relative_diff
Done.

2021-11-12 10:46 UTC, arporter commented
This is just waiting on Tim's answers to the questions about the implementation of the check for equality of the two inner products.

2021-11-12 10:57 UTC, rupertford commented
> This is just waiting on Tim's answers to the questions about the implementation of the check for equality of the two inner products.

I'm happy to review the other changes in the meantime if that would be useful.

2021-11-12 11:01 UTC, arporter commented
That's a good idea; let's be asynchronous :-)

2021-11-12 17:26 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +   their absolute difference by this spacing;
Updated now.

2021-11-18 16:05 UTC, rupertford commented on doc/psyad/user_guide/implementation.rst
> +will remain constant for both the TL and adjoint kernel calls). It may be
I'm afraid I still don't understand the point you are making. Is it that passive variables remain constant and therefore can be included in the inner product computation without affecting the correctness test?

2021-11-18 16:28 UTC, rupertford commented on src/psyclone/psyad/tl2ad.py
> +                raise NotImplementedError(
I suggest merging this with `KeyError` i.e. `(KeyError, NotImplementedError)`

2021-11-18 16:33 UTC, rupertford commented on src/psyclone/tests/psyad/main_test.py
> +relative_diff
Could you please explain how the error comes about in `test_main_not_implemented_error` in a sentence at the end of the docstring (see previous test `test_main_keyerror` as an example).

2021-11-18 16:36 UTC, rupertford requested changes
Just a few small remaining requests. All else is OK. Please also bring branch up-to-date.

2021-11-19 12:22 UTC, arporter commented on doc/psyad/user_guide/implementation.rst
> +will remain constant for both the TL and adjoint kernel calls). It may be
Yes. I've tried re-writing with your words :-)

2021-11-19 12:24 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +                raise NotImplementedError(
Oh yes, that's better.

2021-11-19 12:26 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> +relative_diff
Done.

2021-11-19 12:32 UTC, arporter commented
CI-happiness permitting, this is ready for another look.

2021-11-20 01:17 UTC, rupertford commented on doc/psyad/user_guide/implementation.rst
> +will remain constant for both the TL and adjoint kernel calls). It may be
Thanks, that sounds much better (to me).

2021-11-20 01:21 UTC, rupertford approved these changes
All issues have been addressed. Approving.

2021-11-20 12:48 UTC, merged