(Closes #1484) Remove Py2 from GHA and update documentation
stfc/PSyclone pull request #1501
Opened 2021-11-16 12:40 UTC by arporter

2021-11-18 08:32 UTC, arporter commented
Ready for review now.

2021-11-18 15:02 UTC, rupertford requested changes
Great stuff. Just a few small things related to the changes.

2021-11-18 16:15 UTC, arporter commented on .github/workflows/python-package.yml
> +        # TODO cannot do this while we still have code left from our support
Rather than create yet another issue I've fixed the outstanding flake8 errors and enabled this check.

2021-11-18 16:17 UTC, arporter commented on doc/user_guide/getting_going.rst
> +``configparser``, ``fparser`` and ``pyparsing``. The easiest way to satisfy
Done.

2021-11-18 16:36 UTC, arporter commented on setup.py
> +                          'six', 'jsonschema==3.0.2'],
Yes, it was Python 3.5 that we had the problem with. Created a new issue to track removal of six and added TODO.
Hoist by my own petard re the pylint warnings! They're fixed now.

2021-11-18 16:37 UTC, arporter commented on src/psyclone/tests/dynamo0p3_test.py
> -    reason="Deepcopy of function_space not working in Python 3")
I had a choice to remove the test entirely or just try it and see whether it now works and it does! import of `sys` removed.

2021-11-18 16:39 UTC, arporter commented on src/psyclone/tests/exceptions_test.py
> -import sys
Fixed various pylint errors.

2021-11-18 16:43 UTC, arporter commented on src/psyclone/tests/generator_test.py
> -    # monkeypatch the six module so that the check on which Python
Oops.

2021-11-18 16:48 UTC, arporter commented on src/psyclone/tests/parse/utils_test.py
> +    kwargs = dict(encoding='utf8')
Fixed plus a couple of others.

2021-11-18 17:04 UTC, arporter commented
GHA-happiness permitting, this is ready for another look now.

2021-11-19 16:18 UTC, rupertford commented
@arporter. All is good with this PR but it has a conflict. Could you please fix and update then I can merge to master.

2021-11-19 16:57 UTC, arporter commented
Updated to master and conflict resolved. Ready for another look.

2021-11-20 00:52 UTC, rupertford approved these changes
All issues have been addressed. Approving.

2021-11-20 01:44 UTC, merged