[LFRic] script to remove halo exchanges (closes #1593)
stfc/PSyclone pull request #1594
Opened 2022-01-28 00:22 UTC by rupertford

2022-01-28 11:41 UTC, rupertford commented
Ready for first review from @arporter assuming CI checks are successful

2022-02-01 14:06 UTC, arporter requested changes
A very conservative (small 'c') implementation that is suitably restrictive. However, if this is going to go on to master then it should be exercised in one of the examples, ideally including compilation checking, and the respective documentation updated.

That said, given that in #1542 we have agreed to permit a kernel to specify a 'WRITE' access for a field on a continuous function space, we could just park this ticket.

2022-02-01 14:06 UTC, arporter commented on examples/lfric/scripts/rm_hex.py
> +invoke_info = {
Presumably the idea is that there will be a copy of this script for each algorithm that needs modifying. It would therefore be better if the functionality was separate to the specification of the halo exchanges to delete. However, this is only an example so it can stay as is.

2022-02-03 02:27 UTC, rupertford commented
Given that we have an agreed solution that uses the kernel metadata I don't see a need for this script. It was only to demonstrate that it is possible if needed and it is now not needed. I suggest that I withdraw this PR and issue #1593 and explain why in a comment. Do you agree @arporter?

2022-02-03 08:03 UTC, arporter commented
Yes, I agree that this can be closed.

2022-02-03 09:17 UTC, rupertford commented
As agreed, this script will not go on master as another better solution has been agreed.

2022-02-03 09:17 UTC, closed without merging