Fix gocean alg psyir error (closes #753)
stfc/PSyclone pull request #1597
Opened 2022-01-31 16:01 UTC by rupertford

Fixes a bug reported by @hiker in the new psyir-based algorithm tranformation for the gocean1.0 api. With these changes the game-of-life example provided by @hiker compiles and runs.

2022-01-31 16:02 UTC, rupertford commented
Changes were based on those suggested by @sergisiso (thanks).

2022-01-31 16:45 UTC, rupertford commented
Ready for review from any of @arporter, @sergisiso, @hiker, @TeranIvy. This is a small bug fix.

2022-02-03 10:03 UTC, arporter requested changes
Thanks for fixing this.
A few things need tidying up.
All tests and examples are OK with compilation.
This is a small bug fix so no docs need updating.
There is still a TODO referring to #753.
I've checked all files with pylint.

2022-02-07 15:34 UTC, rupertford commented on src/psyclone/domain/common/algorithm/psyir.py
> +            nodes = [node for node in nodes if not
Yes that is better thanks.

2022-02-07 15:37 UTC, rupertford commented on src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
> +    name for a routine_symbol and a container symbol.
Oops.

2022-02-07 15:42 UTC, rupertford commented on src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
> +    invoke = psyir.children[0].children[0][0]
In the next line we call `_check_alg_names()` and this already does that assert.

2022-02-07 15:49 UTC, rupertford commented on src/psyclone/domain/common/algorithm/psyir.py
>  #
The TODO is correct, it is the title of this PR that was wrong. This PR should not close #753 as there is more to do. I've changed the title.

2022-02-07 16:10 UTC, rupertford commented
Ready for next review from @arporter

2022-02-08 11:46 UTC, arporter commented on src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
> +    invoke = psyir.children[0].children[0][0]
OK.

2022-02-08 11:50 UTC, arporter commented on src/psyclone/tests/domain/common/algorithm/alg_psyir_test.py
> +    psyir = create_alg_psyir(code)
Oh yes, I see that `_check_alg_names` does more than I realised.

2022-02-08 12:00 UTC, arporter approved these changes
All requested changes have been made.
All tests and examples are OK with compilation.
All docs build OK.

2022-02-08 13:20 UTC, merged