remove reference to dynamo0.1 api in the documentation (closes #282)
stfc/PSyclone pull request #1598
Opened 2022-01-31 17:25 UTC by rupertford

2022-01-31 17:26 UTC, rupertford commented
Turns out there is very little reference to dynamo0.1 in the documentation so this is a pleasantly small PR.

2022-02-01 06:53 UTC, TeranIvy commented
Happy to take this, as well as #1599 when it's ready.

2022-02-02 15:16 UTC, TeranIvy requested changes
Thanks for taking this on. All looks straightforward. I ran the tests with compilation to be on the safe side and I also built the User and the Developer guide. All was well.

I have a couple of suggestions inline. I also grepped for `0.1` and `0p1` in the documentation and found one occurence of `dynamo0.1` in the Develope guide and a few occurences of `gocean0.1` API. I am aware that the Gocean 0.1 API is being removed in another PR, however I am listing what I found here for reference.

Mentions of Dynamo 0.1: `developer_guide/APIs.rst:53:.. currently supports the following APIs; dynamo versions 0.1 and 0.3`

Mentions of GOcean 0.1:
```
developer_guide/APIs.rst:54:.. and gocean versions 0.1 and 1.0.
thebigpicture.mm:128:<node COLOR="#000000" CREATED="0" MODIFIED="0" TEXT="gocean0.1">
user_guide/configuration.rst:145:                        "gocean0.1", "gocean1.0" and "nemo"). If there is no
user_guide/psyclone_command.rst:83:                          'gocean0.1', 'gocean1.0', 'nemo'],
```

2022-02-02 15:31 UTC, rupertford commented on doc/user_guide/psy_layer.rst
> +    # This example uses version 0.3 of the Dynamo API
Good idea.

2022-02-02 15:32 UTC, rupertford commented on doc/user_guide/configuration.rst
> +                        APIs supported by PSyclone ("dynamo0.3",
Modified.

2022-02-02 15:36 UTC, rupertford commented
Sorry for missing the reference to dynamo0.1 in the developer's guide, I was a bit sloppy with the grep. Should be OK now. Ready for next review from @TeranIvy subject to CI happiness.

2022-02-02 16:49 UTC, TeranIvy commented
I'll update this after #1578 is on.

2022-02-02 17:03 UTC, TeranIvy approved these changes
All well now. There are still some references to `dynamo0.1` in the generated documentation, however this is due to the auto-generated documentation of some transformation classes and should be resolved by #1599.

Proceeding to merge if the CI is happy.

2022-02-02 17:17 UTC, merged