Improve Node.view() method (closes #1528)
stfc/PSyclone pull request #1613
Opened 2022-02-08 23:48 UTC by rupertford

Adds support for changing the indentation depth, switching off coloured text and returns a string rather than printing to stdout.

2022-03-28 17:01 UTC, rupertford commented
This looks ready for review to me. Probably one for @arporter or @sergisiso

2022-03-29 13:11 UTC, arporter requested changes
Looks good - this is a nice improvement.
Just minor things and places where you've not updated the notebooks:

    $ find . -name \*.ipynb -exec grep -H 'view[(]' {} \;
    ./nemo/nemo_example1.ipynb:    "The `view()` method provides a textual view of the PSyIR  tree:"
    ./nemo/nemo_example1.ipynb:    "schedule.view()"
    ./nemo/nemo_example2.ipynb:    "schedule.view()"
    ./nemo/nemo_example4.ipynb:    "schedule.view()"
    ./nemo/nemo_example4.ipynb:    "schedule.view()"
    ./nemo/nemo_example3.ipynb:    "schedule.view()"
    ./nemo/nemo_example3.ipynb:    "schedule.view()"
    ./nemo/nemo_example3.ipynb:    "schedule.view()"

    $ find . -name \*.rst -exec grep -H 'view[(]' {} \;
    ./doc/developer_guide/psyir.rst:   ``view()`` methods.
    ./doc/developer_guide/psyir.rst:    >>> schedule.view()
    ./doc/user_guide/profiling.rst:    schedule.view()
    ./doc/user_guide/profiling.rst:    schedule.view()
    ./doc/user_guide/psyke.rst:  schedule.view()
    ./doc/user_guide/psyke.rst:  schedule.view()
    ./doc/user_guide/getting_going.rst:By default, the ``view()`` method available on any PSyIR (PSyclone
    ./doc/user_guide/psy_layer.rst:in two ways. First the `view()` method outputs textual information about
    ./doc/user_guide/psy_layer.rst:   >>> schedule.view()
    ./doc/user_guide/transformations.rst:    > schedule.view()
    ./doc/user_guide/transformations.rst:    > schedule.view()

    $ find . -name \*.md -exec grep -H 'view[(]' {} \;
    ./tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/README.md:`schedule.view()` prints out a view of the whole schedule). You will
    ./tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/README.md:    schedule.view()
    ./tutorial/practicals/LFRic/single_node/2_openacc/README.md:    schedule.view()
    ./tutorial/practicals/nemo/1_nemo_psyir/README.md:4. Use the `view()` method of one of these `InlinedKern` nodes to
    ./tutorial/practicals/nemo/1_nemo_psyir/README.md:   kernels[0].view()

There's a TODO 1238 in transformations.rst and tl2ad.py also has two mentions of 1238.

2022-03-29 13:11 UTC, arporter commented
Forgot to say, all tests and examples are OK with compilation.
Changes are pylint clean.

2022-04-02 23:02 UTC, rupertford commented on src/psyclone/psyir/nodes/node.py
Removed.

2022-04-02 23:21 UTC, rupertford commented on src/psyclone/psyir/nodes/node.py
>      def list(self, indent=0):
Removing it does not affect any tests so I've assumed it is OK.

2022-04-02 23:29 UTC, rupertford commented on src/psyclone/tests/psyir/nodes/node_test.py
>  import os
Done.

2022-04-02 23:30 UTC, rupertford commented on src/psyclone/tests/psyir/nodes/range_test.py
> +def test_range_view():
OK.

2022-04-02 23:39 UTC, rupertford commented
I can't believe I missed so many required changes from ***.view() to print(***.view()). Thanks for finding them. There were a load more in the examples directories too. You will see that there are a lot more modified files now (another 80 or so). I think I've got them all. In terms of referencing the associated issue, I could not find a reference in tl2ad.py.

2022-04-02 23:53 UTC, rupertford commented
Ready for next review from @arporter

2022-04-04 10:03 UTC, arporter approved these changes
All looks good. I can't find any old uses of view() now.
Tests and examples are all OK with compilation.
Docs all build fine.

2022-04-04 10:05 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +    preprocess_trans(tl_psyir, active_variables)
Now that I've updated to master this has been resolved.

2022-04-04 10:35 UTC, merged