(Towards #1618) add transformation to convert InvokeCall to Call.
stfc/PSyclone pull request #1666
Opened 2022-03-18 09:23 UTC by arporter

2022-03-18 16:38 UTC, arporter commented
This PR essentially takes the code that 'lowered' an InvokeCall into a Call out of the `lower_to_language_level` method and puts it in a new transformation. This then makes it possible to generate true Algorithm layer code (complete with `call invoke(...)`) or to create transformed algorithm code containing standard calls to PSy-layer subroutines. As part of this I've also renamed the existing 'raising' transformation to hopefully make things a bit clearer.

If the CI is green then this is ready to go. Probably one for @rupertford or perhaps @sergisiso.

2022-03-28 15:24 UTC, rupertford requested changes
Looks great. The tests are failing so could you please take a look. I've made some comments inline but they are pretty much cosmetic.

2022-03-29 08:06 UTC, arporter commented on src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
> +from psyclone.core import SymbolicMaths
Done although we don't have a rule for that says the imported names ought to be in alpha order.

2022-03-29 08:07 UTC, arporter commented on src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
> +        :type options: dict of str:values or None
I think so. Done.

2022-03-29 08:07 UTC, arporter commented on src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
> +        :type options: dict of str:values or None
Done.

2022-03-29 08:23 UTC, arporter commented on src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
> +def test_ai2psycall_validate():
'tis done.

2022-03-29 08:27 UTC, arporter commented on src/psyclone/domain/common/transformations/alg_trans.py
> +from psyclone.domain.common.transformations import RaiseCall2InvokeTrans
Oops, sorry.

2022-03-29 08:46 UTC, arporter commented on src/psyclone/domain/lfric/transformations/lfric_alg_invoke_2_psy_call_trans.py
> +        :type options: dict of str:values or None
In fact, I've updated the Dev Guide appropriately too.

2022-03-29 10:27 UTC, arporter commented on src/psyclone/tests/domain/lfric/transformations/lfric_alg_invoke_2_psy_call_trans_test.py
> +# Author A. R. Porter, STFC Daresbury Lab
Probably. I've added you.

2022-03-29 12:04 UTC, arporter commented
Ready for another look now.

2022-04-01 14:49 UTC, rupertford requested changes
Very nearly there. Just one issue with conformance and a request to modify the documentation. Everything is pycodestyle and pylint clean. docs build. file-to-file coverage is 100%

2022-04-01 14:49 UTC, rupertford commented on src/psyclone/tests/domain/lfric/algorithm/lfric_alg_psyir_test.py
>  def test_aic_defcontainerrootname():
domain/lfric/algorithm/lfric_alg_psyir_test.py:52:0: W0611: Unused Reference imported from psyclone.psyir.nodes (unused-import)

2022-04-01 19:19 UTC, arporter commented on doc/developer_guide/transformations.rst
> +order to support both use cases, PSyclone provides a transformation that
Done.

2022-04-01 19:21 UTC, arporter commented on src/psyclone/tests/domain/lfric/algorithm/lfric_alg_psyir_test.py
>  def test_aic_defcontainerrootname():
Oops, done.

2022-04-01 19:22 UTC, arporter commented
Requested changes made and brought up-to-date with master. Ready for another look assuming CI happiness.

2022-04-03 23:25 UTC, rupertford approved these changes
All issues have been addressed. Approving.

2022-04-03 23:54 UTC, merged