(Closes #1643) Extend Matmul2CodeTrans to support matrix-matrix
stfc/PSyclone pull request #1676
Opened 2022-03-30 09:57 UTC by arporter

2022-03-30 14:20 UTC, arporter commented
This is ready for a first look now from either @rupertford or @sergisiso.

2022-04-08 12:03 UTC, rupertford requested changes
Looks good. Comments/requests are inline.

2022-04-22 07:29 UTC, arporter commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +        do i=1,P
Oh yes, switched.

2022-04-22 07:35 UTC, arporter commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +        if len(vector.symbol.shape) > 2 and not vector.children:
Yes, better.

2022-04-22 07:42 UTC, arporter commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +    For a matrix-vector multiplication, if the dimensions of ``R``, ``A``,
Good point, done.

2022-04-22 07:44 UTC, arporter commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +            if len(vector.children) > 2:
Oops.

2022-04-22 07:48 UTC, arporter commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +        be for the full index space for that dimension (i.e. array
Yes, done.

2022-04-22 10:24 UTC, arporter commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +        # Create "result(i,j)"
Oh yes, that's nicer.

2022-04-22 10:27 UTC, arporter commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +        # Add the new code to the PSyIR
Oh yes, much better.

2022-04-22 10:31 UTC, arporter commented
CI-permitting, this is ready for another look now.

2022-04-23 22:47 UTC, rupertford commented on src/psyclone/psyir/transformations/intrinsics/matmul2code_trans.py
> +        do i=1,P
Thanks for switching but it also needs switching in the docstring.

2022-04-24 00:22 UTC, rupertford approved these changes
All looks good. I've taken the liberty of fixing a small docstring error. Approving.

2022-04-24 00:22 UTC, merged