(Closes #717) lift where restrictions
stfc/PSyclone pull request #1696
Opened 2022-04-21 13:54 UTC by arporter

2022-05-11 20:42 UTC, arporter commented
This is ready for a first look now, probably from @sergisiso. In the end it just rationalises what was duplicated functionality to find the rank of an array subsection. It may be that we really want the routine (rank_of_subsection) to give us back the *shape* of any subsection, possibly using `Range` nodes.  I could change what I have to do that or we could stick with what I have so far and do that as a subsequent step.

2022-05-24 16:42 UTC, sergisiso requested changes
You maybe already hinted it here:

> It may be that we really want the routine (rank_of_subsection) to give us back the shape of any subsection

But this recursion method to find the slice rank is somewhat similar to what @rupertford was planning to implement in order to 'bubble up' the datatypes too all PSyIR expression (datanodes) nodes. I can't find the specific issue but we had a chat during Easter week and Rupert was about to started implementing it. (starting with operations but accessors must also be part of it for a complete solution)

Given that this .datatype property for all expression nodes will be more generic (and would avoid having the slightly confusing "rank_of_subsection" in nodes that have nothing to do with arrays like member and structurereference) I think the methods you add in this PR could at some point be superseded by .datatype and simply be: 
```
rank_slice = len(top_node.datatype.shape)
```

Note that for a reference `a(3,:)`
`ref.symbol.datatype is ArrayType([3, Extent.ATTRIBUTE])`
but
`ref.datatype is  ArrayType([Extent.ATTRIBUTE])`
which is the information you need. 

Since you may need this to fix current Nemo issues with where statements and the .datatype may take a while. I am fine to accept this PR if you address the other comments I have and add some comments/TODO about the possible temporary nature of the methods.
But if @rupertford can shed some light on the progress on this and maybe you can combine efforts to go for a single solution, it would be even better.

2022-07-07 15:16 UTC, arporter commented on src/psyclone/psyir/nodes/structure_reference.py
> +                if any(isinstance(idx_expr, Range) for idx_expr in
Yes, my understanding is that it is not valid anywhere.

2022-07-07 15:18 UTC, arporter commented on src/psyclone/tests/psyir/nodes/array_member_test.py
> +from psyclone.errors import GenerationError, InternalError
Fixed.

2022-09-07 14:33 UTC, closed without merging