Switch to f-strings in the PSyIR source
stfc/PSyclone pull request #1722
Opened 2022-05-17 00:10 UTC by nmnobre

2022-05-19 13:26 UTC, arporter requested changes
Good stuff Nuno. In general makes the code more readable I think.
There are a few places where you've touched lines that use the old `six.raise_from` so I'm requesting that you update those. I also have a query about your use of `chr(10)` to replace `'\n'`.
All tests still pass with compilation enabled and the examples are OK too.
Build of ref. guide is unchanged.

Just a note to remind you to let me close the conversations as there's a lot to keep track of :-)

2022-05-19 13:26 UTC, arporter commented on src/psyclone/psyir/transformations/omp_taskwait_trans.py
> +                    raise TransformationError(LazyString(
Please add a comment here explaining why you have `chr(10)`. Could you have `'\n'` instead?

2022-05-19 13:26 UTC, arporter commented on src/psyclone/psyir/transformations/omp_taskwait_trans.py
> +                                       f"{fwriter(taskloop).rstrip(chr(10))}"))
Again, comment about `chr(10)` please (if it's not possible/wise to reinstate the `'\n'`?).

2022-05-24 14:59 UTC, nmnobre commented
Hi @arporter, I believe the latest commit addresses all the issues you raised. 🙂

2022-05-25 07:59 UTC, arporter commented on src/psyclone/psyir/transformations/omp_taskwait_trans.py
> +                    raise TransformationError(LazyString(
Great, thanks.

2022-05-25 08:17 UTC, arporter requested changes
Almost there now. I would have merged it but we've gained a lot of pycodestyle errors:

    $ pycodestyle psyclone/
    psyclone/psyir/transformations/arrayrange2loop_trans.py:141:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/transformations/arrayrange2loop_trans.py:289:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/transformations/fold_conditional_return_expressions_trans.py:101:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/transformations/omp_taskwait_trans.py:168:78: W291 trailing whitespace
    psyclone/psyir/transformations/omp_taskwait_trans.py:253:70: W291 trailing whitespace
    psyclone/psyir/frontend/fparser2.py:1893:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/nodes/array_of_structures_mixin.py:104:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/nodes/omp_directives.py:891:25: E128 continuation line under-indented for visual indent
    psyclone/psyir/symbols/datasymbol.py:232:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/symbols/symbol.py:190:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/backend/language_writer.py:235:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/backend/opencl.py:226:80: E501 line too long (80 > 79 characters)
    psyclone/psyir/backend/sir.py:261:19: E128 continuation line under-indented for visual indent
    psyclone/psyir/backend/sir.py:262:18: E128 continuation line under-indented for visual indent
    psyclone/psyir/backend/sir.py:263:18: E128 continuation line under-indented for visual indent
    psyclone/psyir/backend/sir.py:264:18: E128 continuation line under-indented for visual indent
    psyclone/psyir/backend/sir.py:265:18: E128 continuation line under-indented for visual indent
    psyclone/psyir/backend/sir.py:266:18: E128 continuation line under-indented for visual indent

Apart from that, tests and examples are all OK with compilation.
Ref guide still builds fine.

2022-05-25 08:57 UTC, nmnobre commented
> Almost there now. I would have merged it but we've gained a lot of pycodestyle errors:
> 
> ```
> $ pycodestyle psyclone/
> psyclone/psyir/transformations/arrayrange2loop_trans.py:141:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/transformations/arrayrange2loop_trans.py:289:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/transformations/fold_conditional_return_expressions_trans.py:101:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/transformations/omp_taskwait_trans.py:168:78: W291 trailing whitespace
> psyclone/psyir/transformations/omp_taskwait_trans.py:253:70: W291 trailing whitespace
> psyclone/psyir/frontend/fparser2.py:1893:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/nodes/array_of_structures_mixin.py:104:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/nodes/omp_directives.py:891:25: E128 continuation line under-indented for visual indent
> psyclone/psyir/symbols/datasymbol.py:232:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/symbols/symbol.py:190:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/backend/language_writer.py:235:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/backend/opencl.py:226:80: E501 line too long (80 > 79 characters)
> psyclone/psyir/backend/sir.py:261:19: E128 continuation line under-indented for visual indent
> psyclone/psyir/backend/sir.py:262:18: E128 continuation line under-indented for visual indent
> psyclone/psyir/backend/sir.py:263:18: E128 continuation line under-indented for visual indent
> psyclone/psyir/backend/sir.py:264:18: E128 continuation line under-indented for visual indent
> psyclone/psyir/backend/sir.py:265:18: E128 continuation line under-indented for visual indent
> psyclone/psyir/backend/sir.py:266:18: E128 continuation line under-indented for visual indent
> ```
> 
> Apart from that, tests and examples are all OK with compilation. Ref guide still builds fine.

Just to clarify, the majority of these were already there before your previous comment right?

2022-05-25 09:05 UTC, nmnobre commented
> > Just to clarify, the majority of these were already there before your previous comment right?
> 
> I don't know when they appeared but they're not there on master :-)

Sure, I was just a bit confused since I didn't touch the majority of those files in yesterday's commits.

2022-05-25 10:31 UTC, nmnobre commented
Done. 😊

Since I'm here, do you also see a bunch of E302 errors under `./tutorial/practicals/LFRic/distributed_memory` ?

2022-05-25 10:42 UTC, arporter commented
Oh yes, I do! I never normally run pycodestyle over that (my bad).

2022-05-25 10:56 UTC, nmnobre commented
Sorted. 😄

2022-05-25 12:32 UTC, arporter approved these changes
Code is squeaky clean now.
Tests and examples all still OK after bringing branch up to master.
Will proceed to merge.

2022-05-25 13:12 UTC, merged