Minor fixes for mlc and a CI test + Improvements for a package's initialisation
stfc/PSyclone pull request #1729
Opened 2022-05-25 14:33 UTC by nmnobre

2022-05-26 08:02 UTC, arporter requested changes
Thanks for fixing these things Nuno.
All tests and examples are OK with compilation.
Only suggestion I have is to try removing the `__all__` list from the `__init__.py` as I suspect we don't need it.

2022-05-26 19:56 UTC, nmnobre commented on src/psyclone/psyir/transformations/__init__.py
> +__all__ = ['TransformationError',
So I take it you agree we can't do this as it stands?

2022-05-26 20:02 UTC, nmnobre commented on src/psyclone/psyir/transformations/__init__.py
> +from psyclone.psyir.transformations.transformation_error \
Done, I just needed to adjust two other files :)
Apologies for the force pushing... I was careful not to rewrite the history prior to your review/comments though.

2022-06-01 08:25 UTC, arporter approved these changes
All requested changes have been made.
I've taken the liberty of fixing the one (very minor) conflict with master.
Tests and examples are all OK with compilation.
Ref guide builds with no new warnings.

2022-06-01 08:50 UTC, merged