Update operator infrastructure and change use statements for CMA operators (for #1738)
stfc/PSyclone pull request #1740
Opened 2022-06-01 21:01 UTC by TeranIvy

- Updates CMA operator data (`columnwise_matrix`) to `r_solver` in test kernels and examples.
- Updates operator and CMA operator infrastructure and separates them.
- Removes the use of `operator_mod` for CMA operator and operator proxy types and adds the use of `columnwise_operator_mod`.

2022-06-08 08:28 UTC, arporter requested changes
Great job Iva, I only have one small request.
All examples, tests and tutorials are OK with compilation.
Updated UG builds fine.
Does this branch work OK with LFRic?

2022-06-08 17:55 UTC, TeranIvy commented on examples/lfric/eg7/alg.x90
You're right. Fixed.

2022-06-09 08:36 UTC, arporter commented
Assuming the CI is green, is this ready for review again @TeranIvy?

2022-06-09 08:57 UTC, TeranIvy commented
I am just testing this with LFRic, @arporter, so I will return it as soon as the test suite is done.

2022-06-09 10:48 UTC, TeranIvy commented
I built the PSyclone test environment from this branch on Spice and Crays XC40 and XCS. I then ran an LFRic test branch that has all the changes for PSyclone 2.3.0 implemented (see [LFRic ticket 3288, comment 6](https://code.metoffice.gov.uk/trac/lfric/ticket/3288#comment:6)). The developer test suites were all fine. 

This PR ready to go so I am returning it to @arporter for another look.

2022-06-09 11:01 UTC, arporter approved these changes
All requested changes have been made.
Tests and examples are still OK with compilation.
Proceeding to merge.

2022-06-09 11:30 UTC, merged