Fix invalid adjoint names for subroutine and module (closes #1717)
stfc/PSyclone pull request #1763
Opened 2022-06-19 10:15 UTC by rupertford

prepend `adj_` to tangent-linear module and subroutine names rather than appending as appending breaks the LFRic rules about ending in `_mod`, `_code`, etc. Also removes prepended `tl_` if it exists in the original tangent linear name. Metadata names (metadata `_type` and reference to code are not updated as this is waiting on proper parsing of kernel metadata).

2022-06-23 21:05 UTC, rupertford commented
Ready for first review from @arporter

2022-06-24 07:33 UTC, arporter requested changes
All good apart from one minor typo.
Tests and examples are all OK with compilation.
Only omission is documentation. I've checked and actually we say nothing about the naming of the adjointed code and I think we should - just a couple of sentences should do it.

2022-06-24 10:29 UTC, rupertford commented on src/psyclone/psyad/tl2ad.py
> +#: names when generating : the adjoint. If the original name contains
Oops.

2022-06-24 21:34 UTC, rupertford commented
Added a section about naming.

2022-06-24 22:07 UTC, rupertford commented
Ready for next review from @arporter

2022-06-30 11:56 UTC, arporter approved these changes
All requested changes have been made.
Doc updated and builds fine.
All examples and tests OK with compilation.

2022-06-30 14:03 UTC, merged