[Otter] Update interface with Otter to reflect upstream changes
stfc/PSyclone pull request #1781
Opened 2022-06-29 15:00 UTC by adamtuft

This PR is for review by @LonelyCat124 

This PR updates the interface to Otter to reflect the latest changes to Otter in [v0.2.0](https://github.com/Otter-Taskification/otter/tree/v0.2.0). These changes include:

- Renaming several Otter API entrypoints,
- Changing the arguments passed to several entrypoints,
- Removing the `otterTaskSingle[Begin|End]` entrypoint which no longer exists.

2022-07-21 12:46 UTC, LonelyCat124 commented
@arporter @sergisiso Is there a way to override the testing system to work on PRs that don't involve master?

2022-07-21 17:03 UTC, arporter commented
You can add "[skip ci]" to the commit message if that's what you're after?

2022-07-21 18:07 UTC, LonelyCat124 commented
The opposite, I want ci to run on this branch before I merge it into my branch. I can do it manually if needed but was hoping it could be done here.

2022-07-27 13:37 UTC, LonelyCat124 requested changes
Hi @adamtuft , a few tests are failing in `src/psyclone/tests/psyir/transformations/otter_transformations_test.py` and `src/psyclone/tests/psyir/nodes/otter_nodes_test.py`

The root of the issue appears to be to do with the arguments to the calls. Do these calls no longer expect `__FILE__, 'functioncall', __LINE__` as arguments? If not we'll need to make additional changes in PSyclone - but unless there have been other changes in Otter I'd missed I think they still will for the Fortran version.

2022-07-27 13:37 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/nodes/otter_nodes_test.py
> +    assert len(calls[0].children) == 0
Hi Adam,

Not sure whats happened here but this test is broken - looks like you changed some stuff here to do with the calls for the argument, might wanted to revert these lines.

2022-07-27 13:37 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/nodes/otter_nodes_test.py
> +    assert len(calls[0].children) == 0
Same issue here.

2022-07-27 13:37 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/nodes/otter_nodes_test.py
> +    assert calls[0].children[0].value == "0"
Again here

2022-07-27 13:37 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/nodes/otter_nodes_test.py
> +    assert len(calls[0].children) == 0
and here.

2022-07-27 13:37 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/transformations/otter_transformations_test.py
> -        '''CALL fortran_otterLoopBegin_i(__FILE__, 'invoke_0_compute_cu', __LINE__)
This test also fails, the arguments are still produced in the code.

2022-07-27 13:37 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/transformations/otter_transformations_test.py
> -        '''CALL fortran_otterSynchroniseDescendantTasksBegin_i(__FILE__, 'invoke_0_compute_cu', __LINE__)
Arguments still produced in the output code but not in the test.

2022-07-27 13:37 UTC, LonelyCat124 commented on src/psyclone/tests/psyir/transformations/otter_transformations_test.py
> -      CALL fortran_otterSynchroniseChildTasks_i(__FILE__, 'invoke_0_compute_cu', __LINE__)'''
Arguments still produced in the output code but not in the test.

2024-01-05 12:04 UTC, LonelyCat124 commented
With all the changes to Otter I think we're going to try to swap to using PSyData to do the otter profiling. I'm going to leave this PR open for now while we work on that but this will be closed later

2024-04-03 15:03 UTC, closed without merging