(Closes #1771) Refactor algorithm-creation functionality.
stfc/PSyclone pull request #1785
Opened 2022-07-04 13:13 UTC by arporter

Alters what was `domain.lfric.alg_gen` so that it only exposes an `LFRicAlg` class which can be used to construct Algorithm-layer PSyIR from kernel metadata.

2022-07-06 04:12 UTC, hiker requested changes
Nicely done (I would have been happy with all functions just being static members of this class as a kind of namespace, but of course, using an instance is much better in case that this needs to be extended in the future).
You would just have to confirm if the class is missing on purpose from the docs, and if you want a ticket to replace manually setting __all__, and bring it up to trunk, then I'll merge this in.

2022-07-11 07:28 UTC, arporter commented on src/psyclone/domain/lfric/algorithm/__init__.py
> +from psyclone.domain.lfric.algorithm.lfric_alg import LFRicAlg
It's the adding things to `__all__` that seems to cause the problems/warnings when building the reference guide, and, as you say, it only seems needed in order to support `from blah import *` which we don't do. I've just checked the reference guide built from this source and LFRicAlg is still there so I think it's OK.

2022-07-11 08:35 UTC, arporter commented on src/psyclone/domain/lfric/algorithm/__init__.py
> +from psyclone.domain.lfric.algorithm.lfric_alg import LFRicAlg
I was wrong. I've added LFRicAlg to the `__all__` list now (and corrected the comment).

2022-07-11 09:03 UTC, arporter commented
Ready for another look now.

2022-07-12 01:10 UTC, hiker commented on src/psyclone/kernel_tools.py
> +from psyclone.domain.lfric.algorithm import LFRicAlg
I've opened #1793 for this, mentioning the duplicated symbols and just in case also the above code that avoids setting `__all__` explicitly.

2022-07-12 02:07 UTC, hiker approved these changes
All issues have been resolved, ready to merge.

2022-07-12 02:07 UTC, merged