psyad unary minus fix [closes 1583]
stfc/PSyclone pull request #1795
Opened 2022-07-12 11:36 UTC by rupertford

2022-07-15 08:38 UTC, arporter requested changes
Fix is good.
All tests and examples are fine with compilation.
I just found two of the comments a bit confusing so please could you reword slightly.
Optionally, would you mind fixing the f-string warnings in `psyad/transformations/assignment_trans.py`?

2022-07-15 08:38 UTC, arporter commented on src/psyclone/tests/psyad/transformations/test_assignment_trans.py
> +    the lhs of an expression.
s/an expression/a rhs expression/

2022-07-15 08:38 UTC, arporter commented on src/psyclone/tests/psyad/transformations/test_assignment_trans.py
> +    the lhs of an expression.
s/an expression/a rhs expression/

2022-07-21 19:44 UTC, rupertford commented on src/psyclone/tests/psyad/transformations/test_assignment_trans.py
> +    the lhs of an expression.
modified

2022-07-21 19:45 UTC, rupertford commented on src/psyclone/tests/psyad/transformations/test_assignment_trans.py
> +    the lhs of an expression.
modified.

2022-07-21 19:48 UTC, rupertford commented
I've made the requested changes and brought the branch up to master. There are no warnings in `psyad/transformations/assignment_trans.py`. I'm guessing an earlier PR has already sorted these out. Ready for next review from @arporter.

2022-07-25 07:05 UTC, arporter requested changes
All requested changes have been made.
Tests and examples still all OK with compilation.
This is a bug fix so no documentation update required.
Will proceed to merge.

2022-07-25 08:49 UTC, arporter approved these changes

2022-07-25 08:49 UTC, merged