1797 psydata logical support
stfc/PSyclone pull request #1803
Opened 2022-07-18 01:09 UTC by hiker

Fixes #1797 by adding support for Logical data types to PSyData libraries. In detail:
- `read-only` test: convert logical to 0/1 and use this as checksum.
- `nan-test`: tread logical as int and disable ieee function calls that are only defined for reals
- `profile`: no change, since the profiling lib does not provide any functions for variables
- `extraction`: support writing and reading logical values. Since (afaik) NetCDF does not support logical, the logicals are converted to int (and back)

Note that no psyclone code was changes, so no tests were added. The problems with logical variables happens only at compile time (since the generic interface cannot find an implementation for logicals). I have added a logical scalar to the LFRic extraction example. Again, afaik there are no arrays of logicals possible, so I could not add a test for handling of logical arrays.

2022-07-25 08:50 UTC, arporter requested changes
All good. All examples (and tests) OK with compilation.
Just a few files that need their copyright dates updating.

2022-07-25 08:50 UTC, arporter commented on lib/process.py
> +             "logical": ("Logical", "Logical(kind=4)", 4),
Please update the copyright date.

2022-07-25 08:54 UTC, arporter commented
I think the dev. guide needs updating slightly - particularly https://psyclone-dev.readthedocs.io/en/latest/psy_data.html#jinja-support-in-the-base-class.

2022-07-26 02:25 UTC, hiker commented on examples/lfric/eg17/full_example_extract/testkern_w0_kernel_mod.f90
> +     type(arg_type), dimension(3) :: meta_args =       &
Oops. Fixed.

2022-07-26 02:25 UTC, hiker commented on lib/process.py
> +             "logical": ("Logical", "Logical(kind=4)", 4),
Fixed.

2022-07-26 02:26 UTC, hiker commented
> I think the dev. guide needs updating slightly - particularly https://psyclone-dev.readthedocs.io/en/latest/psy_data.html#jinja-support-in-the-base-class.

Indeed, I totally missed that. Fixed now.

2022-07-26 02:26 UTC, hiker commented on examples/lfric/eg17/full_example_extract/main.x90
> +    use constants_mod,          only: r_def, i_def, l_def
Fixed.

2022-07-26 06:53 UTC, arporter approved these changes
All requested changes have been made.
Dev. guide has been updated and builds and looks fine.
Will proceed to merge.

2022-07-26 08:01 UTC, merged