disallow functions in PSyAD (closes #1681)
stfc/PSyclone pull request #1808
Opened 2022-07-21 21:47 UTC by rupertford

2022-07-21 23:16 UTC, rupertford commented
Ready for first review from @arporter

2022-08-01 07:29 UTC, arporter requested changes
Looks good.
Tests and examples all OK with compilation.
Docs updated and build fine.
All changes are pylint clean and covered.
Just one tiny request to add the offending function name to the error message and then this can be merged.

2022-08-01 07:29 UTC, arporter commented on src/psyclone/psyad/tl2ad.py
> +                "function. Please re-write as a subroutine.")
f"Please re-write '{routine.name}' as a subroutine"

2022-08-03 11:31 UTC, rupertford commented on src/psyclone/psyad/tl2ad.py
> +                "function. Please re-write as a subroutine.")
Good idea. Updated.

2022-08-03 13:44 UTC, rupertford commented
Ready for next review from @arporter

2022-08-08 07:29 UTC, arporter approved these changes
The one requested change has been made.
I'll proceed to merge once I've double-checked compilation tests and examples.

2022-08-08 08:39 UTC, merged