1813 standalone extract
stfc/PSyclone pull request #1845
Opened 2022-08-22 07:18 UTC by hiker

This is the stand-alone extraction library. Note that I have not added compilation tests (which we can do) to keep the patch smaller.

2022-08-24 08:40 UTC, hiker commented
This is ready for a first review, but ideally would be done after merging #1831 (which will likely cause some clashes).

Note that the link checking will fail because the links to the standalone library, which I have added, do not exist yet.

2022-09-05 04:50 UTC, hiker commented
I believe the link check is caused by the stand-alone directory missing, which this PR will add. And I don't understand the coverage issue at all (I believe I might have removed one covered line, which might slightly reduce the percentage of covered lines??)

2022-09-06 05:51 UTC, hiker commented
OK, I hope I've fixed all incorrect references to NetCDF. The link-check errors are expected since they point to paths that do not yet exist on master. The coverage issue should just be a hiccup (i.e. removed covered lines --> percentage of covered lines decreases).
Ready for first review.

2022-09-06 12:46 UTC, arporter requested changes
Looks good Joerg. It all worked for me when I tried building and running the various things.
Just a few minor suggestions to address and then this can go on.
Docs have all been updated.
As you say, the link check fails because the path that this branch introduces is not yet on master.
Examples work.

2022-09-07 14:07 UTC, hiker commented on examples/gocean/eg5/extract/README.md
> +
Good idea.

2022-09-07 14:07 UTC, hiker commented on examples/lfric/eg17/full_example_extract/README.md
> +
Indeed.

2022-09-07 14:08 UTC, hiker commented on lib/extract/netcdf/dl_esm_inf/kernel_data_netcdf.f90
Indeed, a lot of unnecessary code in there.

2022-09-07 14:10 UTC, hiker commented on doc/user_guide/psy_data.rst
> +  libraries that extract input and output data into a either a Fortran
Done.

2022-09-07 14:10 UTC, hiker commented on doc/user_guide/psyke.rst
> +IO to write and read kernel data.
Good point.

2022-09-07 14:11 UTC, hiker commented on examples/gocean/eg5/extract/README.md
> +    $ TYPE=netcdf make
Very good point.

2022-09-07 14:11 UTC, hiker commented on examples/gocean/eg5/extract/README.md
> +The binary will either be called ``extract.standalone`` or ``extract.netcdf``.
Done.

2022-09-07 14:12 UTC, hiker commented on examples/gocean/eg5/extract/README.md
> +subdirectories. To create and compile the example, modify the Makefile
I believe that was just a 'standard' sentence (e.g. feel free to put your preferred compiler into the Makefile so you don't have to add F90=... all the time). But agreed, it's better without this.

2022-09-07 14:12 UTC, hiker commented on examples/gocean/eg5/extract/README.md
> +This examples uses the ``extract_transform.py`` transformation script
Done.

2022-09-07 14:12 UTC, hiker commented on examples/gocean/eg5/extract/README.md
> +computed. These drivers will be compiled by the Makefile as well.
Done.

2022-09-07 14:12 UTC, hiker commented on examples/gocean/eg5/extract/README.md
>  When running the program, you should see:
Done.

2022-09-07 14:13 UTC, hiker commented on examples/lfric/eg17/full_example_extract/README.md
> +    $ TYPE=netcdf make
Indeed.

2022-09-07 14:18 UTC, hiker commented on lib/extract/netcdf/dl_esm_inf/doxyfile
> -# Doxyfile 1.8.6
No, I think this file was added by mistake(?). No other doxyfile is in psyclone, and I looked at the log, it looks like it was added accidentally while fixing other, unrelated documentation issues.

2022-09-07 14:19 UTC, hiker commented on lib/extract/standalone/extract_standalone_base.jinja
> +        ! A '%' is added to avoid a clash if the user should have say
Nope ... copy & paste :)

2022-09-07 14:23 UTC, hiker commented on lib/extract/standalone/lfric/README.md
> +parameters of instrumented code regions to a stand-alone [binary
Fixed.

2022-09-12 12:43 UTC, arporter approved these changes
All requested changes have been made.
All tests and examples are OK with compilation.
All docs build OK.
Will proceed to merge.

2022-09-12 13:19 UTC, merged