Add support for inlining functions (closes #1882)
stfc/PSyclone pull request #1884
Opened 2022-09-19 17:32 UTC by rupertford

2022-10-05 18:15 UTC, rupertford commented
Ready for first review, probably from @arporter or @sergisiso. This is a small change to the inline transformation to add support for inlining functions.

2022-10-12 14:39 UTC, rupertford commented on src/psyclone/tests/psyir/transformations/inline_trans_test.py
> +
Added.

2022-10-12 18:06 UTC, rupertford commented on src/psyclone/tests/psyir/transformations/inline_trans_test.py
> +        "    real :: func\n\n"
We get invalid code :-). Fixed.

2022-10-12 19:21 UTC, rupertford commented
Ready for next review from @arporter.

2022-10-13 08:49 UTC, arporter requested changes
Requested changes have been made and I'm happy with the functionality now.
Tests and examples all compile OK.
No other changes have been made.
I would merge but there are two print statements that I think can be removed.
Once that's done I will merge...

2022-10-13 08:49 UTC, arporter commented on src/psyclone/psyir/transformations/inline_trans.py
> +        print(f"Looking for {name}")
Please remove these prints.

2022-10-13 12:15 UTC, rupertford commented on src/psyclone/psyir/transformations/inline_trans.py
> +        print(f"Looking for {name}")
Doh.

2022-10-13 12:16 UTC, rupertford commented
Sorry about that. Should be OK now. Ready for next review from @arporter, GHA willing.

2022-10-13 13:19 UTC, merged