(Closes #1903) rationalise OMP schedule values
stfc/PSyclone pull request #1905
Opened 2022-10-05 13:15 UTC by arporter

2022-10-05 13:29 UTC, arporter commented
Note to self: check testing of OMPParallelDoDirective.gen_code as test for `schedule` rather than `schedule != "none" wasn't picked up.

2022-10-12 15:32 UTC, arporter commented
I need to check the various examples that involve OpenMP and then this can go for review.

2022-10-20 15:51 UTC, arporter commented
I've checked, and the various examples that show OpenMP appear to be correct.

Ready for first review from @sergisiso.

2022-10-26 09:22 UTC, sergisiso requested changes
@arporter This is a nice improvement on the OpenMP schedule behavior. There is just some minor suggestions to fix. pycodestyle, pylint, tests, codecov, TODOs and documentation building is all good.

A further question is now that the behavior matches the OpenMP standard would it make sense to remove the LFRic and Gocean own default to 'static' schedule or do you prefer to keep them.
(in practice it doesn't change much because most implementations default to static if no env var is found - it is mainly to be closer to the standard)

2022-11-11 10:42 UTC, arporter commented on src/psyclone/tests/psyir/nodes/omp_clause_test.py
> +            "'guided', 'auto', 'none']. Found test." in str(excinfo.value))
Oops.

2022-11-11 10:43 UTC, arporter commented on src/psyclone/tests/psyir/nodes/omp_directives_test.py
> +    private clause changes appropriately. Also check that changing the schedule
Good spot!

2022-11-11 10:43 UTC, arporter commented on src/psyclone/tests/psyir/nodes/omp_directives_test.py
> +    pdir._omp_schedule = "none"
Oh yes.

2022-11-11 10:50 UTC, arporter commented on src/psyclone/tests/psyir/nodes/omp_directives_test.py
> +    assert "schedule(" not in code
Done.

2022-11-11 11:14 UTC, arporter commented
CI permitting, this is ready for another look. I'd prefer to leave the GOcean and LFRic defaults alone for now.

2022-11-11 13:53 UTC, sergisiso approved these changes
@arporter All comments addressed and all check/formatting/docs still pass. This is approved to merge.

2022-11-11 14:35 UTC, merged