1967 create proper signatures for argument structures
stfc/PSyclone pull request #1972
Opened 2022-11-30 04:38 UTC by hiker

A small patch so that arguments that are structures (`something%ncell_3d`) are turned into proper signatures when collecting the variable accesses. Previously it would be using a 1-element using the whole string, instead of a 2-element signature with `(something, ncell_3d)`.

2023-01-09 04:53 UTC, hiker commented
Ready for review, the link check failures appear to be unrelated.

2023-01-10 10:26 UTC, arporter requested changes
Looks good.
All tests and examples are OK with compilation.
Ref. guide builds without new warnings.
Just a couple of minor things to address.

2023-01-12 05:40 UTC, hiker commented on src/psyclone/core/signature.py
Done.

2023-01-12 05:49 UTC, hiker commented on src/psyclone/tests/domain/lfric/kern_call_arg_list_test.py
>          'cell', 'nlayers', 'op_a_proxy%ncell_3d', 'op_a_proxy%local_stencil',
@arporter I am not sure how to create this kind of code? As far as I can see, `op_a_proxy(2)` is in the PSyLayer, i.e. must be created by PSyclone. Even if I declare an array:
```
  type(operator_type) :: op_a(3)  
  call invoke(enforce_operator_bc_kernel_type(op_a(2)))
```
the PSyLayer will just see a single `operator_type` argument, so it won't create an array of proxies. I tried to create a vector of operators, but got:
```
In the LFRic API, vector notation is only supported for ['gh_field'] argument types but found 'gh_operator * 3'
```

So I am not sure what to do.

FWIW, vector fields are tested, e.g.:
```
    assert create_arg_list._arglist == [
        'nlayers', 'f1_proxy%data', 'f2_proxy(1)%data', 'f2_proxy(2)%data',
        'f2_proxy(3)%data', 'f3_proxy%data', 'istp', 'ndf_w2', 'undf_w2',
        'map_w2(:,cell)', 'basis_w2_qr_xyoz', 'basis_w2_qr_face', 'ndf_wchi',
```

2023-01-12 05:56 UTC, hiker commented
Should be ready for next review.

2023-01-12 09:23 UTC, arporter commented on src/psyclone/tests/domain/lfric/kern_call_arg_list_test.py
>          'cell', 'nlayers', 'op_a_proxy%ncell_3d', 'op_a_proxy%local_stencil',
Ah, that's OK then. I just didn't look very carefully - apologies.

2023-01-12 09:51 UTC, arporter approved these changes
All requested changes have been made.
Tests, examples and ref. guide are still fine.
Issue no. is not mentioned anywhere.
Will proceed to merge.

2023-01-12 11:28 UTC, merged