1978 update lfric infrastructure and psydata
stfc/PSyclone pull request #1980
Opened 2022-12-09 00:11 UTC by hiker

This adds support for 32- and 64-bit fields to all PSyData libraries. Note that atm we don't have an easy way of testing these libraries (see #1979 for the missing bit), but I have successfully used the LFRic NetCDF extraction library with gungho, which is mixed precision.

This PR:
- adds the new infrastructure files to support 32- and 64-bit fields
- updates all PSyData libraries using jinja to fully support mixed precision.

2022-12-09 00:52 UTC, hiker commented
The CI failure is not my fault, like like python 3.6. is not available anymore??

I have also fixed #1529 with this (i.e. I've also added compilation for eg19).

2022-12-20 10:27 UTC, TeranIvy requested changes
Thanks for the updates to the infrastructure and libraries, especially the first one was long overdue.

I also like that infrastructure interface libraries are now Jinja templates as this is much more flexible. They would benefit from some tidying up, though (see the inline comments).

There was nothing to check for `pycodestyle` and `pylint`. I checked building of documentation to be on the safe side and that works.

`pytest` without compilation and `make` in `examples` without compilation also work.

However, things break when I try to compile.

* `pytest --compile` with GCC 11.2.0 returns this:

```
E           cd field; gfortran -Wall -g -fcheck=bound -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/configuration -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/field -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/function_space -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/initialisation -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/io -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/mesh -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/operator -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/scalar -I /var/tmp/pytest-of-ikavcic/pytest-47/dynamo_wrapper0/utilities -c /net/home/h06/ikavcic/PSyclone_work/PSyclone/src/psyclone/tests/test_files/dynamo0p3/infrastructure//field/field_mod.F90 -o field_mod.o
E           $HOME/PSyclone_work/PSyclone/src/psyclone/tests/test_files/dynamo0p3/infrastructure//field/field_mod.F90:25:7:
E           
E              25 |   use field_r64_mod, only: field_type         => field_r64_type, &
E                 |       1
E           Fatal Error: Cannot open module file 'field_r64_mod.mod' for reading at (1): No such file or directory
E           compilation terminated.
E           make: *** [field/field_mod.o] Error 1
```
* `make compile` in `examples/lfric` also breaks. Trying to run `make clean` and recompiling is not working. The already compiled libraries and modules are not removed, I suspect due to a double slash in paths, e.g.
```
../../../src/psyclone/tests/test_files/dynamo0p3/infrastructure//mesh -I ../../../src/psyclone/tests/test_files/dynamo0p3/infrastructure//operator -I ../../../src/psyclone/tests/test_files/dynamo0p3/infrastructure//scalar -I ../../../src/psyclone/tests/test_files/dynamo0p3/infrastructure//utilities -c scaled_matrix_vector_kernel_mod.F90
```
* `git ignore` should be updated for the `lfric/eg11` example as `git status` after make returns
```
eg11/helmholtz_solver_alg_mod.f90
eg11/helmholtz_solver_alg_psy.f90
```

* `git status` in all examples after `make` returns:
 ```
 gocean/eg3/opencl_kernels_0.cl
 lfric/eg11/helmholtz_solver_alg_mod.f90
lfric/eg11/helmholtz_solver_alg_psy.f90
nemo/eg3/traldf_iso.F90
psyad/eg1/test_harness.f90
psyad/eg1/testkernadj_mod.f90
psyad/eg2/adj_hydrostatic_kernel_mod.F90
psyad/eg2/adj_hydrostatic_kernel_mod.x90
psyad/eg2/adjoint_test_mod.F90
psyad/eg2/adjoint_test_mod.x90
psyad/eg2/psy.f90
```

2022-12-21 11:55 UTC, hiker commented on examples/lfric/eg19/Makefile
> +GENERATED_FILES = psy.f90 alg.f90 *.o *.mod
Done.

2022-12-21 12:04 UTC, hiker reviewed
You commented in several places about the alignment. FWIW, the alignment is all done so that the produced .f90 files are properly aligned. I decided to do that originally so the produced Fortran code does not look auto-produced.

But I totally get that we could focus on readability of the .jinja files. I don't mind, I just thought I point the reason for this strange indentation out, and leave it to you to decide which is the better solution, since I can't decide ;)

2022-12-21 12:04 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +        type(field_r{{prec}}_type), dimension(:), intent(in)     :: value
See below.

2022-12-21 12:04 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +        type(field_r{{prec}}_type), dimension(:), intent(in)     :: value
See below.

2022-12-21 12:04 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +                           DeclareFieldVector_r{{prec}},&
See below.

2022-12-21 12:04 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +                           ProvideFieldVector_r{{prec}},&
See below.

2022-12-21 12:04 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +        type(field_r{{prec}}_type), dimension(:), intent(in)             :: value
See below.

2022-12-21 12:04 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +{# Added this as jinja code so that it is understood that the
Done ... here and everywhere.

2022-12-21 12:05 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +{{ "! THIS FILE IS CREATED FROM THE JINJA TEMPLATE FILE  !" }}
Done ... here and everywhere.

2022-12-21 12:05 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +{{ "! DO NOT MODIFY DIRECTLY                             !" }}
Done ... here and everywhere.

2022-12-21 12:05 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +    !> This subroutine declares an LFric real-valued {{prec}}-bit field vector.
Done.

2022-12-21 12:07 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +        ! Provide each component of the vector as an individual 1d array.
Done ... here and everywhere.

2022-12-21 12:07 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +        ! The base class will re-allocate internal array sizes if required
Done.

2022-12-21 12:07 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +    !> This subroutine declares an LFRic field with real-valued
Done ... here and everywhere.

2022-12-21 12:07 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +    !> This subroutine writes the values of an LFRic real-valued {{prec}}-bit field.
Done ... here and everywhere.

2022-12-21 12:08 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +    !> This subroutine declares an LFric real-valued {{prec}}-bit field vector.
Done ... here and everywhere.

2022-12-21 12:08 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +    !> This subroutine writes an LFRic real-valued {{prec}}-bit field vector to
Done ... here and everywhere.

2022-12-21 12:08 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +        ! Provide each dimension of the vector as an individual 1d array.
Done ... here and everywhere.

2022-12-21 12:08 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +    !> This subroutine declares an LFRic field with integer-valued data.
Done ... here and everywhere.

2022-12-21 12:08 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +    !> This subroutine writes the values of an LFRic integer-valued field.
Done ... here and everywhere.

2022-12-21 12:08 UTC, hiker commented on lib/extract/netcdf/lfric/kernel_data_netcdf.jinja
> +        class(extract_PsyDataType), intent(inout), target :: this
Done.

2022-12-21 12:08 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +{# Added this as jinja code so that it is understood that the
Done ... here and everywhere.

2022-12-21 12:09 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +{{ "! THIS FILE IS CREATED FROM THE JINJA TEMPLATE FILE  !" }}
Done ... here and everywhere.

2022-12-21 12:09 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +{{ "! DO NOT MODIFY DIRECTLY                             !" }}
Done ... here and everywhere.

2022-12-21 12:09 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +    !> This subroutine writes the values of an LFRic real-valued {{prec}}-bit field.
Done ... here and everywhere.

2022-12-21 12:09 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +    !> This subroutine declares an LFric real-valued {{prec}}-bit field vector.
Done ... here and everywhere.

2022-12-21 12:09 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +        ! The base class will re-allocate internal array sizes if required
Done.

2022-12-21 12:09 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +    !> This subroutine writes an LFRic real-valued {{prec}}-bit field vector to
Done ... here and everywhere.

2022-12-21 12:10 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +    !> This subroutine declares an LFRic field with integer-valued data.
Done ... here and everywhere.

2022-12-21 12:10 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +    !> This subroutine writes the values of an LFRic integer-valued field.
Done ... here and everywhere.

2022-12-21 12:10 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +    !! @param[in,out] this The instance of the extract_PsyDataType.
Done.

2022-12-21 12:12 UTC, hiker commented on lib/extract/standalone/lfric/kernel_data_standalone.jinja
> +        class(extract_PsyDataType), intent(inout), target :: this
Done.

2022-12-21 12:12 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +{# Added this as jinja code so that it is understood that the
Done ... here and everywhere.

2022-12-21 12:12 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +{{ "! THIS FILE IS CREATED FROM THE JINJA TEMPLATE FILE  !" }}
Done ... here and everywhere.

2022-12-21 12:12 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +{{ "! DO NOT MODIFY DIRECTLY                             !" }}
Done ... here and everywhere.

2022-12-21 12:13 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +    !> This subroutine checks whether a real-valued LFRic field has NAN or
Done ... here and everywhere.

2022-12-21 12:13 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +        if (this%verbosity>1) then
Done.

2022-12-21 12:13 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +    !> This subroutine declares LFRic real-valued field vectors. No
Done ... here and everywhere.

2022-12-21 12:13 UTC, hiker commented on lib/nan_test/lfric/nan_test.jinja
> +    !> This subroutine declares LFRic integer-valued fields. No functionality
Done ... here and everywhere.

2022-12-21 12:13 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +{# Added this as jinja code so that it is understood that the
Done ... here and everywhere.

2022-12-21 12:13 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +{{ "! DO NOT MODIFY DIRECTLY                             !" }}
Done ... here and everywhere.

2022-12-21 12:14 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +    !> This subroutine declares a real-valued {{prec}} bit field based on
Done ... here and everywhere.

2022-12-21 12:14 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +    !> This subroutine declares a vector of real-valued {{prec}}-bit
Done ... here and everywhere.

2022-12-21 12:14 UTC, hiker commented on lib/read_only/lfric/read_only.jinja
> +    !> This subroutine declares an integer field based on the LFRic
Done ... here and everywhere.

2022-12-21 12:19 UTC, hiker commented
Thank you very much for the very detailed review (feel free next time to just post one comment and tell me to fix it everywhere :)  ).

I have fixed most (all?) of the suggestions in all jinja files, even the ones not originally included in the PR. In hindsight maybe that's a bit confusing, but at least now all .jinja files under lib are consistent. I would suggest not to review the new files that have only changes in comments (1d -> 1D; "." and "!" in warning message,; jinja->Jinja, !>@brief). I've commented them all as "Done ... here and everywhere." :)

Sorry for the compilation problem, I somehow forgot to update the dependency file :( 

Re 'make clean' not removing the library: that's on purpose, there is a special target 'allclean' which removes all libraries external to the example.

Should be ready for next review.

2023-02-08 09:10 UTC, merged