(closes #1986) Fixes LFRic OpenMP issues by skipping dep_analysis on PSy coloured loops
stfc/PSyclone pull request #1994
Opened 2022-12-19 16:20 UTC by sergisiso

2022-12-19 16:47 UTC, sergisiso commented
@arporter This is ready to review. It fixes the current issues with LFRic OpenMP in master.

(Unfortunately it reverses some LFRic loop bounds to Literal['NotInitialized'] I think because the better boundaries were given by some call inside the dependency_analysis call stack)

2023-01-03 10:25 UTC, arporter requested changes
Sorry to be a pain but I'd like to understand why changes to the validation have caused a change in the loop bounds displayed in the PSyIR. That doesn't seem to be good/expected behaviour so it would be good to get to the bottom of it.
Apart from that there are just a few minor things to tidy.
Tests and examples are all OK with compilation.
No need to update documentation.
Issue number is not mentioned anywhere.

2023-01-03 18:58 UTC, sergisiso commented on src/psyclone/transformations.py
>          :raise TransformationError: if an OMP loop transform would create \
Fixed

2023-01-03 18:58 UTC, sergisiso commented on src/psyclone/transformations.py
> +        ''' Perform Dynamo 0.3 specific loop validity checks for the
Done

2023-01-03 18:59 UTC, sergisiso commented on src/psyclone/transformations.py
> +        ''' Apply Dynamo 0.3 specific OMPLoopTrans.
Done

2023-01-03 19:00 UTC, sergisiso commented on src/psyclone/transformations.py
> +        :param node: the Node in the Schedule to check
Done

2023-01-03 19:34 UTC, sergisiso commented
@arporter This is ready for next review.

> Sorry to be a pain but I'd like to understand why changes to the validation have caused a change in the loop bounds displayed in the PSyIR. That doesn't seem to be good/expected behaviour so it would be good to get to the bottom of it.

It is because calling DependencyTools.can_loop_be_parallelised() or not in LFRic changes the tree.

Ideally it shouldn't change it, but right now when recursing down the tree at some point it calls a
`loop.start_expr` semantic navigation property, which in LFRic (src/psyclone/dynamo0p3.py::7685) if its set to 'not initialized' it automatically replace the bound expression to a newly created reference.

This should be fixed when we get rid of the 'not initialized' bounds completely, but since we are not there yet as a quickfix I believe we changed the semantic navigation to dynamically change the tree when acessed. I think this is partially discussed in #1876

2023-01-04 10:00 UTC, arporter commented
> Ideally it shouldn't change it, but right now when recursing down the tree at some point it calls a `loop.start_expr` semantic navigation property, which in LFRic (src/psyclone/dynamo0p3.py::7685) if its set to 'not initialized' it automatically replace the bound expression to a newly created reference.

OK, thanks for explaining - I'm happy now :-)

2023-01-04 10:16 UTC, arporter approved these changes
All requested changes have been made.
Tests and examples are all OK with compilation.
Ref. guide has new errors but they aren't the fault of this PR (and I've taken the liberty of fixing them as it was just missing continuation symbols in a doc string).
Will proceed to merge.

2023-01-04 10:34 UTC, merged