#2009 : Fix hardcoding value forcing parsing fortran as free-form
stfc/PSyclone pull request #2014
Opened 2023-01-17 16:15 UTC by svalat

Add optional `free_form` option to parser to handle fixed form fortran.

Feel free to say if you want it another way.

2023-01-18 08:36 UTC, arporter requested changes
I like the fix - thanks very much for doing this PR.
There are just a few pycodestyle errors to fix.
All tests and examples are OK with compilation.
Reference guide builds without new warnings.
Coverage of the diff is 100%.

2023-01-18 08:36 UTC, arporter commented on src/psyclone/psyir/frontend/fortran.py
> +    def psyir_from_source(self, source_code, free_form = True):
Please could you fix the formatting errors reported by pycodestyle for this file.

2023-01-18 08:36 UTC, arporter commented on src/psyclone/psyir/frontend/fortran.py
> +        :param free_form: If parsing free-form code or not (default False).
"default True" I think?

2023-01-18 08:36 UTC, arporter commented on src/psyclone/tests/psyir/frontend/fortran_test.py
> +FIXED_FORM_CODE = '''
Please could you fix the various pycodestyle complaints about this file too.

2023-01-21 02:41 UTC, svalat commented
All fixed.

2023-01-24 08:33 UTC, arporter approved these changes
Thanks for making those changes.
All tests and examples are OK with compilation.
Ref. guide builds fine.
Will proceed to merge.

2023-01-24 08:33 UTC, merged