#1545: changing DynCollection to LFRicCollection
stfc/PSyclone pull request #2090
Opened 2023-03-31 13:42 UTC by mo-lottieturner

closes #1545

2023-04-20 12:22 UTC, TeranIvy commented
Note: To be merged after #2095 is merged.

2023-05-25 15:02 UTC, TeranIvy requested changes
Nice work! There are some things to tidy up, mainly cosmetic (see inline). Please also refresh the branch with the master after the review comments are addressed.

Tests with compilation pass, LFRic examples as well, and developer guide builds and reads well.

2023-05-25 15:04 UTC, TeranIvy commented
Back to @mo-lottieturner 😄

2023-05-25 16:18 UTC, mo-lottieturner commented on src/psyclone/domain/lfric/lfric_collection.py
> +''' This module implements the PSyclone Dynamo 0.3 API by 1)
this was copied across from the dynamo0p3 file - have edited to make it LFRicCollection-specific

2023-05-25 16:20 UTC, mo-lottieturner commented on src/psyclone/domain/lfric/lfric_collection.py
> +            # We are handling declarations/initialisations for an Invoke
I thought we were doing no full stops on single line comments?

2023-05-25 17:09 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_collection.py
> +            # We are handling declarations/initialisations for an Invoke
You're right! Please ignore this comment. If you see full stops at the end of one-line comments please remove them :)

2023-05-25 17:12 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_collection.py
> +''' This module implements the PSyclone Dynamo 0.3 API by 1)
Yes, that's why I suggested "LFRic (Dynamo 0.3) API", so it has LFRic in. We'll remove mentions of Dynamo 0.3 eventually.

2023-05-30 16:18 UTC, mo-lottieturner commented
Back to @TeranIvy

2023-06-01 13:53 UTC, TeranIvy requested changes
Thanks for making changes! There's just one thing to fix (see inline) and the branch needs an update with the master and then it can go on :smile:

2023-06-01 13:53 UTC, TeranIvy commented on src/psyclone/domain/lfric/__init__.py
> +    'LFRicCollection'
`pylint` says: `__init__.py:76:4: E0603: Undefined variable name 'LFRicCollectionLFRicConstants' in __all__ (undefined-all-variable)`. 

I think there should be a comma :smile:

2023-06-01 16:25 UTC, TeranIvy approved these changes
All well now. Retested and re-built documentation. Updated changelog and user guide. Proceeding to merge.

2023-06-01 17:07 UTC, merged