algorithm arguments fix (towards #1618)
stfc/PSyclone pull request #2129
Opened 2023-05-05 14:47 UTC by rupertford

The new approach to parsing the algorithm layer using the PSyIR did not support negative literal values as arguments. This PR fixed this.

2023-05-05 15:25 UTC, rupertford commented
Ready for first review from @arporter or @sergisiso

2023-05-09 08:08 UTC, arporter requested changes
Nearly perfect. I think the error message could be improved slightly but that's all. Presumably we are also getting closer to being able to support expressions in kernel arguments?
Tests and examples are all fine with compilation.
Changes are pylint clean.
This a bug fix/towards PR so no doc changes needed.

2023-05-09 08:08 UTC, arporter commented on src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
>      assert ("Expected Algorithm-layer kernel arguments to be a literal, "
Oh, I see that we explicitly don't support expressions (I'd forgotten that) as arguments so you can disregard my previous comment.

2023-05-09 08:08 UTC, arporter commented on src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
> +           "reference or code block, but '+1.0' in kernel 'my_kernel' is "
s/in/passed to/

2023-05-09 08:08 UTC, arporter commented on src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
> +                f"a literal, reference or code block, {string}.")
Probably better to capitalise these to emphasise that they are Node types (i.e. "Literal, Reference or CodeBlock").

2023-05-09 10:58 UTC, rupertford commented on src/psyclone/domain/common/transformations/alg_invoke_2_psy_call_trans.py
> +                isinstance(arg, UnaryOperation) and
As you point out below, I've continued with the current restrictions that we have on arguments. We are close to being able to support expressions if the Met Office decide they want that. The only problem (that I know about) is determining the datatype and precision of the argument if it is an expression.

2023-05-09 11:07 UTC, rupertford commented on src/psyclone/tests/domain/common/transformations/alg_invoke_2_psy_call_trans_test.py
> +           "reference or code block, but '+1.0' in kernel 'my_kernel' is "
Better, thanks.

2023-05-09 13:24 UTC, rupertford commented
Ready for next review from @arporter

2023-05-10 10:51 UTC, merged