#2245 Splitting LFRicLoopBounds from dynamo0p3.py
stfc/PSyclone pull request #2260
Opened 2023-08-14 12:25 UTC by oakleybrunt

closes #2245

2023-08-14 15:10 UTC, oakleybrunt commented
Added more imported functions to the `__all__` attributes in `__init__.py`

2023-08-15 15:29 UTC, mo-lottieturner commented
#2235

2023-08-22 10:01 UTC, arporter commented on src/psyclone/domain/lfric/lfric_loop_bounds.py
> +from psyclone.domain.lfric import (LFRicCollection)
No need for parentheses here or below.

2023-08-22 10:03 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_loop_bounds_test.py
>  from __future__ import absolute_import
Please rm this line (it was needed back when we supported both Python 2 and Python 3 and we're gradually removing them now).

2023-08-23 10:37 UTC, oakleybrunt commented on src/psyclone/domain/lfric/__init__.py
> +    'LFRicKernCallFactory',
Ah, sorry about the confusion! I was going through this first issue with Iva and we came across the __init__.py file which was missing several package names in this section. She said to add them but I see now that this is confusing and should be separated into its own issue. I'll revert these changes and only add LFRicLoopBounds

2023-08-24 10:57 UTC, arporter commented
Hi @oakleybrunt, is this ready for review again now?

2023-08-24 12:05 UTC, oakleybrunt commented
@arporter Apologies. Yes, it is ready for review. I've added the label and won't forget on the next PR!

2023-08-25 08:21 UTC, arporter requested changes
Almost there now.
Docstrings need a bit more work.
I've triggered the integration tests so will check those next time.

2023-08-25 08:21 UTC, arporter commented on src/psyclone/domain/lfric/lfric_loop_bounds.py
> +''' This module Handles all variables required for specifying loop limits within a
Please reword to say it provides the `LFRicLoopBounds` class that .... for the LFRic PSy layer.

2023-08-25 08:21 UTC, arporter commented on src/psyclone/domain/lfric/lfric_loop_bounds.py
>  class LFRicLoopBounds(LFRicCollection):
Please put back this doc string - all classes must have one.

2023-08-30 07:40 UTC, arporter approved these changes
All requested changes have been made.
Ref. guide builds fine.
Integration tests are fine.
Will proceed to merge.

2023-08-30 08:06 UTC, merged