2263 splitting LFRic scalar args
stfc/PSyclone pull request #2264
Opened 2023-08-15 13:42 UTC by oakleybrunt

2023-09-13 12:43 UTC, TeranIvy requested changes
Nice work! There are some minor comments and clean-ups (see inline).

Tests with compilation work and examples pass. I didn't check documentation in this instance, but grepping for `LFRicScalarArgs` only returns source and test changes so I think we're fine here.

Also, the branch needs updating with master. I'd advise doing that in a separate commit to review corrections.

2023-09-13 13:29 UTC, oakleybrunt commented on src/psyclone/dynamo0p3.py
> +                                   LFRicKernCallFactory, LFRicScalarArgs)
Hmm, that's strange.

`Counter` is used on line 134 and `FORTRAN_INTENT_NAMES` is used on line 76.

My `pylint` shows this:

```
************* Module psyclone.domain.lfric.lfric_scalar_args
domain/lfric/lfric_scalar_args.py:68:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
domain/lfric/lfric_scalar_args.py:182:4: R0914: Too many local variables (16/15) (too-many-locals)
domain/lfric/lfric_scalar_args.py:182:4: R0912: Too many branches (22/12) (too-many-branches)
```

2023-09-21 07:50 UTC, TeranIvy reviewed
All review comments are addressed. Tests with compilation pass except for an unrelated test. It is not the fault of this PR and it is exposed by using GCC 11.2.0 compiler which is stricter in syntax. 
Documentation builds fine. Examples run.
After updating the user guide and changelog I will proceed to merge the branch.

2023-09-21 08:35 UTC, TeranIvy approved these changes
CI passed, proceeding to merge.

2023-09-21 08:35 UTC, merged