#2272 Split LFRicFields into domain/lfric module
stfc/PSyclone pull request #2273
Opened 2023-08-16 12:38 UTC by oakleybrunt

Closes #2272

2023-10-02 09:04 UTC, arporter commented
Hi @oakleybrunt, is this the next one you'd like me to review? If so, please could you bring up to master and fix the conflicts. Thanks :-)

2023-10-30 09:07 UTC, TeranIvy commented
@arporter, @oakleybrunt, I'm happy to review this. @oakleybrunt, could you please bring the branch up to date and resolve conflicts?

2023-11-03 13:05 UTC, oakleybrunt commented
@TeranIvy Can you help me understand why the sphinx-link-check is failing please?

2023-11-03 14:33 UTC, arporter commented
> @TeranIvy Can you help me understand why the sphinx-link-check is failing please?

It's not your fault (or problem) so you can safely ignore it :-)

2023-11-24 13:37 UTC, TeranIvy commented
Nice work, @oakleybrunt, and apologies for the delay in reviewing!

There are some minor style issues to address (see inline comments). Tests with compilaton pass and `lfric` examples run. There are no changes to documentation.

After the review issues are addressed I would suggest updating the branch with the master and running `pycodestyle` over the entire source and tutorials (e.g. `pycodestyle src/psyclone`, `pycodestyle tutorials` from the top-level directory). I unknowingly picked up some errors when I updated a recent PR branch, it's worth checking it!

2023-11-24 13:39 UTC, TeranIvy requested changes
Nice work, @oakleybrunt, and apologies for the delay in reviewing!

There are some minor style issues to address (see inline comments). Tests with compilaton pass and `lfric` examples run. There are no changes to documentation.

After the review issues are addressed I would suggest updating the branch with the master and running `pycodestyle` over the entire source and tutorials (e.g. `pycodestyle src/psyclone`, `pycodestyle tutorials` from the top-level directory). I unknowingly picked up some errors when I updated a recent PR branch, it's worth checking this!

2023-11-24 13:39 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_kern.py
> +                                        DynBasisFunctions, DynStencils,
Would you mind fixing a couple of `pylint` errors below (not caused by you)? 
```
src/psyclone/domain/lfric/lfric_kern.py:450:0: C0325: Unnecessary parens after 'if' keyword (superfluous-parens)
src/psyclone/domain/lfric/lfric_kern.py:715:8: R1725: Consider using Python 3 style super() without arguments (super-with-arguments)
```

2023-11-24 13:39 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/lfric_field_mdata_test.py
> +# Modified: O. Brunt, Met Office
I'd suggest adding this with other MO contributors.

2023-11-24 13:39 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/lfric_field_mdata_test.py
> +from psyclone.domain.lfric import LFRicArgDescriptor, LFRicConstants, LFRicFields
`pycodestyle` reports `domain/lfric/lfric_field_mdata_test.py:51:80: E501 line too long (81 > 79 characters)`

2023-12-18 18:53 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_fields.py
> +# documentation for. (See https://psyclone-ref.readthedocs.io)
Not quite there, but fixed now.

2023-12-18 20:00 UTC, TeranIvy approved these changes
All well now. There is apparent lack of coverage after moving `LFRicFields`, however further check in `dynamo0p3.py` does not show missing lines. Also, there is a link check that times out, however the link exists so I will consider it a fluke.

Tests run and documentation builds. Updated changelog and user guide for merge to master. Proceeding to merge.

2023-12-18 20:00 UTC, merged