#2284 LFRicRunTimeChecks Split from dynamo0p3.py
stfc/PSyclone pull request #2285
Opened 2023-08-17 13:58 UTC by oakleybrunt

Closes #2284

Sub_issue of #2235

2023-08-17 15:04 UTC, oakleybrunt commented
LFRicRunTimeChecks requires LFRicCollection.
LFRicCollection requires LFRicInvoke.
LFRicInvoke requires LFRicRunTimeChecks.

2023-10-02 15:45 UTC, arporter requested changes
Almost perfect! Just a couple of mentions of an issue that has been closed so the comments need updating.
Also, this has conflicts with master so I haven't been able to check the CI  or docs yet.

2023-10-02 15:45 UTC, arporter commented on src/psyclone/domain/lfric/lfric_run_time_checks.py
> +        # When issue #753 is addressed (with issue #79 helping further)
#753 has been closed so I suggest replacing it with #30.

2023-10-02 15:45 UTC, arporter commented on src/psyclone/domain/lfric/lfric_run_time_checks.py
> +        # When issue #753 is addressed (with issue #79 helping further)
Again, replace 753 with 30 please.

2023-10-06 15:46 UTC, arporter reviewed
Requested changes have been made.
Ref. guide builds fine.
CI is all green.
I'll fire off the integration tests.

2023-10-06 19:03 UTC, arporter approved these changes
Integration tests all green.

2023-10-06 19:27 UTC, merged