(Closes #2253) allow for GH_WRITE access to continuous field args to inter-grid kernels
stfc/PSyclone pull request #2287
Opened 2023-08-22 09:55 UTC by arporter

2023-08-22 10:39 UTC, arporter commented
I'll set the integration tests running and then this just needs a bit of tidying.

2023-08-23 07:26 UTC, arporter commented
Integration tests were all green.

2023-08-23 08:11 UTC, arporter commented
On reflection I decided I could do better than simply declare both cell maps (and also, I think LFRic complains about unused variables). I've therefore tightened things up and have re-launched the integration tests.

2023-08-23 09:05 UTC, arporter commented
This is now ready for testing by @thomasmelvin and @mo-lottieturner.

2023-09-22 11:24 UTC, arporter commented
This has been tested by the MO and is now ready for review. One for @TeranIvy, @hiker or @rupertford.

2023-09-25 16:12 UTC, TeranIvy requested changes
Nice work! Tests with compilation pass, examples run, and the documentation builds fine. There are some minor comments (see inline).

From what I have gathered looking at the user guide, the behaviour for loop stops for MPI is not really explained (e.g. looping into halos vs looping until edge cells regarding the function space continuity). Now, with GH_WRITE thrown into the mix for continuous function spaces, things can get confusing, as we still need to apply colouring but we have loop limits for discontinuous function spaces. It would be good to clarify what PSyclone generates.

2023-09-25 19:47 UTC, arporter commented
> From what I have gathered looking at the user guide, the behaviour for loop stops for MPI is not really explained (e.g. looping into halos vs looping until edge cells regarding the function space continuity). Now, with GH_WRITE thrown into the mix for continuous function spaces, things can get confusing, as we still need to apply colouring but we have loop limits for discontinuous function spaces. It would be good to clarify what PSyclone generates.

This is covered in the developer guide: https://psyclone-dev.readthedocs.io/en/latest/APIs.html#cell-iterators-continuous

2023-09-25 20:48 UTC, arporter commented on src/psyclone/tests/dynamo0p3_multigrid_test.py
> +def test_cont_field_restrict(tmpdir, dist_mem, monkeypatch, annexed):
Oops. Added missing compilation check.

2023-09-25 20:50 UTC, arporter commented on src/psyclone/tests/dynamo0p3_multigrid_test.py
> +    single restriction operation (read from fine, write to
Oh yes, that's clearer.

2023-09-25 20:54 UTC, arporter commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +    '''Test the loop-colouring transformation for an intergrid kernel that has
Done (albeit new-line before Test as I prefer that). The dev guide documents the need to loop into the halos.

2023-09-25 20:56 UTC, arporter commented on src/psyclone/tests/test_files/dynamo0p3/restrict_w2_kernel_mod.F90
> +! -----------------------------------------------------------------------------
Added.

2023-09-25 20:56 UTC, arporter commented on src/psyclone/tests/test_files/dynamo0p3/restrict_w2_kernel_mod.F90
> +!> Psy layer.
Done.

2023-09-25 21:00 UTC, arporter commented
CI-permitting, this is ready for another look. I've also fired off the integration tests.

2023-09-26 09:59 UTC, TeranIvy reviewed
Thanks for making changes. All looks good now, so I am proceeding to final testing.

2023-09-26 12:46 UTC, TeranIvy approved these changes
CI and tests with compilation are fine. Updated changelog and UG for merge to master.

2023-09-26 12:47 UTC, merged