2294 support char in extraction
stfc/PSyclone pull request #2295
Opened 2023-08-29 23:21 UTC by hiker

First part of #1990 (kernel extraction with external symbols)

2023-08-30 10:29 UTC, arporter requested changes
Thanks for breaking this out Joerg.
All looks fine (modulo some slight tweaks) and I could build the libs locally.
I'm not comfortable with having functionality in the repo. that isn't exercised in some form (although this is also true of the profiling wrappers to a lesser extent). Is it possible to extend one or more examples to exercise this new support for `character` and `long`?
The section 'Jinja support in the base class' in the Dev. Guide needs updating to mention that process.py now supports char too. In fact, so does the 'help' text for the `-types` argument to that script (L61-62).

2023-08-31 07:57 UTC, hiker commented on lib/extract/standalone/read_kernel_data_mod.jinja
>          {% if name == "Logical" %}
Done. I also did this in the NetCDF equivalent code.

2023-08-31 07:57 UTC, hiker commented on lib/extract/standalone/read_kernel_data_mod.f90
> +        ! Initialise it with 0, so that an array comparison will work
Agreed.

2023-08-31 08:00 UTC, hiker commented
> I'm not comfortable with having functionality in the repo. that isn't exercised in some form (although this is also true of the profiling wrappers to a lesser extent). Is it possible to extend one or more examples to exercise this new support for `character` and `long`? 

Hmm - not easily. Long would be used if the we would pre-process constants_mod.F90 to switch to 64 bit ints, but that's a change I am not keen to make. And I believe no kernel supports character arguments.

I suggest we keep this for #1990 - then I just need to declare a character and long etc in an external module, and that would then be tested.


> The section 'Jinja support in the base class' in the Dev. Guide needs updating to mention that process.py now supports char too. In fact, so does the 'help' text for the `-types` argument to that script (L61-62).

All done.

2023-08-31 10:11 UTC, arporter reviewed
All looks nice now - thanks for improving all the comments.
Just waiting on the integration tests now.

2023-08-31 10:56 UTC, arporter approved these changes
Integration tests are green.
Dev. guide builds fine.
Will proceed to merge.

2023-09-01 08:16 UTC, merged