#2305 Renamed DynHaloExchange to LFRicHaloExchange
stfc/PSyclone pull request #2306
Opened 2023-09-12 12:24 UTC by oakleybrunt

2023-09-22 11:18 UTC, TeranIvy requested changes
Nice work!

I would suggest going all the way and renaming all DynHaloExchange* classes in this PR. Splitting of classes can wait for another PR, as it would muddle waters.

The remarks I have are minor and are mainly about code style and authorship. Speaking of authorship, modifying developer guide includes adding the developer's name to the list of developers' guide authors. Please see inline comment on how to do that.

The branch will also need to be updated with the master before coming back for the second review.

2023-09-22 11:18 UTC, TeranIvy commented on src/psyclone/tests/dynamo0p3_test.py
> +    value is stored in an instance of the LFRicHaloExchange class. This test
Please add yourself under "Modified".

2023-09-22 11:18 UTC, TeranIvy commented on src/psyclone/tests/psyGen_test.py
> +    # to test is overridden in LFRicHaloExchange.
Please add yourself under "Modified".

2023-09-22 11:18 UTC, TeranIvy commented on src/psyclone/tests/psyGen_test.py
>      schedule = invoke.schedule
Not the fault of this PR, but `pylint` reports
```
psyGen_test.py:67:0: W0611: Unused CWriter imported from psyclone.psyir.backend.c (unused-import)
psyGen_test.py:68:0: W0611: Unused FortranWriter imported from psyclone.psyir.backend.fortran (unused-import)
```
Would you mind improving this?

2023-09-22 11:18 UTC, TeranIvy commented on tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/solutions/overlap_generic.py
> +        for hex_node in schedule.walk(LFRicHaloExchange):
Please add yourself under "Modified", i.e.
```
# Author: R. W. Ford, STFC Daresbury Lab
# Modified: O. Brunt, Met Office
```

Please also update the modification year to 2023.

2023-09-22 15:48 UTC, oakleybrunt commented on src/psyclone/dynamo0p3.py
> +class DynHaloExchangeStart(LFRicHaloExchange):
Renamed all DynHaloExchange* to their LFRicHaloExchange* version

2023-09-22 16:08 UTC, oakleybrunt commented on src/psyclone/tests/dynamo0p3_multigrid_test.py
> +from psyclone.dynamo0p3 import LFRicHaloExchange, DynKernMetadata, HaloReadAccess
You accidentally quoted the wrong `pycodestyle` message. Putting the correct one here for reference but thank you for pointing this out. 

`src/psyclone/tests/dynamo0p3_multigrid_test.py:53:80: E501 line too long (81 > 79 characters)`

2023-09-26 10:10 UTC, TeranIvy commented on src/psyclone/dynamo0p3.py
> +class DynHaloExchangeStart(LFRicHaloExchange):
Thanks :)

2023-09-26 15:38 UTC, TeranIvy requested changes
Almost there :) There are a few minor things to address, as well as a request to rename and move one of the tests. The branch also needs an update with the latest master.

2023-09-26 15:38 UTC, TeranIvy commented on doc/developer_guide/conf.py
> +     u'Oakley Brunt, Rupert Ford, Joerg Henrichs, Iva Kavcic, \\\\'
Thanks for adding your name :) There are a few more documentation options where it needs to be updated: `man_pages`, `texinfo_documents`, `epub_author` and `epub_publisher` (pretty much where you see Lottie's and my name.

2023-09-26 15:38 UTC, TeranIvy commented on examples/lfric/scripts/async_halo_exchanges.py
> +# Modified by O. Brunt, Met Office
I would suggest `# Modified: O. Brunt, Met Office` for consistency with the "Authors" line above.

2023-09-26 15:38 UTC, TeranIvy commented on src/psyclone/tests/psyGen_test.py
> +# Modified I. Kavcic, L. Turner and O. Brunt, Met Office
I would suggest adding `:` after `# Modified` for consistency with the "Authors" line above.

2023-09-26 15:38 UTC, TeranIvy commented on tutorial/practicals/LFRic/distributed_memory/3_overlapping_comms/solutions/overlap_generic.py
> +# Modified by O. Brunt, Met Office
I would suggest `# Modified: O. Brunt, Met Office` for consistency with the "Authors" line above.

2023-09-28 11:55 UTC, TeranIvy approved these changes
All well now. Updated changelog and user guide. CI passes. Tests with compilation pass. Proceeding to merge.

2023-09-28 11:56 UTC, merged