1786 Adding real-to-real conversion builtin
stfc/PSyclone pull request #2420
Opened 2023-11-27 13:10 UTC by oakleybrunt

Closes part of #1786

2024-01-11 18:06 UTC, TeranIvy requested changes
Nice work! I have some requests on testing and documentation, and there are some style issues to fix (see inline).

Tests with compilation pass, the examples build and the user guide builds and displays nicely. The changes are covered. The branch also needs to be updated with the latest master.

2024-01-12 11:09 UTC, oakleybrunt commented on doc/user_guide/dynamo0p3.rst
> +   field data-type conversion Built-ins,
I don't think that any of the conversion builtins break these rules (5.4, 6.5) anymore. All start with the type that they operate on now: `int_to_real_X` operates on integer-valued fields - was called `real_X` (not prefixed with matching datatype)

2024-01-15 17:18 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py
> +# -----------------------------------------------------------------------------
`pycodestyle` reports `src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py:119:1: W293 blank line contains whitespace`.

2024-01-15 17:26 UTC, TeranIvy commented on src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py
> +    print(code)
The `print` statement is still there 😃

2024-01-15 18:57 UTC, TeranIvy requested changes
Almost there. There are some minor style and documentation changes to do. 

Please also update the branch with the latest master if it changes before the next review round.

2024-01-18 14:22 UTC, oakleybrunt commented on src/psyclone/tests/domain/lfric/builtins/real_to_real_x_test.py
> +    print(code)
Whoops! Can't believe I made the same mistake twice!

2024-01-18 14:30 UTC, oakleybrunt commented on doc/user_guide/dynamo0p3.rst
> +Built-ins which take a ``real`` field element for conversion to
After moving this block and generating the pdf, it stll feels a little lost, as though it is part of the real_to_real_X builtin section. Would it be clearer if this block was made into a note?

2024-01-19 14:26 UTC, TeranIvy commented on doc/user_guide/dynamo0p3.rst
> +Built-ins which take a ``real`` field element for conversion to
I think you're right for this one. I rephrased it and moved just below the conversion subtitle. How does this sound?
```
Conversion of ``real`` field elements
#####################################

Built-ins which take a ``real`` field for conversion to a field of
a different datatype or precision are denoted by the datatype that the
input ``real`` field will be converted to. A Built-in that converts a
``real`` to an ``integer`` field is denoted by the phrase **to_int**.
Likewise, a Built-in that converts a ``real`` to a ``real`` field is
denoted by the phrase **to_real**.
```

2024-01-19 16:01 UTC, TeranIvy commented on doc/user_guide/dynamo0p3.rst
> +Built-ins which take a ``real`` field element for conversion to
Rephrased this and pushed. I wanted to merge, but there is question of authorship in `doc/user_guide/conf.py` that needs to be discussed with PSyclons so I'll park this until the Monday telco.

2024-01-22 09:07 UTC, TeranIvy reviewed
All well now. Updated changelog and user guide for merge to master. If CI and Integration tests pass, this can go on.

2024-01-22 10:36 UTC, merged