#2410 splitting and renaming DynStencils to LFRicStencils
stfc/PSyclone pull request #2423
Opened 2023-11-28 14:18 UTC by mo-lottieturner

closes #2410

2024-01-15 12:00 UTC, mo-lottieturner commented
have tried moving each file's LFRicStencils import to the top level individually, but unfortunately none of them worked

2024-01-18 11:42 UTC, TeranIvy commented
Taking this for review.

2024-01-19 13:33 UTC, TeranIvy requested changes
Thanks for the refactoring! I have some minor style remarks and a request to update the bransh with the master (see inline comments). I grepped the code and documentation for the old class name and all is fine. Also, the tests with compilation pass.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +                            f"direction")
I would suggest adding a full stop in this error message. The related test will need to be adjusted, too.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        # list of stencil args with an extent variable passed in. The same
Upper case "List", please.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +    :param node: the Invoke or Kernel stub for which to provide stencil info.
Please remove `\` in descriptions here and other lines in the file where applicable.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +                                 the meta-data for the kernel argument.
"metadata" here and throughout the file, I think. Please also remove `\` from descriptions and add a blank line above the triple quotes as said above.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :rtype: str
Please add a blank line above the triple quotes.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :rtype: str
Please add a blank line above the triple quotes.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param symtab: symbol table that will contain (or already contains) \
Please remove the `\` character and align "the symbol" in the line below with "symbol table".

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param symtab: symbol table that will contain (or already contains) \
Please remove the `\` character and align "the symbol" in the line below with "symbol table".

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param symtab: symbol table that will contain (or already contains) \
Please remove the `\` character and align "the symbol" in the line below with "symbol table".

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +                  this kernel call for cross2d stencils.
I would suggest upper case "CROSS2D". Please also insert a blank line below the `rtype` description.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param parent: the node in the f2pygen AST to which to add the \
Please remove the `\` character from decsriptions..

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param symtab: symbol table that will contain (or already contains) \
Please remove the `\` character and align "the symbol" in the line below with "symbol table".

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :rtype: str
Please insert a blank line below this one.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :returns: list of all the unique extent argument names in this \
Please remove the `\` character from descriptions.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :raises InternalError: if neither self._kernel or self._invoke are set.
I would suggest single quotations (') around `'self._kernel'` and `'self._invoke'`.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +            raise InternalError("_unique_extent_vars: have neither Invoke "
I would suggest specifying the name of the parent class in this error message to make it easier. That is "LFRicStencils._unique_extent_vars: have ...". The relevant test will need to be adjusted.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        Declare all unique extent arguments as integers with intent in and
I would suggest single quotations around `'in'` here to mark it is code.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        in and add the declaration as a child of the parent argument passed
I would suggest single quotations around `'in'` here to mark it is code (intent).

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param parent: the node in the f2pygen AST to which to add the \
Please remove the `\` character from the description (and others in the file).

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        '''
Please insert a blank line above '''.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        Declare all unique direction arguments as integers with intent in
I would suggest single quotations around `'in'` here to mark it is code.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        '''
Please insert a blank line above ‘’’.

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        Declare all stencil-related quanitites for a Kernel stub.
I would suggest "Declares".

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        '''
Please insert a blank line above ‘’’ (please also do that through the module where missing).

2024-01-19 13:33 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +# documentation for. (See https://psyclone-ref.readthedocs.io)
I would suggest "documentation for (see https://psyclone-ref.readthedocs.io)."

2024-01-22 16:22 UTC, mo-lottieturner commented on src/psyclone/domain/lfric/kern_call_acc_arg_list.py
> +        from psyclone.domain.lfric.lfric_stencils import LFRicStencils
these are both due to the Dyn to LFRic change in the line above - fixed [ed1ea8b](https://github.com/stfc/PSyclone/pull/2423/commits/ed1ea8bf5fb9f5d179e129cb62283631656f1e7e)

2024-01-22 16:24 UTC, mo-lottieturner commented on src/psyclone/domain/lfric/lfric_stencils.py
> +class LFRicStencils(LFRicCollection):
[ed1ea8b](https://github.com/stfc/PSyclone/pull/2423/commits/ed1ea8bf5fb9f5d179e129cb62283631656f1e7e)

2024-01-22 16:24 UTC, mo-lottieturner commented on src/psyclone/tests/domain/lfric/lfric_stencil_test.py
> +    ''' Check that LFRicStencils.initialise and LFRicStencils._declare_maps_invoke
[ed1ea8b](https://github.com/stfc/PSyclone/pull/2423/commits/ed1ea8bf5fb9f5d179e129cb62283631656f1e7e)

2024-01-22 16:25 UTC, mo-lottieturner commented on src/psyclone/domain/lfric/lfric_kern.py
> +                                        DynBasisFunctions, DynReferenceElement)
is the fault of this PR - DynStencils moved up to be LFRicStencils - fixed [ed1ea8b](https://github.com/stfc/PSyclone/pull/2423/commits/ed1ea8bf5fb9f5d179e129cb62283631656f1e7e)

2024-01-22 16:30 UTC, mo-lottieturner commented on src/psyclone/domain/lfric/lfric_stencils.py
> +''' This module implements the PSyclone Dynamo 0.3 API by 1)
Yes that looks copied - I knew I had overlooked something!

2024-02-06 17:20 UTC, TeranIvy requested changes
Almost there, just a few small changes and `pycodestyle` clean-up are required. Please also update the branch with the latest master.
Tests with compilation pass fine.

2024-02-06 17:20 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +class LFRicStencils(LFRicCollection):
`pycodestyle` reports several errors:
```
src/psyclone/domain/lfric/lfric_stencils.py:321:80: E501 line too long (83 > 79 characters)
src/psyclone/domain/lfric/lfric_stencils.py:331:80: E501 line too long (82 > 79 characters)
src/psyclone/domain/lfric/lfric_stencils.py:377:1: W293 blank line contains whitespace
src/psyclone/domain/lfric/lfric_stencils.py:412:1: W293 blank line contains whitespace
src/psyclone/domain/lfric/lfric_stencils.py:451:1: W293 blank line contains whitespace
```

2024-02-06 17:20 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +''' This module implements the stencil information and code generation
I would suggest specifying this is for LFRic API. E.g. "... associated with a PSy-layer routine or Kernel stub in LFRic API."

2024-02-06 17:20 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param parent: the node in the f2pygen AST to which to add \
Please remove `\` from the description.

2024-02-06 17:20 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        '''
Please add a blank space above these triple quotations.

2024-02-06 17:20 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param parent: the node in the f2pygen AST representing the kernel \
Please remove `\`.

2024-02-06 17:20 UTC, TeranIvy commented on src/psyclone/domain/lfric/lfric_stencils.py
> +# documentation for (See https://psyclone-ref.readthedocs.io).
Lower case "see", please.

2024-02-06 20:48 UTC, TeranIvy approved these changes
All well now. Retested with compilation and built examples.

Updated changelog and user guide for merge to master. Integration and compilation tests on PSyclone mirror all pass. Markdown links check started failing again, however this is not the fault of this PR.

Proceeding to merge.

2024-02-06 20:58 UTC, TeranIvy commented
Had to push an empty commit to hopefully trigger Coverage report this time.

2024-02-06 21:38 UTC, merged