(closes #2254) Make PSyAD harness use logging in LFRic version
stfc/PSyclone pull request #2426
Opened 2023-12-04 15:31 UTC by rupertford

To fit in with the LFRic testing environment, the LFRic PSyAD harness should use LFRic logging to indicate success or failure of the LFRic adjoint code. @DrTVockerodtMO has kindly provided the required code in the associated issue #2254.

2023-12-13 12:05 UTC, arporter requested changes
Thanks for improving this. The change is basically OK but I baulked at the duplication. Therefore I'm requesting that you just specialise the part of the code that does the error reporting.
I'll check for pylint etc. next time.

2023-12-17 21:06 UTC, rupertford commented on src/psyclone/psyad/domain/lfric/lfric_adjoint_harness.py
> +    :rtype: list of :py:class:`psyclone.psyir.nodes.Node`
Modified to `List[...]` in the appropriate places

2023-12-17 21:07 UTC, rupertford commented on src/psyclone/psyad/domain/lfric/lfric_adjoint_harness.py
> +
Removed duplication as requested.

2023-12-17 21:08 UTC, rupertford commented
Ready for next review from @arporter

2023-12-18 09:33 UTC, arporter reviewed
Requested changes have been made.
Changes are pylint/pycodestyle clean.
I've taken the liberty of fixing an error found when generating the Ref. Guide (not related to this PR).
Just waiting on the integration tests now.

2023-12-18 11:10 UTC, arporter approved these changes
NEMO integration tests failed but that's not the fault of this PR.
Will proceed to merge.

2023-12-18 11:26 UTC, merged