2451 split rename dyn invoke schedule
stfc/PSyclone pull request #2452
Opened 2024-01-03 14:58 UTC by oakleybrunt

2024-05-10 15:29 UTC, oakleybrunt commented
@TeranIvy - tests now passing, ready for review :)

2024-05-13 15:15 UTC, arporter requested changes
Good job. I only managed to find one outstanding mention of DynInvokeSchedule:

    ./src/psyclone/tests/psyir/tools/call_tree_utils_test.py:    # This will return three schedule - the DynInvokeSchedule, and two

Ref. guide still builds fine, as does the UG. I'll fire off the integration tests but as these don't currently work for LFRic, I'll need independent verification from you that you tested this branch with LFRic :-)

2024-05-13 15:27 UTC, oakleybrunt commented on src/psyclone/domain/lfric/lfric_invoke_schedule.py
> +# Copyright (c) 2017-2023, Science and Technology Facilities Council.
Wow hahaha

2024-05-14 12:28 UTC, arporter reviewed
All requested changes have been made (thanks) and integration tests were fine.
@oakleybrunt please could you confirm that you've tested LFRic with this branch?
Note: reference guide still builds fine.

2024-05-15 10:07 UTC, oakleybrunt commented
> All requested changes have been made (thanks) and integration tests were fine. @oakleybrunt please could you confirm that you've tested LFRic with this branch? Note: reference guide still builds fine.

@arporter I have not! And embarrasingly I can't remember how to test specific branches of PSyclone with LFRic... can you help?

2024-05-15 10:56 UTC, arporter commented
@oakleybrunt, re. building with LFRic, Sergi is hopeful that he will have the integration tests fixed today so we can just wait for them to come back :-)

2024-05-16 10:22 UTC, arporter commented
I've just triggered the integration tests. If they are OK then I'll proceed to merge.

2024-05-16 10:27 UTC, oakleybrunt commented
> I've just triggered the integration tests. If they are OK then I'll proceed to merge.

Thanks Andy, sorry for not getting to the LFRic testing myself.

2024-05-16 11:58 UTC, arporter commented
Everything was green. will proceed to merge.

2024-05-16 12:01 UTC, arporter approved these changes
All good now.
Just waiting on final CI.

2024-05-16 12:38 UTC, merged