2461 DynamoPSy split & rename
stfc/PSyclone pull request #2461
Opened 2024-01-08 14:04 UTC by oakleybrunt

Closes #2460

2024-05-21 09:47 UTC, mo-lottieturner requested changes
Mostly backslashes needing removing

2024-05-21 09:47 UTC, mo-lottieturner commented on examples/lfric/eg2/loop_fuse_trans.py
>      :param psy: the PSy object that PSyclone has constructed for the \
remove backslash

2024-05-21 09:47 UTC, mo-lottieturner commented on examples/lfric/eg2/module_inline_trans.py
>      :param psy: the PSy object that PSyclone has constructed for the \
remove backslash

2024-05-21 09:47 UTC, mo-lottieturner commented on examples/lfric/eg2/print_psyir_trans.py
>      :param psy: the PSy object that PSyclone has constructed for the \
remove backslash

2024-05-21 09:47 UTC, mo-lottieturner commented on src/psyclone/tests/domain/lfric/lfric_psy_test.py
>      :param str name: the name to use for this dummy invoke. Defaults \
remove backslash

2024-11-04 13:16 UTC, arporter commented
This branch is getting horribly out of date (and thus hard to merge). Are you still planning to complete this @oakleybrunt and @mo-lottieturner?

2024-11-26 13:35 UTC, mo-lottieturner approved these changes

2024-11-26 13:47 UTC, mo-lottieturner commented
Approved, but I'm not authorised to merge this onto trunk

2024-11-26 15:20 UTC, mo-lottieturner commented
> Thanks both. I've just made @mo-lottieturner a 'maintainer' - does that then permit you to merge this PR? If not, I'll upgrade you to 'admin' :-)

Yep, looks like it! How do I know that the integration testing has passed? Looks like Oakley has updated the changelog

2024-11-26 17:04 UTC, arporter commented
You go here: https://github.com/stfc/PSyclone-mirror/actions I've just given you read access (you might have an email invitation?).

2024-11-26 17:04 UTC, arporter commented
You'll see that everything apart from NEMOv5 was OK and NEMOv5 is expected to fail currently so that's OK.

2024-11-26 17:05 UTC, arporter commented
(You also need to build and update the User Guide in the root directory - see https://github.com/stfc/PSyclone/wiki/CodeReview#merging-a-branch-to-master)

2024-11-27 17:26 UTC, merged

2024-11-27 17:27 UTC, mo-lottieturner commented
Merged and branch deleted