(closes #2419) Rename UnknownType to UnsupportedType and DeferredType to UnresolvedType
stfc/PSyclone pull request #2486
Opened 2024-01-22 10:42 UTC by sergisiso

2024-01-22 11:52 UTC, sergisiso commented
This is ready to review, one for @arporter or @hiker

2024-01-23 16:24 UTC, arporter commented
I managed to find:
 
   $ find ./doc ./src -name \*.py -exec grep -iH unknownfortrantype {} \;
    ./src/psyclone/tests/psyir/frontend/fparser2_test.py:def test_process_declarations_unknownfortrantype():
    ./src/psyclone/psyir/backend/fortran.py:    (This is required because we capture an UnknownFortranType declaration as

2024-01-24 09:04 UTC, arporter requested changes
Good work Sergi. Just a couple of minor things and one pycodestyle issue:

    psyclone/tests/psyir/nodes/array_reference_test.py:550:62: E128 continuation line under-indented for visual indent

I've fired off the integration tests now.

2024-01-24 09:12 UTC, sergisiso commented on src/psyclone/tests/psyir/nodes/operation_test.py
> +    # TODO #2419 - UnresolvedType should probably be UnsupportedType really.
yep, done

2024-01-24 09:13 UTC, sergisiso commented on src/psyclone/tests/psyir/backend/opencl_test.py
> +    # Add a symbol with a Unresol and check that this raises the
Ups. Done.

2024-01-24 09:17 UTC, sergisiso commented on src/psyclone/tests/psyir/backend/fortran_unknown_declns_test.py
> +    which is not imported or an interface UnsupportedFortanType is found by the
Rephrased to "or a Fortran interface (currently an UnsupportedFortanType)" which is what I think we mean

2024-01-24 09:18 UTC, sergisiso commented on src/psyclone/psyir/symbols/typed_symbol.py
> +        ''' If the symbol has am Unresolved datatype, find where it is defined
Fixed

2024-01-24 09:30 UTC, sergisiso commented
> I managed to find:

$ find ./doc ./src -name *.py -exec grep -iH unknownfortrantype {} ;
./src/psyclone/tests/psyir/frontend/fparser2_test.py:def test_process_declarations_unknownfortrantype():
./src/psyclone/psyir/backend/fortran.py: (This is required because we capture an UnknownFortranType declaration as

Done!, which also made me think of doing "find . -name *unknown*" and found one filename to update.

> I've fired off the integration tests now.

I fired it two days ago in the same commit. I just saying it because I don't think the CI repeats the test to the same commit and you will have to go back in the jobs list to find the results, which were successful.

2024-01-24 09:33 UTC, arporter commented
> I fired it two days ago in the same commit. I just saying it because I don't think the CI repeats the test to the same commit and you will have to go back in the jobs list to find the results, which were successful.

Oh, that's clever, I didn't know it did that. It also explains why I can see no trace of the job I submitted half an hour ago!

2024-01-24 09:43 UTC, sergisiso commented on src/psyclone/psyir/frontend/fparser2.py
> +                symbol_type=DataSymbol, datatype=UnresolvedType())
Note that now we have Unresolved Symbols (interfaces) and Unresolved DataTypes (and both have the same meaning - that the declaration has not been found), but in this case we mean the former (although in many cases the later would also be true). As you mention, I think I would like to leave this for another PR.

2024-01-24 09:45 UTC, sergisiso commented on src/psyclone/psyir/symbols/datatypes.py
> +        return "UnresolvedType"
Again, as you suggest I prefer not changing other aspects in this PR as its big enough.

2024-01-24 10:21 UTC, sergisiso commented
@arporter This is ready for the next review.

2024-01-24 13:35 UTC, arporter approved these changes
All good now thanks.
I've also checked for the issue number and not found any mentions of it.
All the different docs build fine.
Will proceed to merge.

2024-01-24 14:34 UTC, merged