(Closes #2492) nemoouterarrayrange bug
stfc/PSyclone pull request #2493
Opened 2024-01-29 20:49 UTC by arporter

Bug fix for the named transformation (required when an array reference itself uses an array reference in an index expression) and also a minor fix to the `utils.py` file in `examples/nemo/scripts` that prevents us attempting to specialise the same Symbol more than once. (Found while processing latest NEMO source.)

2024-01-29 21:43 UTC, arporter commented
Integration tests are running now...

2024-01-30 12:39 UTC, sergisiso requested changes
@arporter This fixes a couple of bugs and the implementation is simple, I am happy with the code changes.

But Codecov shows an indirect line miss. Can we explore what is it? Also the integration tests all pass but it may be worth running it again when nobody is on glados to make sure the indirect changes don't have any performance impact.

2024-01-30 16:09 UTC, arporter commented
The missed line is weird and @LonelyCat124 has just hit the same thing in his PR. I've tried running the test suite for master on my laptop and that line is not hit. Possibly it is hit in an older version of Python (I have 3.12)? Anyway, it doesn't seem to be a result of this particular PR.

2024-01-31 15:04 UTC, sergisiso approved these changes
@arporter Re-running the integration tests shows that all performance match their best numbers. So we can proceed to merge this PR.

2024-01-31 16:22 UTC, merged