2394 support char logical in psydata
stfc/PSyclone pull request #2509
Opened 2024-02-22 01:04 UTC by hiker

2025-01-06 16:53 UTC, arporter requested changes
Nice, small PR :-)
Would it be possible to extend one of the examples to make use of/exercise this new functionality? Otherwise it's completely untested :-(
Also, I have a concern about the 'number of bits' being specified for logical and character variables. I can't remember how you use this information?

2025-01-06 16:53 UTC, arporter commented on lib/read_only/Makefile
>  # The read-only verification library is implemented for int, real and
Please update the comment too.

2025-01-06 16:53 UTC, arporter commented on lib/value_range_check/Makefile
>  # double scalars and 2-dimension arrays
Please update the comment too.

2025-01-06 16:53 UTC, arporter commented on lib/value_range_check/value_range_check_base.jinja
> +                        ("Logical", "logical",              8),
I happened to be reading about this today and, in Fortran, the storage of a logical has to be the same as the storage of a default integer. I don't know what it is for character. I can't remember how this 'number of bits' is used here though?

2025-01-06 16:53 UTC, arporter commented on lib/value_range_check/value_range_check_base.jinja
>          {# IEEE_SUPPORT_DATATYPE does not even compile for int data types #}
Comment needs updating?

2025-01-07 13:37 UTC, hiker commented on lib/read_only/Makefile
>  # The read-only verification library is implemented for int, real and
Done.

2025-01-07 13:38 UTC, hiker commented on lib/value_range_check/Makefile
>  # double scalars and 2-dimension arrays
Done.

2025-01-07 13:41 UTC, hiker commented on lib/value_range_check/value_range_check_base.jinja
> +                        ("Logical", "logical",              8),
OK, that cost me some time. Turns out, the bit size was only used for the read-only-verification, so I decided to remove these unnecessary value from the other files.
But since it was (potentially/likely) also set when calling `process.py`, so I changed read-only to  set the bit size depending on name instead. That made this patch a bit bigger, but these unnecessary values are gone now.

2025-01-09 14:05 UTC, hiker commented
> Nice, small PR :-) Would it be possible to extend one of the examples to make use of/exercise this new functionality? Otherwise it's completely untested :-( 

That was a bit of a headache, since neither gocean nor lfric support character strings. So I've added a new generic read-only verification library, and added an example as nemo/eg6. I couldn't add an examples that will actually throw an error (since PSyclone processes the file and does not support `loc` or `sizeof`, which was the trick I used in gocean). There is documentation how you can manually modify the psy file to trigger an error (but admittedly that's kind of stupid). Suggestions welcome.

> Also, I have a concern about the 'number of bits' being specified for logical and character variables. I can't remember how you use this information?

I have also refactored all of that, so no more bits specified. Unfortunately, all of that that made this PR somewhat bigger :)

2025-01-10 09:54 UTC, arporter commented on doc/user_guide/psy_data.rst
> +library is included in ``examples/gocean/eg6/``.
nemo/eg6 rather than gocean?

2025-01-10 09:54 UTC, arporter commented on examples/nemo/eg6/Makefile
> +# Makefile for the 5th NEMO example. Uses PSyclone (which must
First sentence is wrong (and could just be removed).

2025-01-10 09:54 UTC, arporter commented on examples/nemo/eg6/README.md
> +# PSyclone NEMO Example 6 - Read-only Verification
Please add a brief section to examples/nemo/README.md to mention this new example.

2025-01-10 09:54 UTC, arporter commented on doc/user_guide/tutorials_and_examples.rst
> +Example 6: Read-only Verification
I realise we have duplication between this text and the markdown README files. If you're feeling keen, we could experiment with removing this section and replacing it with an include of the appropriate README. Sphinx's `include` directive supports a 'parser' option which apparently allows this (https://docutils.sourceforge.io/docs/ref/rst/directives.html#include-options). However, now that I write all that, I think perhaps that would be a separate issue.

2025-01-10 09:54 UTC, arporter commented on examples/nemo/eg6/README.md
> +compile again, an error will be produced.
This worked for me. Good stuff. Only wrinkle is that doing `make compile` again ran PSyclone and over-wrote my modified psy.f90 file. I had to cut-n-paste the compile and link lines to build with the modified psy.f90 file. Not a biggie. Either mention it here or perhaps it's just a small tweak to the Makefile?

2025-01-10 09:54 UTC, arporter commented on examples/nemo/eg6/dummy.f90
> +    ! TODO: Unfortunately, PSyclone does not support loc or sizeof,
Please could you clarify here. I tried it for myself and see that it's the generation of the PSyData calls that is broken. If we don't already have an Issue please could you create one and refer to it here. Generating code that doesn't compile isn't a good look for us :-(

2025-01-10 09:54 UTC, arporter commented on examples/nemo/eg6/dummy.f90
> +program dummy
Please add the ususal license and a brief comment summarising the purpose of this file.

2025-01-10 09:54 UTC, arporter commented on lib/read_only/generic/Makefile
> +
Please add a comment saying that this Makefile is for the read-only checking lib for generic Fortran code.

2025-01-10 09:54 UTC, arporter commented on lib/read_only/generic/README.md
> +https://psyclone.readthedocs.io/en/latest/psy_data.html#read-only-verification-library-for-gocean)
This link is for gocean. Is that deliberate?

2025-01-10 09:54 UTC, arporter commented on lib/read_only/generic/README.md
> +https://psyclone.readthedocs.io/en/latest/examples.html#compilation), the
Should be `tutorials_and_examples.html` I think.

2025-01-10 09:54 UTC, arporter commented on lib/value_range_check/value_range_check_base.jinja
> +                        ("Logical", "logical",              8),
Sorry. That was quite a lot of work. I think it's an improvement though.

2025-01-10 09:57 UTC, arporter commented on lib/value_range_check/value_range_check_base.jinja
>          {# IEEE_SUPPORT_DATATYPE does not even compile for int data types #}
:-)

2025-01-10 10:05 UTC, arporter commented on examples/nemo/eg6/dummy.f90
> +program dummy
You could take the opportunity to say this is really just about exercising aspects of the read-only verification library.

2025-01-10 10:07 UTC, arporter requested changes
Thanks very much Joerg. Just a few minor things now.
In testing the compilation of the examples I discovered that the xdsl Makefile was broken (spaces instead of tabs) so I've taken the liberty of fixing that and pushed it on your branch.

2025-01-14 00:02 UTC, hiker commented on examples/nemo/eg6/README.md
> +# PSyclone NEMO Example 6 - Read-only Verification
So many places to modify :)  Done, thanks for spotting that.

2025-01-14 00:03 UTC, hiker commented on examples/nemo/eg6/Makefile
> +# Makefile for the 5th NEMO example. Uses PSyclone (which must
Done, and I slightly reworded the next sentence to read a bit better.

2025-01-14 00:03 UTC, hiker commented on doc/user_guide/psy_data.rst
> +library is included in ``examples/gocean/eg6/``.
Indeed.

2025-01-14 02:45 UTC, hiker commented on doc/user_guide/tutorials_and_examples.rst
> +Example 6: Read-only Verification
I have it nearly all sorted out, then I realised that the rst has a link target from the dev guide, which would now need to be defined in the README.md :cry: ... I kind of ran out of time to see if this is possible, and opened #2847 with the patch I have done so far.

2025-01-14 06:23 UTC, hiker commented on examples/nemo/eg6/README.md
> +compile again, an error will be produced.
Good point. I think I've fixed that now.

2025-01-14 06:42 UTC, hiker commented on examples/nemo/eg6/dummy.f90
> +    ! TODO: Unfortunately, PSyclone does not support loc or sizeof,
Not really a PSyclone problem (at this stage at least :) ). The two functions `loc` and `sizeof` are non-standard extensions, and as such are not detected by fparser (and then end up as being assumed to be arrays).  We have an fparser issue to support additional (standard) intrinsics:
https://github.com/stfc/fparser/issues/434

So I've added these two in with the comment that they are non-standard. I've also updated the comment to better indicate why it doesn't work.

If you prefer, I could handle `loc` and `sizeof` as special case in the transformation, so that they wouldn't get 'extracted' ... but of course that would mean if a user has those names used as variables, it would fail as well :(

2025-01-14 06:50 UTC, hiker commented on examples/nemo/eg6/dummy.f90
> +program dummy
Done

2025-01-14 06:52 UTC, hiker commented on lib/read_only/generic/Makefile
> +
Done.

2025-01-14 07:03 UTC, hiker commented on lib/read_only/generic/README.md
> +https://psyclone.readthedocs.io/en/latest/psy_data.html#read-only-verification-library-for-gocean)
Nope - good catch, thanks!

2025-01-14 07:10 UTC, hiker commented on lib/read_only/generic/README.md
> +https://psyclone.readthedocs.io/en/latest/examples.html#compilation), the
Indeed - that's broken in all three versions of the library  - oops, it's actually broken in all READMEs in the lib directory. All fixed now.

2025-01-14 07:14 UTC, hiker commented
OK, all issues addressed I believe.

2025-01-14 11:37 UTC, hiker commented
Linkspector failures are caused by the new example not yet in git (master). I've started the compilation tests.

2025-01-14 11:38 UTC, hiker commented on doc/user_guide/psy_data.rst
> +library is included in ``examples/gocean/eg6/``.
I meant ... you are right, it was indeed wrong.

2025-01-20 16:34 UTC, arporter commented on doc/user_guide/tutorials_and_examples.rst
> +Example 6: Read-only Verification
Thanks Joerg :-)

2025-01-20 16:37 UTC, arporter commented on examples/nemo/eg6/dummy.f90
> +    ! TODO: Unfortunately, PSyclone does not support loc or sizeof,
No, that's good now, thanks.

2025-01-20 16:40 UTC, arporter approved these changes
All good now thanks Joerg.
I'll proceed to merge.

2025-01-20 17:14 UTC, merged