(Closes #2622) Add convenient methods `SymbolTable.insert_argument` and `.append_argument`.
stfc/PSyclone pull request #2626
Opened 2024-06-20 17:25 UTC by JulienRemy

Arguments currently have to be inserted in `SymbolTable().argument_list` using a workaround: 
- 1. getting it, which checks the arguments and non-arguments symbols in the table,
- 2.  adding the symbol to the table and the argument list. Trying to do it in the reversed order causes a validation error on either the table or the argument list.

This introduces `SymbolTable().insert_argument(index, argument)` and `.append_argument(argument)` to hopefully cover most use cases.

2024-06-20 18:49 UTC, JulienRemy commented
@arporter @sergisiso What do you think about these?

2024-06-21 13:18 UTC, arporter requested changes
Thanks very much for this Julien. Just small things to tidy up. 
Updated test file fully covers modified source file.
No need to update user guide or dev guide because we don't mention the management of Routine argument lists! While that's not good, I don't think we have to address that here.
Ref. guide builds without extra warnings.
Although this PR really shouldn't affect anything, I'll launch the integration tests just to be on the safe side.

2024-06-21 15:13 UTC, JulienRemy commented on src/psyclone/tests/psyir/symbols/symbol_table_test.py
> +        assert ("var1" in str(err.value)
Do you mean line 1643?
Unindenting to the previous tab i.e.
```python
    arg1 = symbols.DataSymbol("var2", symbols.REAL_TYPE,
                            interface=symbols.ArgumentInterface())
    with pytest.raises(InternalError) as err:
        sym_table.insert_argument(0, arg1)
        assert ("var1" in str(err.value)
```
causes Flake8 to complain: `src/psyclone/tests/psyir/symbols/symbol_table_test.py:1643:29: E128 continuation line under-indented for visual indent`

2024-06-21 15:14 UTC, JulienRemy commented on src/psyclone/tests/psyir/symbols/symbol_table_test.py
> +        assert ("var1" in str(err.value)
Same with even one space less.

2024-06-21 15:14 UTC, JulienRemy commented on src/psyclone/tests/psyir/symbols/symbol_table_test.py
> +        assert ("var6" in str(err.value)
Same as above.

2024-06-24 09:02 UTC, JulienRemy commented
`assert`s are now unindented and I also changed the `_validate_...` error strings to use `type(object).__name__`.

2024-06-24 14:30 UTC, merged