#2617 Support generic functions.
stfc/PSyclone pull request #2651
Opened 2024-07-08 06:27 UTC by hiker

Fixes #2617.

2024-07-23 07:15 UTC, arporter requested changes
Thanks Joerg. Almost perfect. Just one comment needs a bit of clarification.
I'll fire off the integration tests in the meantime.

2024-07-23 07:15 UTC, arporter commented on src/psyclone/tests/psyir/tools/call_tree_utils_test.py
> +    visited (until PSyclone properly resolves generic interfaces)
As discussed in Teams, please could you clarify slightly. Even when we can do better than we do now, there will still be cases where we can't resolve the target due to a lack of type information.

2024-07-23 23:34 UTC, hiker commented
I hope that's better. The CI passed, and given that I only modified a comment, I didn't bother running it again.

2024-07-29 07:23 UTC, arporter approved these changes
New comment is good thanks.
Just waiting on CI now and then I'll merge it.

2024-07-29 08:08 UTC, merged