(Closes #2716) Add support for module-inlining calls to polymorphic kernels/routines
stfc/PSyclone pull request #2732
Opened 2024-10-03 09:12 UTC by arporter

2024-10-03 14:06 UTC, arporter commented
As well as addressing the coverage, I need to extend the LFRic integration tests to use this new functionality.

2024-10-07 16:05 UTC, arporter commented
Added the KernelModuleInlineTrans back into the LFRic transformation script and get a crash when trying to add the interface symbol into the symbol table.

2024-10-08 14:19 UTC, arporter commented
Build and run with updated transformation script works:
![image](https://github.com/user-attachments/assets/80599023-fafc-42b9-82dd-bf59708a46c1)

2024-10-08 14:52 UTC, sergisiso commented
If you merge with master, I added multiple prints in the output, so you can grep and count the number of each cases that we could not get the kernel_schedule before due to polymorphic kernels, which was 331

2024-10-08 20:43 UTC, arporter commented
The OMP offload LFRic integration test failed with an ICE:
```
17:47:36 Pre-process and compile inventory/id_r32_field_array_pair_mod.F90
inventory/id_r32_field_array_pair_mod.F90:
NVFORTRAN-S-0000-Internal compiler error. flowgraph: node is zero       3  (lfric_xios_setup_mod_psy.f90: 85)
NVFORTRAN-F-0000-Internal compiler error. Invalid key for hash       0  (lfric_xios_setup_mod_psy.f90: 85)
NVFORTRAN/x86-64 Linux 24.5-1: compilation aborted
```
It's seems odd that there's a `_psy.f90` for xios setup??

2024-10-08 21:22 UTC, arporter commented
Do the build manually for OpenACC and things are looking better:
![image](https://github.com/user-attachments/assets/5154a115-b8e2-46d5-baaa-809d4f9279ab)
(note: I've marked MATMUL as being available on the GPU now.)

2024-10-08 21:32 UTC, arporter commented
I need to figure out why we get an inlined routine without an offload directive added to it. The build log says:
```
PSy name = 'lfric_xios_setup_mod_psy'
Transforming invoke 'invoke_0_nodal_xyz_coordinates_kernel_type' ...
Failed to annotate 'nodal_xyz_coordinates_code' with GPU-enabled directive due to:
Transformation Error: Kernel 'nodal_xyz_coordinates_code' accesses the symbol 'chi2xyz: RoutineSymbol<NoType, pure=unknown, elemental=unknown>' which is imported. If this symbol represents data then it must first be converted to a Kernel argument using the KernelImportsToArguments transformation.
Failed to annotate 'nodal_xyz_coordinates_code' with GPU-enabled directive due to:
Transformation Error: Kernel 'nodal_xyz_coordinates_code' accesses the symbol 'chi2xyz: RoutineSymbol<NoType, pure=unknown, elemental=unknown>' which is imported. If this symbol represents data then it must first be converted to a Kernel argument using the KernelImportsToArguments transformation.
Transforming invoke 'invoke_1_nodal_coordinates_kernel_type' ...
Failed to module-inline kernel 'nodal_coordinates_code' due to:
Transformation Error: Cannot inline subroutine 'nodal_coordinates_code' because another, different, subroutine with the same name already exists and versioning of module-inlined subroutines is not implemented yet.
Successfully offloaded loop with ['nodal_coordinates_code']
Successfully offloaded loop with ['nodal_coordinates_code']
Transforming invoke 'invoke_2_nodal_coordinates_kernel_type' ...
Failed to module-inline kernel 'nodal_coordinates_code' due to:
Transformation Error: Cannot inline subroutine 'nodal_coordinates_code' because another, different, subroutine with the same name already exists and versioning of module-inlined subroutines is not implemented yet.
Successfully offloaded loop with ['nodal_coordinates_code']
Successfully offloaded loop with ['nodal_coordinates_code']
```

2024-10-09 08:04 UTC, arporter commented
Part of the problem was that the optimisation script wasn't checking that it hadn't already transformed a given kernel for a given invoke. Fixing that removes the 'failed to inline' messages but we still end up with an inlined kernel that doesn't have a directive added to it.

2024-10-09 08:42 UTC, arporter commented
The problem was that, having successfully module-inlined the kernel routine, we proceed to apply the annotation transformation to the original Kern and that does not update the Routine that has been inlined. It probably should? For now, I can search for the newly inlined routine and apply the transformation to that and we get the expected code.

2024-10-09 08:43 UTC, arporter commented
Now get a compilation failure:
```
NVFORTRAN-S-0155-Ambiguous interfaces for generic procedure matrix_vector_code (
algorithm/norm_alg_mod_psy.f90: 338)
```

2024-10-09 09:11 UTC, arporter commented
`Kern.get_kernel_schedule()` (which is to be replaced/removed if/when we migrate Kern to subclass Call) currently caches the PSyIR of the kernel. `KernelModuleInlineTrans` creates a copy of this PSyIR and then inserts it into the PSy-layer. Therefore, `get_kernel_schedule()` should now return that copy of the PSyIR. In fact, that would happen automatically if I undid my changes to `KernelModuleInlineTrans` so that it *doesn't* copy the PSyIR. I can't remember why I made that change.

2024-10-10 13:10 UTC, arporter commented
Thinking about this a bit more, I belatedly realise that if a given PSy layer routine calls the same kernel more than once then either all of them must be module inlined or none of them (unless we attempt to rename the inlined version and that gets complicated). I think the reason that LFRic is still not working is that we fail to inline a second instance of the same kernel (because the first instance has been transformed) but then we do proceed to transform it. Therefore, `rename_and_write()` is called in order to generate a new version of that kernel on disk. I need a reproducer for this.

2024-10-11 09:58 UTC, arporter commented
I've realised that `Kern.module_inline` sets this flag for *all* Kernels with that name in the current `InvokeSchedule`. This seems sensible but is causing me problems because we end up with a Kernel marked as 'module inlined' but which actually isn't because the transformation on it failed and so it was written to file and renamed instead.

2024-10-11 11:04 UTC, arporter commented
The trouble with the LFRic example is that we have two, *separate* `invoke` calls, each with the same Kernel. The first Kernel gets module inlined but has to be modified to have some imports made local to it. That then means we refuse to inline the second Kernel because it is no longer identical. The question is, why does the search for the source of the second kernel not return the module-inlined source of the first one?

2024-11-18 14:51 UTC, arporter commented
With this branch and latest gpu script in lfric/examples:
![image](https://github.com/user-attachments/assets/9353d420-720b-4270-8116-7f72f033e4be)

2024-11-18 15:33 UTC, arporter commented
Adding RANDOM_NUMBER intrinsic to available_on_device - build still worked OK on GPU but profile didn't look much different. Need to update the Sankey diagram and see whether I've missed anything.

2024-11-19 10:29 UTC, arporter commented
One of the compilation tests fail with the nvidia compiler. This same test passes with gfortran:

![image](https://github.com/user-attachments/assets/e7527ae0-0a3a-4493-81af-e12ccec9bb15)

2024-11-19 11:36 UTC, arporter commented
```
$ nvfortran -I../dynamo_wrapper0/utilities -I../dynamo_wrapper0/field -I../dynamo_wrapper0/operator -I../dynamo_wrapper0/function_space -I../dynamo_wrapper0/mesh -I../dynamo_wrapper0/scalar -I../dynamo_wrapper0/configuration -c psy.f90
NVFORTRAN-S-0155-Ambiguous interfaces for generic procedure mixed_code (psy.f90: 289)
```

2024-11-19 13:34 UTC, arporter commented
The problem is that the invoke subroutine is still importing the kernel interface, even though it has been module inlined:
```fortran
    SUBROUTINE invoke_1(scalar_r_phys, a, istp)
      USE mixed_kernel_mod, ONLY: mixed_code
```

2024-11-19 16:47 UTC, arporter commented
I'm beginning to think that this is a compiler bug. If I alter the second invoke so that it calls a specific implementation of the kernel (e.g. mixed_code_64) then it compiles fine.

2024-11-22 10:58 UTC, arporter commented
This is ready for a first review. It's quite big but can wait until 3.0 is out of the door. Probably needs to be reviewed by @sergisiso.

2024-11-28 17:02 UTC, arporter commented
Trying this updated branch with LFRic (and my enhanced global.py) I now get:
```
Failed to module-inline routine coordinate_jacobian:
Transformation Error: routine 'coordinate_jacobian' contains accesses to 'jacobian_abr2xyz' which is declared in the same module scope. Cannot inline such a routine.
```
where `jacobian_abr2xyz` is actually a routine in the same module so we could inline it...

Also get
```
File '../lfric/components/science/source/kernel/geometry/chi_transform_mod.F90' does contain module 'chi_transform_mod' but PSyclone is unable to create the PSyIR of it.
```
This is possibly because that module contains an unsupported form of interface definitions:
```fortran
  INTERFACE
    SUBROUTINE chi2xyz_interface(chi_1, chi_2, chi_3, panel_id, x, y, z)
      IMPORT :: r_def, i_def
      IMPLICIT NONE
      INTEGER(KIND = i_def), INTENT(IN) :: panel_id
      REAL(KIND = r_def), INTENT(IN) :: chi_1, chi_2, chi_3
      REAL(KIND = r_def), INTENT(OUT) :: x, y, z
    END SUBROUTINE chi2xyz_interface
  END INTERFACE
```

2024-11-28 17:12 UTC, arporter commented
Attempt to do recursive inlining:
```
Failed to inline call jacobian_abr2xyz(alpha, beta, radius, panel_id):
Transformation Error: Routine 'jacobian_abr2XYZ_r_single' cannot be inlined because it accesses variable 'r_single' from its parent container.
```
but `r_single` is actually named in an import into the parent container => should be easy to handle.

2025-04-10 13:43 UTC, arporter commented
Got a crash while processing `init_saturated_profile_alg_mod.x90`:
```
  File "/home//Projects/PSyclone/src/psyclone/domain/lfric/lfric_loop.py", line 895, in gen_code
    super().gen_code(parent)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/home//Projects/PSyclone/src/psyclone/psyir/nodes/loop.py", line 581, in gen_code
    kernel.rename_and_write()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home//Projects/PSyclone/src/psyclone/psyGen.py", line 1664, in rename_and_write
    self._rename_psyir(new_suffix)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home//Projects/PSyclone/src/psyclone/psyGen.py", line 1741, in _rename_psyir
    kern_schedule.name = new_kern_name[:]
    ^^^^^^^^^^^^^^^^^^
  File "/home//Projects/PSyclone/src/psyclone/psyir/nodes/routine.py", line 419, in name
    sym = self.symbol_table.lookup(symbol.name)
```
because the Routine instance doesn't yet have a symbol table.

2025-04-10 14:26 UTC, arporter commented
Fixed that and now get failure when doing:
```
LFRIC_OFFLOAD_DIRECTIVES=omp psyclone -api lfric -d /Projects/LFRic/spack_gfortran/lfric_apps_7536/applications/gungho_model/working/build_gungho_model -s applications/gungho_model/optimisation/psyclone-test/global.py /Projects/LFRic/spack_gfortran/lfric_apps_7536/applications/gungho_model/working/build_gungho_model/algorithm/initialisation/init_saturated_profile_alg_mod.x90
```
because the kernel schedule obtained in `CodedKern._rename_and_write()` has somehow been detached from its parent container.

2025-04-10 20:05 UTC, arporter commented
```
Failed to annotate 'initial_theta_code' with GPU-enabled directive due to:
Transformation Error: Kernel 'initial_theta_code' accesses the symbol 'analytic_temperature: RoutineSymbol<UnresolvedType, pure=unknown, elemental=unknown>' which is imported. If this symbol represents data then it must first be converted to a Kernel argument using the KernelImportsToArguments transformation.
Successfully offloaded loop with ['inc_x_times_y']
Added OMP threading to loop with ['initial_theta_code']
```

2025-04-11 11:28 UTC, arporter commented
Further investigation shows that it is when generating the code for `invoke_5` that we get the failure. When processing this invoke I see:
```
Transforming invoke 'invoke_5' ...
setting _parent None
setting _parent None
setting _parent None
setting _parent Container[init_saturated_profile_alg_mod_psy]

setting _parent None
setting _parent Container[init_saturated_profile_alg_mod_psy]

Failed to module-inline kernel 'theta_e_code' due to:
Transformation Error: Kernel 'theta_e_code' cannot be module inlined into Container 'init_saturated_profile_alg_mod_psy' because a *different* routine with that name already exists and versioning of module-inlined subroutines is not implemented yet.
Annotated kernel 'theta_e_code'
```

2025-04-15 09:12 UTC, arporter commented
LFRic with OMP offload now fails to compile:
```
NVFORTRAN-S-1058-Call to NVHPC runtime function not supported - pgf90_matmul_real4_i8 (algorithm/solver/pressure_diag_precon_alg_mod_psy.f90: 36)
  0 inform,   0 warnings,   1 severes, 0 fatal for dg_matrix_vector_code_r_single
```

2025-04-15 14:16 UTC, arporter commented
```
Failed to replace MATMUL in 'project_eliminated_theta_q32_code' because:
Transformation Error: Matmul2CodeTrans only supports the transformation of a MATMUL operation when it is the sole operation on the rhs of an assignment.
Annotated kernel 'project_eliminated_theta_q32_code'
```

2025-04-24 09:28 UTC, arporter commented
NEMOv4 OpenACC Kernels integration test failed with:
```
NVFORTRAN-S-0155-Ambiguous interfaces for generic procedure mpp_sum (/home/me/NEMO/cfgs/SPITZ12_openacc_kernels/WORK/bdyini.f90: 1742
```
This is with NVHPC 25.1. I've tried to reproduce this with 25.3 but no joy - it compiled fine.

2025-04-24 13:22 UTC, arporter commented
The difference seems to be that in the runner, we PSyclone lib_mpp.f90 whereas it is excluded (for some reason) when I attempt to replicate it locally.

2025-04-24 14:27 UTC, arporter commented
It looks as though we've inlined `mpp_sum` into `bdy_oce` but haven't made the interface symbol private:
```bash
$ grep -i 'interface mpp_sum' psycloned-openacc_kernels/*90
psycloned-openacc_kernels/bdy_oce.f90:  interface mpp_sum
psycloned-openacc_kernels/bdy_oce.f90:  end interface mpp_sum
psycloned-openacc_kernels/lib_mpp.f90:  interface mpp_sum
psycloned-openacc_kernels/lib_mpp.f90:  end interface mpp_sum
```

2025-04-24 17:34 UTC, arporter commented
I tried adding `lib_mpp` to the modules that the frontend will resolve but the resulting inlining of mpp_sum in icbrst.f90 caused another compilation failure with "ambiguous interface". Presumably because lib_mpp is imported in load of other modules and, of course, NEMO always does wildcard imports so there are lots of other ways the original `mpp_sum` could be brought into scope. The only solution to this is #2846 so that's probably what I'll do after this one.

2025-04-25 07:36 UTC, arporter commented
This is now ready for first review. Integration tests pass. I'm thinking we probably need to rename `Kern.get_kernel_schedule()` but I'll let you see what you think. Probably another one for @sergisiso I'm afraid (but it's a lot smaller than the last one).

2025-04-28 14:21 UTC, sergisiso requested changes
@arporter I made a first high-level review, I link the implementation but not so much the method return type that it leads to lots of ` = kernels[0]` over the code which can silently produce errors, so I suggested another interface which could allow to revert some of this changes. Let me know what you think.

2025-04-28 14:21 UTC, sergisiso commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +            :py:class:`psyclone.psyir.symbols.GenericInterfaceSymbol`)]
I would also return a union one or the other, not a tuple of one plus maybe the other, so basically:
```
if isinstance(node, CodedKern):
    return node.get_kernel_schedule()
...
```

2025-04-28 14:21 UTC, sergisiso commented on src/psyclone/psyir/nodes/call.py
> +                            routines.append(psyir)
I don understand why we resolve_routine but then not use the returned name. Should it be "name" what we pass to "find_routine_psyir"?

2025-05-28 11:02 UTC, arporter commented on src/psyclone/domain/lfric/lfric_kern.py
> +                      list[:py:class:`psyclone.psyGen.KernelSchedule`]]
I started doing this but have hit a snag - currently `GenericInterfaceSymbol.routines` returns `List[tuple[:py:class:`psyclone.psyir.symbols.RoutineSymbol`, bool]]`. There's no way to get from that to the `Routine` 's themselves.

2025-05-28 15:06 UTC, arporter commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
>                  # Compare the routine to be inlined with the one that
Good spot, done.

2025-05-28 15:46 UTC, arporter commented on src/psyclone/psyir/nodes/call.py
> +                            routines.append(psyir)
Ah! That seems to be an error. I need to make sure this is exercised by a test.

2025-05-28 16:12 UTC, arporter commented on src/psyclone/psyir/nodes/call.py
> +                            routines.append(psyir)
I've monkeypatched my way to a test for this.

2025-06-06 15:32 UTC, arporter commented
Finally got a profile with the same version of LFRic as used in the integration tests:
![image](https://github.com/user-attachments/assets/9368d490-dc16-4aae-9106-5bed4549af9d)
This is approximately one time-step. The big 'gap' at the end is for weighted_proj2thetav called from si_operators_alg_mod. I think this is where there are kernels with calls to relatively complex routines that we haven't handled yet.

2025-06-09 09:59 UTC, arporter commented
Ready for another look now. I haven't yet renamed `get_kernel_schedule` but will do this as a final step if you're happy with the approach.

2025-06-10 12:05 UTC, sergisiso requested changes
This is getting close @arporter, it is just minor comments now.

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +        return node.get_callees()
I like the new return value of get_kernel_schedule(), it solves my main issue with the previous implementation that it was easy to miss. Now a kernesl[0] is required and it is the user responsibility to do this assumption.

Regarding the name, this method made me realise that we now return the same as `get_callees` which is great. We also plan to make codedkernels subclass of Call at some point, so it would make sense to rename `get_kernel_schedule` to `get_callees`? Otherwise, we will have 2 methods with the same intent when we change the hierarchy. Also, it hides the distinction from the transformations. For instance, this whole `_get_psyir_to_inline` can be removed and just use the `get_callees` in its place. This is good because this is a generic psyir transformation and is not ideal that it currently depends on CodedKern, which is a psykal component.

2025-06-10 12:05 UTC, sergisiso commented on examples/lfric/scripts/gpu_offloading.py
> +`
There is a leftover backtick in this line

2025-06-10 12:05 UTC, sergisiso commented on examples/lfric/scripts/gpu_offloading.py
> +    :param kern: the Kernel or Routine to inline any Calls into.
Kernel is 'kind of a Call' and routine is a Routine. Technically kernel is not necessarily a CodedKern, but in this case we only care about CodedKerns.

The different argument type make the implementation more complicated: e.g. get_kernel_schedule is called inside but get_callees, is called outside. The same with the recursion, get_kernel_schedule is called at the top while get_callees is called in the inner nest just before recursing.

I think it will be nicer to pick one or the other (call or routine) in both cases. Specially if you take the suggestion of using "get_callees" as a common method name.

2025-06-10 12:05 UTC, sergisiso commented on examples/lfric/scripts/gpu_offloading.py
> +            continue
I see this is stopped here, but the inlining transformations below are already in try/excepts. Is something failing that the try/except misses? I am asking just to know, this PR is already a big step if removing this continue needs other fixes it can be in a follow up.

2025-06-10 12:05 UTC, sergisiso commented on examples/lfric/scripts/kernel_print.py
> +            for ksched in kernel_schedules:
Maybe merge these lines, if the expression is only used once we don't need a variable for it.

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +            caller_name) if len(codes_to_inline) > 1 else None
I think this inlined if else is a bit hard to read, maybe:
```
interface_sym = None
if len(codes_to_inline) > 1:
   interface_sym = codes_to_inline[0].symbol_table.lookup(caller_name)
```

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +            caller_name) if len(codes_to_inline) > 1 else None
There is also a small caveat here, since we are using the caller name in the callee scope we want to use  "node.routine.interface.orig_name" and not "node.routine.symbol.name" to be resistant to renaming imports. It is not as simple as changing caller_name because I see below is used for callsite_table. So maybe we need a new "caller_external_name" which is "caller_name" unless a interface.orig_name is available?

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +                return
Why don't we do this in the validate and return a TransformationError?

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +    def get_interface_symbol(self) -> Union[GenericInterfaceSymbol, None]:
`Optional[GenericInterfaceSymbol]` ?

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/psyir/nodes/intrinsic_call.py
> +            IntrinsicCall.Intrinsic.MATMUL,
Just checking if this is intentional or a leftover, in the transformation script you inline these saying that they sometimes cause issues with the nvidia compiler.

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
> +    assert "!$acc routine seq" in output
could we do `assert output.count("!$acc routine seq") == 2` ?

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +        ''' Bring the kernel/subroutine into this Container.
Maybe "Bring the implementation of this kernel/call into this container." (To not confuse what it takes as node)

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
> -    assert gen.count("end subroutine testkern_qr_code") == 1
Can we put this back? Are this 0 (or not in gent) and 1 now?

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
> +    # Since we don't currently rename module-inlined kernels, module-inlining
Mention the issue number that will resolve this

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/transformations.py
>              k_or_r = "routine"
This also seems to take a kern (call) or a routine. Nemo needs routines as we search them by name since they may not be in the same file than the caller. Would it be possible to bring the `kernel_schedules = node.get_kernel_schedule()` outside in LFRic where this is called to be consistent? We can still do:
```
if isinstance(node, KernScedule):
```
if it helps to give different error messages.

(Can be a separate PR is this is getting to big)

2025-06-10 12:05 UTC, sergisiso commented on src/psyclone/transformations.py
>              k_or_r = "routine"
I see below that this is also the case in OMPDeclareTargetTrans, so maybe a separate PR

2025-06-13 13:38 UTC, arporter commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +        return node.get_callees()
Oh yes, that's a really good idea. I've renamed it and removed `_get_psyir_to_inline`. Happy days.

2025-06-13 13:38 UTC, arporter commented on examples/lfric/scripts/gpu_offloading.py
> +`
Oops.

2025-06-20 10:05 UTC, arporter commented on examples/lfric/scripts/gpu_offloading.py
> +    :param kern: the Kernel or Routine to inline any Calls into.
I've simplified this now since there's a bit more to do to get full inlining working (currently the transformation rejects a Kernel as it wants a Routine).

2025-06-20 10:05 UTC, arporter commented on examples/lfric/scripts/gpu_offloading.py
> +            continue
Yes, simplified for now.

2025-06-20 10:05 UTC, arporter commented on examples/lfric/scripts/kernel_print.py
> +            for ksched in kernel_schedules:
Done.

2025-06-20 15:55 UTC, arporter commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +            caller_name) if len(codes_to_inline) > 1 else None
Oh yes, that was a very good spot. I've added two new tests and updated the code so that it works for renamed imports. It's a bit hot and it's complicated code so I may need to review what I've done.

(I also realised that I needed to forbid an attempt to module-inline a polymorphic routine if the call site didn't have a parent Container that I could declare the interface in.)

2025-06-23 08:37 UTC, arporter commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +                return
Good point, done.

2025-06-23 08:38 UTC, arporter commented on src/psyclone/domain/lfric/lfric_kern.py
> +    def get_interface_symbol(self) -> Union[GenericInterfaceSymbol, None]:
I thought you didn't like `Optional` on a return value (or perhaps that was Rupert)? I'm happy though so done.

2025-06-23 08:44 UTC, arporter commented on src/psyclone/psyir/nodes/intrinsic_call.py
> +            IntrinsicCall.Intrinsic.MATMUL,
I wasn't sure about this - it only causes issues in LFRic where there's mixed precision. Otherwise it's fine. However, I've commented it out again now and left a comment.

2025-06-23 08:49 UTC, arporter commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
> +    assert "!$acc routine seq" in output
Yes!

2025-06-23 08:50 UTC, arporter commented on src/psyclone/domain/common/transformations/kernel_module_inline_trans.py
> +        ''' Bring the kernel/subroutine into this Container.
Done.

2025-06-23 08:51 UTC, arporter commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
> -    assert gen.count("end subroutine testkern_qr_code") == 1
I can't remember what happened there but it seems they are back already. Presumably as part of a change I did earlier.

2025-06-23 08:52 UTC, arporter commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
> +    # Since we don't currently rename module-inlined kernels, module-inlining
Done.

2025-06-23 09:46 UTC, arporter commented on src/psyclone/transformations.py
>              k_or_r = "routine"
Yes, I started doing this and it got out of hand. As things stand, it would become the responsibility of the person writing the transformation script to do `node.get_callees()`, allow for cases where the PSyIR can't be obtained, and then call the transformation on each result. That doesn't feel very nice.

2025-06-23 10:57 UTC, arporter commented
Ready for another look now. CodeCov is doing weird things but perhaps it will get sorted out if master moves on and then we bring this branch up to date.

2025-06-30 09:45 UTC, sergisiso commented
@arporter since you are on AL I fixed the merge conflicts and a leftover get_kernel_schedule myself as I want to proceed with the integration tests for this PR.

2025-06-30 12:37 UTC, sergisiso approved these changes
@arporter All my previous comments have been addressed, the coverage was complete and the integration tests all passed (the system was noisy but there seems to be a slowdown by doing more kernels on the gpu, this is acceptable as the coverage is significantly increased and we don't do the code-inline and atomics yet).

Good job @arporter this has been a long PR but I like how it has end up. This opens the door to do the code-inlining of the mixed kernels and the deprecation of okern.

2025-06-30 13:01 UTC, merged