2758 fix compilation tests
stfc/PSyclone pull request #2759
Opened 2024-10-28 12:02 UTC by hiker

A few small changes to fix #2758.

2024-10-28 13:08 UTC, hiker commented
Ready for review. The link check failure (to https://fortranwiki.org/fortran/show/Intrinsic+procedures) is not caused by this PR, the site seems unavailable atm.

2024-10-29 09:46 UTC, arporter requested changes
Thanks very much for the quick fix Joerg. All looks good and nice to see how encapsulated the problem was.
However, I've realised that we have `lib/extract/{netcdf,standalone}/nemo` and the READMEs in those directories talk about the NEMO API. Would you mind renaming those directories (perhaps s/nemo/no_psykal/ or something) and updating the READMEs too?

2024-12-11 23:11 UTC, hiker commented
I completely missed that PR. By now, Sergi has renamed the directory. I've fixed the references to NEMO in the files that were still there. The only exception are references to `examples`, where we still have a NEMO directory.

2024-12-17 08:44 UTC, hiker commented on .github/workflows/compilation.yml
>    push
I have no idea how it shows up for you. Looking at "Files Changed" above, it doesn't show up. Looing at `git blame`, I am also not seeing anything from me:
```
psyclone/.github/workflows$ git blame compilation.yml | grep -v Andrew | grep -v Nobre | grep -v Siso
psyclone/.github/workflows$ 
```
Only Nuno, Sergi, and you show up in blame :( Where do you see a change?

2024-12-17 08:46 UTC, hiker commented
@arporter: I've updated it to latest master. Could you tell me where you see a modification to a yaml file?

2024-12-17 09:00 UTC, arporter commented
I've triggered the integration tests.

2024-12-17 09:09 UTC, arporter commented
The compilation tests failed (https://github.com/stfc/PSyclone-mirror/actions/runs/12369603001/job/34521856319) :-( Would you mind taking a look @hiker?

2024-12-17 10:17 UTC, hiker commented
It worked for me, because I had a jinja-procssed file in `extract/tandalone/lfric`, which is missing in a clean checkout.

What I don't understand: how on earth did that pass even the normal CI? For me (once I cleaned that directory), normal (non-compilation) tests failed, because the file was missing :(  No idea. I've removed the preprocessed file  `extract/standalone/read_kernel_data_mod.f90`, and added it to `extract/standalone/lfric`. Will test CI and then compilation test (which again worked for me, and I tried to clean my directories properly :) )

Note that gocean extraction is not affected - at this point gocean does not inline the dependent modules (and therefore does not need this file at all).

2024-12-17 16:54 UTC, merged