(towards #2543) Simplify Introduction documentation
stfc/PSyclone pull request #2770
Opened 2024-11-08 12:13 UTC by sergisiso

- I made termcolour and graphviz standard dependencies (its more consistent and requires less documentation than being optional)

- I removed lots of documentation that seem unneeded

- I started using sphinx tabs for alternative options, see image:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/364110df-6d5f-4956-b1c7-d90436e04da1">

2024-11-12 12:12 UTC, sergisiso commented
@arporter @hiker This is ready for review. A bit unfortunately the linkcheck does not pass because the last commit updated a link to https://github.com/stfc/PSyclone/tree/master/tutorial/practicals/generic which won't exist until itself is merged, but you can check in the previous commit that the tests pass with the warning as errors flags.

2024-11-13 16:52 UTC, arporter requested changes
Nice job Sergi. Thanks very much for all your work on improving the documentation.
Mostly small things. The only concern I have is that the funky new 'tab' option doesn't render very well in latexpdf but perhaps we can tweak it (or just live with it)?
docs build fine for me (and this is now tested in the CI which is great).

2024-11-13 16:52 UTC, arporter commented on doc/user_guide/getting_going.rst
> +    in its own ``virtual environment`` we recomment reading the
"recommend"

2024-11-14 09:51 UTC, sergisiso commented on .github/workflows/python-package.yml
> +    # First we need a first build and launching a server, otherwise the
Done

2024-11-14 09:51 UTC, sergisiso commented on .github/workflows/python-package.yml
> +    # - run: cd doc/reference_guide; make html
Done

2024-11-14 09:54 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +please see :ref:`Installation section in the Developer Guide <dev-installation>`.
Done

2024-11-14 09:54 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +    in its own ``virtual environment`` we recomment reading the
Done

2024-11-14 09:54 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +    For more information about how to use Spack we recommend readign the
Fixed

2024-11-14 09:55 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +PSyclone installation location will vary depending on the specific installation
Done

2024-11-14 09:55 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +method and options used. The ``pyclone`` command will typically already be
Done

2024-11-14 09:57 UTC, sergisiso commented on doc/user_guide/getting_going.rst
>  Various aspects of PSyclone are configured through a configuration
Done

2024-11-14 09:58 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +   If PSyclone is installed in 'editable' mode (``-e`` flag to ``pip``), ``pip``
Deleted

2024-11-14 10:00 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +
Added mention to it in parenthesis

2024-11-14 10:08 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +.. tabs::
I see, what do you think if they are uppercase and with colon?

web:
<img width="569" alt="image" src="https://github.com/user-attachments/assets/52c7bf6b-b5e5-4106-a562-03edcbc717aa">
pdf:
<img width="489" alt="image" src="https://github.com/user-attachments/assets/437d5544-f34b-4e56-91b8-5c5ded0860c7">

2024-11-14 10:09 UTC, sergisiso commented on doc/user_guide/getting_going.rst
> +the code-transformation mode (when no ``-api``/``--psykal-dsl`` flags is provided) or the
Done

2024-11-14 10:10 UTC, sergisiso commented on doc/user_guide/tutorials_and_examples.rst
> +(this is only recommended for people interested in PSKAL DSLs and LFRic in particular).
Fixed

2024-11-14 10:10 UTC, sergisiso commented on doc/user_guide/tutorials_and_examples.rst
> +download the hand-on directory with:
Fixed

2024-11-14 10:11 UTC, sergisiso commented on doc/user_guide/tutorials_and_examples.rst
> +The tutorial is divided in two sections, a first section that introduces
Fixed

2024-11-14 10:12 UTC, sergisiso commented on doc/user_guide/tutorials_and_examples.rst
>  NEMO API in PSyclone. They are *not* intended as 'turn-key' solutions but
Done

2024-11-14 10:28 UTC, sergisiso commented on src/psyclone/tests/conftest.py
>      ''' Whether or not the system has graphviz installed. Note that this
Updated

2024-11-14 10:29 UTC, sergisiso commented on tutorial/practicals/generic/Makefile
>  # Top-level Makefile to test all of the NEMO hands-on tutorials.
Done

2024-11-14 10:33 UTC, sergisiso commented
@arporter This is ready for another review

2024-11-14 19:52 UTC, arporter commented on doc/user_guide/getting_going.rst
> +.. tabs::
Oh yes, that's better.

2024-11-14 19:52 UTC, arporter commented on doc/user_guide/tutorials_and_examples.rst
>  as a starting point.
Great, thanks.

2024-11-14 19:55 UTC, arporter approved these changes
All looks good now. Thanks very much.
Will proceed to merge.

2024-11-14 21:05 UTC, merged