Support optional and named arguments in inlining
stfc/PSyclone pull request #2801
Opened 2024-11-23 12:41 UTC by schreiberx

This PR would solve issue #2525

2024-11-24 19:39 UTC, schreiberx commented
This PR depends on PR #2775

2025-01-14 19:50 UTC, schreiberx commented
@arporter @sergisiso @hiker I thought it would be good to have you all informed about this PR because of some restructuring of the callee detection and I guess this is getting more and more important for other use cases of psyclone.

We have the following two different situations:
- We like to create a call trace. However, we don't want to use the inline transformation for a call trace. What we would like to have is to find the callee.
- If we like to inline, we need to find the callee as well.
Since finding the matching callee for interfaced calls/subroutines is part of these two situations, and since adding the feature of supporting optional and named arguments added quite a lot of lines of codes, I put the functionality to find the matching calls/subroutine into the file in
`psyir/tools/call_routine_matcher.py`
To do the coverage tests in the Andy style (Each test has to cover 100% of the corresponding file), I moved over various test cases which have been formerly part of the `call_tests.py` and `inline_trans_tests.py` to the new test file `call_routine_matcher_tests.py` .
All three test files now result in 100% coverage of the respective python file.

2025-01-21 09:15 UTC, arporter requested changes
Thanks very much Martin, this is exciting functionality. However, there are a couple of biggish issues that I want to tackle before I go any further with the review. First, you have implemented a different way of handling options for InlineTrans. We need project-wide agreement on how we do this so that we can adopt a uniform approach (#2668 ). We should use #2668 to come to some agreement and then you can implement that here. Second, you have cool new functionality to remove branching when the condition is a literal and I think that should be broken out as a separate transformation with an associated PR.
Finally, there are some files with non-functional changes that you can just revert to master to shrink this PR.

2025-01-21 09:15 UTC, arporter commented on src/psyclone/psyir/transformations/inline_trans.py
> +    def set_option(
1. This list of options is massive - can it be refined/reduced?
2. As mentioned elsewhere, we haven't yet agreed on how to handle options to transformations (#2668) so please stick with the current method for now.

2025-01-21 09:15 UTC, arporter commented on src/psyclone/psyir/transformations/inline_trans.py
> +        self._ret_arg_match_list: List[int] = None
Why is this Transformation class now holding state? I wouldn't expect this to be necessary...

2025-01-21 09:15 UTC, arporter commented on src/psyclone/psyir/transformations/inline_trans.py
> +        :param routine: PSyIR subroutine to be inlined.
What's the reason for adding this argument?

2025-01-21 09:15 UTC, arporter commented on src/psyclone/psyir/transformations/inline_trans.py
> +        # self.node_routine and self._ret_arg_match_list
Ah, so that's why there's state? Please update the comments on the declarations of these member variables.

2025-01-21 09:15 UTC, arporter commented on src/psyclone/psyir/transformations/inline_trans.py
> +        # arguments and to which routine arguments they are matched to.
"...and which routine arguments..."

2025-01-21 09:15 UTC, arporter commented on src/psyclone/psyir/transformations/inline_trans.py
> +        self._optional_arg_eliminate_ifblock_if_const_condition()
Nice. However, I think this should be a separate transformation. That way, it can be used after @hbrunie 's new `ReplaceReferenceByLiteralTrans` (#2828) to eliminate branching. For preference I think this should be done as a separate PR to avoid us ending up with a massive review again.

2025-07-16 18:44 UTC, schreiberx commented on doc/Makefile
> +	make -C reference_guide html SPHINXOPTS="-W --keep-going"
I'm working on the proposed changes quite late. There have been huge updates on this Makefile => I'll remove my suggested changes since the new version from `master` is much better.

2025-07-16 18:50 UTC, schreiberx commented on doc/Makefile
> +
I'm working on the proposed changes quite late. There have been huge updates on this Makefile. I'll remove my suggested changes since the new version from master is much better.

2025-07-16 19:29 UTC, schreiberx commented on src/psyclone/tests/psyir/transformations/omp_task_transformations_test.py
> +    trans.set_option(check_matching_arguments_of_callee=False)
OK

2025-07-16 19:31 UTC, schreiberx commented on src/psyclone/psyir/transformations/inline_trans.py
> +        self._optional_arg_eliminate_ifblock_if_const_condition()
OK. I'll open first an issue and then we'll see. Not sure if I can do this in the near future.

2025-07-16 20:06 UTC, schreiberx commented on src/psyclone/psyir/nodes/__init__.py
> +        'OMPDependClause',
OK.

2025-07-16 20:07 UTC, schreiberx commented on src/psyclone/psyir/symbols/containersymbol.py
> +        :param ignore_missing_modules: If 'True', no ModuleNotFound exception=
OK.

2025-07-18 15:05 UTC, schreiberx commented
@arporter I'll close this one and reopen another one.

2025-07-18 15:05 UTC, closed without merging

2025-07-18 15:19 UTC, schreiberx commented
For reference, this is the new PR: https://github.com/stfc/PSyclone/pull/3067