2773 add vernier support
stfc/PSyclone pull request #2820
Opened 2024-12-09 12:04 UTC by hiker

Adds a psydata wrapper and (gocean) example for using Vernier.

2024-12-19 11:28 UTC, arporter requested changes
Thanks Joerg. It all looks fine. Just a few typos and I think the default directory name for the location of Vernier should be capitalised.
I've been unable to actually test the code yet as I can't build Vernier (see https://github.com/MetOffice/Vernier/discussions/154). I'll do that next time.

2024-12-19 11:28 UTC, arporter commented on lib/profiling/vernier/Makefile
> +VERNIER_ROOT ?= ./../../../../vernier
A default 'clone' of Vernier results in a directory named `Vernier`. Would perhaps be better to assume this name?

2024-12-19 11:28 UTC, arporter commented on lib/profiling/vernier/README.md
> +VERNIER_ROOT ?= ./../../../../vernier
Again, I'd suggest `Vernier` here and below.

2024-12-19 11:28 UTC, arporter commented on lib/profiling/vernier/README.md
> +writes the output into rank-specific output files, the output is not
"...into MPI-rank-specific output..."

2024-12-19 11:28 UTC, arporter commented on lib/profiling/Makefile
> +# We don't build dl_timer, drhook, nvidia, Vernier, and tau since they
"...and tau by default since..."

2025-01-06 00:57 UTC, hiker commented on examples/gocean/eg5/profile/Makefile
> +# Needs to additionally link with the Vernier library
Done. Gee, there are too many files that need updating when a new profiling lib (and examples) are added :(

2025-01-06 00:58 UTC, hiker commented on lib/profiling/README.md
> +instructions are in [``veriner/README.md``](
I missed it, too, and started to look into the link checker (why on earth do we have a `reviewdog -h` running in our CI??? I couldn't find where that comes from, I just noticed the output)

Anyway, the typo is only in the text displayed, the link itself is correct.

2025-01-06 01:00 UTC, hiker commented on lib/profiling/vernier/Makefile
> +VERNIER_ROOT ?= ./../../../../vernier
It is obviously totally wrong to use capitalised names .... :)  (I do indeed rename everything on checkout :) )
But I've changed that, good pickup.

2025-01-06 01:00 UTC, hiker commented on lib/profiling/vernier/README.md
> +VERNIER_ROOT ?= ./../../../../vernier
Done.

2025-01-06 01:00 UTC, hiker commented on lib/profiling/vernier/README.md
> +writes the output into rank-specific output files, the output is not
Done.

2025-01-06 01:00 UTC, hiker commented on lib/profiling/Makefile
> +# We don't build dl_timer, drhook, nvidia, Vernier, and tau since they
Done.

2025-01-06 01:01 UTC, hiker commented
Ready for next review.

2025-01-07 14:26 UTC, arporter commented on lib/profiling/vernier/Makefile
> +VERNIER_ROOT ?= ./../../../../vernier
Thanks :-)

2025-01-07 14:28 UTC, arporter commented on lib/profiling/README.md
> +instructions are in [``veriner/README.md``](
Oh yes, so it is. I don't know why we have `reviewdog -h` in our CI? Probably I cut-n-pasted the recipe from somewhere...

2025-01-07 14:34 UTC, arporter approved these changes
Thanks for those changes and for helping me to get Vernier built.
I can now confirm I've built and run GOcean eg5 using the Vernier profiling.
I'll need to check the integration tests but this should be ready to go now.

2025-01-07 16:50 UTC, arporter commented
The integration tests were all fine apart from NEMOv.4 which had a weird network error when attempting to upload performance results to mongoDB. Clearly not the fault of this PR. Therefore, I will bring this to master and proceed to merge.

2025-01-07 17:31 UTC, merged