#2826 Add config option to PSyAD
stfc/PSyclone pull request #2829
Opened 2024-12-17 13:46 UTC by mo-alistairp

2025-01-13 15:20 UTC, mo-alistairp commented
Have tested that the new config option passes the new config test using PSyclone's test environment. Have also tested that the reference to configuration in the documentation works when the pdf has been built.

2025-01-13 15:53 UTC, mo-alistairp commented
Have tested that the new config option passes the new config test using PSyclone's test environment. Have also tested that the reference to configuration in the documentation works when the pdf has been built.

2025-01-23 16:44 UTC, arporter requested changes
Thanks for doing this Alistair.
Updated source file is fully covered by updated test file.
Doc builds with a warning that's not your fault but I've requested that you fix it (see inline).
Just a few typos to fix.

2025-01-23 16:44 UTC, arporter commented on doc/psyad/user_guide/psyad_command.rst
> +Further dcoumentation of the configuration option can be read in
"documentation" and "options" please and perhaps "found" rather than "read"?

2025-01-23 16:44 UTC, arporter commented on doc/psyad/user_guide/psyad_command.rst
> +
I note when building the documentation that we have a warning about a broken link:
```
doc/psyad/user_guide/implementation.rst:445: WARNING: undefined label: 'user_guide:available_trans' [ref.ref]
```
Although it's not your fault, it would be good to fix it. I think you need to change `available_trans` to `sec_transformations_available` at the appropriate line in implementation.rst.

2025-01-23 16:44 UTC, arporter commented on doc/psyad/user_guide/psyad_command.rst
> +
(Presumably this also means we're not testing the build of the PSyAD docs in the CI but that can be left for another day.)

2025-01-23 16:44 UTC, arporter commented on src/psyclone/psyad/main.py
> +
No blank line after closing "'''" please.

2025-01-23 16:44 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> +from psyclone.configuration import Config
We try to order imports alphabetically by module name so this line should go before the import from `psyclone.psyad`.

2025-01-23 16:44 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> +    # filename_in = str(tmpdir.join("tl_foo_kernel_mod.f90"))
Please rm this line.

2025-01-23 16:44 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> +    # dummy_config has a non-default REPORD_PAD_SIZE of 7
"REPROD"

2025-01-23 16:44 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> +    with open(filename_in, "w", encoding='utf-8') as my_file:
Comment please (because it took me a while to realise you aren't writing a new config file here), e.g. "Create LFRic kernel file"

2025-01-23 16:44 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> +    print(Config.get().reprod_pad_size)
Please rm.

2025-01-24 15:10 UTC, mo-alistairp commented on doc/psyad/user_guide/psyad_command.rst
> +Further dcoumentation of the configuration option can be read in
Good spot - done

2025-01-24 15:11 UTC, mo-alistairp commented on doc/psyad/user_guide/psyad_command.rst
> +
Done and built for me without any warnings

2025-01-24 15:11 UTC, mo-alistairp commented on src/psyclone/psyad/main.py
> +
Done

2025-01-24 15:11 UTC, mo-alistairp commented on src/psyclone/tests/psyad/main_test.py
> +from psyclone.configuration import Config
Done

2025-01-24 15:11 UTC, mo-alistairp commented on src/psyclone/tests/psyad/main_test.py
> +    # filename_in = str(tmpdir.join("tl_foo_kernel_mod.f90"))
Done

2025-01-24 15:11 UTC, mo-alistairp commented on src/psyclone/tests/psyad/main_test.py
> +    # dummy_config has a non-default REPORD_PAD_SIZE of 7
Done

2025-01-24 15:11 UTC, mo-alistairp commented on src/psyclone/tests/psyad/main_test.py
> +    with open(filename_in, "w", encoding='utf-8') as my_file:
Done

2025-01-24 15:11 UTC, mo-alistairp commented on src/psyclone/tests/psyad/main_test.py
> +    print(Config.get().reprod_pad_size)
Done

2025-01-27 09:32 UTC, arporter requested changes
Almost! You've accidentally deleted part of a test - see inline.
Apart from that, it just needs bringing up-to-date with master.

2025-01-27 09:32 UTC, arporter commented on src/psyclone/tests/psyad/main_test.py
> -    main([filename_in, "-a", "field", "-api", "lfric"])
You've been a bit over-zealous here - it was only the `print` that needed to be removed :-)

2025-01-27 09:36 UTC, arporter commented
(I forgot to say - the PSyAD docs build without a warning now for me too.)

2025-01-27 11:37 UTC, mo-alistairp commented on src/psyclone/tests/psyad/main_test.py
> -    main([filename_in, "-a", "field", "-api", "lfric"])
Appologies - I misunderstood what you were after! 

I've reinstated the overzealous deletion and merged the master branch in

2025-01-28 09:20 UTC, arporter approved these changes
Thanks for fixing that.
All good now.
Will proceed to merge.

2025-01-28 12:02 UTC, merged