#2831 Reorder arguments to parser for consistency
stfc/PSyclone pull request #2832
Opened 2024-12-19 15:12 UTC by mo-alistairp

2025-01-07 10:36 UTC, LonelyCat124 requested changes
Hi @mo-alistairp 

Happy with the changes - I've added one comment to change since I wanted to send it back as you need to add yourself to the Author list in the `generator.py` file. Can you also update the copyright date in that file to include 2025?

I'll submit integration tests in the mean time.

2025-01-07 10:36 UTC, LonelyCat124 commented on src/psyclone/generator.py
>          'output Fortran. Use \'output\' to apply line-length limit to output '
I know this isn't your modiciations, but can you update this string to use double quotes so we can remove the backslashes from the string (i.e. `"output Fortran. Use 'output'....") (This is just PEP8 compliance update).

2025-01-08 09:16 UTC, mo-alistairp commented on src/psyclone/generator.py
>          'output Fortran. Use \'output\' to apply line-length limit to output '
Made the requested changes.

2025-01-09 11:03 UTC, LonelyCat124 approved these changes
No changes to generated code so no need to run Ready to merge.

2025-01-09 11:15 UTC, merged