Martin fileinfo cache 2
stfc/PSyclone pull request #2833
Opened 2024-12-19 16:39 UTC by schreiberx

This is the final PR for the updates on caching fparser (and later on psyir).

This update avoids using the same file multiple times for individual modules in each file.

2024-12-19 16:40 UTC, schreiberx commented
@arporter That's the final PR for the file info caching stuff.
It's probably best to first get the previous PR in the master.

2025-01-10 12:37 UTC, schreiberx commented
@arporter Your turn. Let's try to stay below 50 comments :-)

2025-02-17 11:39 UTC, arporter requested changes
Looks good Martin, this is functionality that will be important to have.
There are a couple of places where you appear to be duplicating functionality that we already have so I've asked for clarification.
I've not looked at the tests yet (but these will require updating anyway when you remove the bare asserts from the code).

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/file_info.py
> +                os.remove(self._get_filepath_cache())
Would this file still exist now that it includes the hash in the filename (i.e. if we need to write the cache file, that's because the hash must have changed)? Or are you just being careful?

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_info.py
> +    def get_routine_by_name(
This is a duplication of `Container.find_routine_psyir()` and `Container.resolve_routine()`. Can this be removed and that functionality used instead (from wherever you call this method).

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
Pls document the `cache_path` argument.

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +                cache_path: str = None
Pls document this in the class docstring.

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        # Ordered dictionary to lookup modules of all files
"...lookup ModuleInfo from a file path."

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        # Dictionary of modules to lookup module info
"...of ModuleInfo objects, indexed by module name"?

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +    def add_files(self, filepaths: Union[str, List[str], Set[str]]) -> None:
Can you have `Iterable[str]` rather than specifying List or Set?

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        """Add a file to the list of files
"Utility to add multiple files to the ModuleManager" perhaps?
Also, "Any file already found to be present in the ModuleManager is skipped."

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +    def load_all_source_codes(self, verbose: bool = False) -> None:
s/codes/files/ perhaps?

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +    def load_all_fparser_trees(self, verbose: bool = False) -> None:
Presumably, this parses source as required, rather than just loading from file? Could therefore be `create_all_fparser_trees`?

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +    def load_all_psyir_nodes(self, verbose: bool = False) -> None:
Again, 'create' rather than 'load' (and again in the docstring).

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        """Load the module info using psyir nodes
"...nodes for all FileInfo objects in the ModuleManager."

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +
No blank line please.

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        Return a list of all module infos
:returns: list of all module infos.

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        Return a list of all FileInfo objects
:returns: ...

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +    def get_all_file_infos(self) -> List[FileInfo]:
Am I right in thinking this doesn't do anything other than return information on objects we've already created? If so, I think this should be an `@property` named `all_file_infos`.

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +    def get_all_module_infos(self) -> List[ModuleInfo]:
c.f. my comment on `get_all_file_infos`, could this be a property named `all_module_infos`?

2025-02-17 11:39 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +    def get_all_recursively_used_module_infos(
Is this a duplication of the functionality already provided by `get_all_dependencies_recursively` and `sort_modules`?

2025-02-20 10:20 UTC, schreiberx commented on doc/developer_guide/module_manager.rst
> +A standard storage path could be, e.g., `$HOME/.cache/psyclone`.
OK.

2025-02-20 10:21 UTC, schreiberx commented on src/psyclone/parse/file_info.py
> +        # Filepath to cache
OK.

2025-02-20 10:21 UTC, schreiberx commented on src/psyclone/parse/file_info.py
> +    def _get_filepath_cache(self):
OK.

2025-02-20 10:22 UTC, schreiberx commented on src/psyclone/parse/file_info.py
> +        assert self._source_code_hash_sum is not None
OK

2025-02-20 10:25 UTC, schreiberx commented on src/psyclone/parse/file_info.py
> +        # We assume this path is shared amongst many.
No, that's not what I meant.
I updated the comment for a better description. Please check.

BTW: That's how it's done with GPU shaders.

2025-02-20 11:56 UTC, schreiberx commented
@arporter Back to you :-)

2025-02-28 10:00 UTC, arporter commented
Thanks Martin. There are a few things to look at including a few you seem to have missed last time :-) I note that there is still at least one bare assert in the code but I'll do a proper grep next time around. Please could you also bring up-to-date with master.

2025-02-28 10:01 UTC, arporter requested changes
Please see inline comments.

2025-03-11 21:28 UTC, schreiberx commented
Back to you Andy!

2025-03-12 17:01 UTC, arporter commented on src/psyclone/parse/module_info.py
> +    def get_routine_by_name(
Still there?

2025-03-13 09:31 UTC, arporter requested changes
Back to you Martin.

2025-03-13 09:31 UTC, arporter commented on src/psyclone/parse/module_info.py
> +    def get_routine_by_name(
In fact, a grep reveals that this is only ever called from a test.

2025-03-13 09:31 UTC, arporter commented on src/psyclone/tests/parse/file_info_test.py
> +    except FileNotFoundError:
This can be improved by using the `tmp_path` fixture instead of `tmpdir` - that will ensure that the directory this test is given is unique to it so the file can't exist.

2025-03-13 09:31 UTC, arporter commented on src/psyclone/tests/parse/file_info_test.py
>      source_code = file_info.get_source_code(verbose=True)
Again, I need some talking through this (comments) please.

2025-03-13 09:31 UTC, arporter commented on src/psyclone/tests/parse/module_manager_test.py
> +def test_mod_manager_get_all_dependencies_recursively_DEPRECATED(capsys):
This should probably be removed?

2025-03-13 09:31 UTC, arporter commented on src/psyclone/tests/parse/module_manager_test.py
> +    mod_man.load_all_source_files()
Please add checks that these calls have modified the internal state of `mod_man` as you expect.

2025-03-13 09:31 UTC, arporter commented on src/psyclone/tests/parse/module_manager_test.py
> +    # Should raise an error that the first module to be processed
Why does this raise an error - can we not silently/safely ignore this if we've already processed it?

2025-03-13 09:31 UTC, arporter commented on src/psyclone/tests/parse/module_manager_test.py
> +    # These are soft errors that don't raise Exceptions
s/These are soft/The missing dependency is a soft/ if that's right? If not, please elaborate a bit.

2025-03-13 09:31 UTC, arporter commented on src/psyclone/tests/parse/module_manager_test.py
> +    get_all_dependencies_recursively_for_module_name():
s/:/when no modules can be found/ perhaps?

2025-03-13 12:57 UTC, schreiberx commented
@arporter Back to you.

2025-03-18 09:44 UTC, arporter commented on src/psyclone/tests/parse/module_manager_test.py
> +    # Should raise an error that the first module to be processed
Still outstanding?

2025-03-18 09:45 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        not_found = list()
Still outstanding?

2025-03-18 09:57 UTC, arporter requested changes
Thanks Martin. Almost done now - there are just two comments that still need a response.
Coverage of the individual files is 100%.
The errors in the link check are not the fault of this PR (in fact, I don't know why they've suddenly appeared).
I've brought the branch up to master so you'll need to pull it.

2025-03-24 16:45 UTC, arporter requested changes
Thanks Martin.
Just one question remaining...

2025-03-24 16:45 UTC, arporter commented on src/psyclone/parse/module_manager.py
> +        not_found = list()
Thanks for updating the comment. I still don't understand why you've changed to a list though?

2025-03-26 16:27 UTC, merged