(closes #1010) Generate PSy-layers and Kernel Subs using PSyIR lowering (instead of gen_code/f2pygen)
stfc/PSyclone pull request #2834
Opened 2024-12-29 17:53 UTC by sergisiso

2025-01-20 09:34 UTC, sergisiso commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
Hey @hiker I have 2 remaining issue with psy_data, one is with name clashes, this can be seen in the following PR FIXMES (the last one is a good example):
```
src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
625:@pytest.mark.xfail(reason="FIXME")
626-@pytest.mark.usefixtures("change_into_tmpdir", "init_module_manager")
627-def test_lfric_driver_external_symbols():
--
661:@pytest.mark.xfail(reason="FIXME")
662-@pytest.mark.usefixtures("change_into_tmpdir", "init_module_manager")
663-def test_lfric_driver_external_symbols_name_clash():
--
708:@pytest.mark.xfail(reason="FIXME")
709-@pytest.mark.usefixtures("change_into_tmpdir", "init_module_manager")
710-def test_lfric_driver_external_symbols_error(capsys):

src/psyclone/tests/psyir/nodes/psy_data_node_test.py
482:@pytest.mark.xfail(reason="FIXME")
483-@pytest.mark.usefixtures("change_into_tmpdir", "clear_module_manager_instance")
484-def test_psy_data_node_name_clash(fortran_writer):
```

I suspect the selected code in psy_data_node.py::create_unique_names . I modified this because using the original left generic Symbols in the symbol_table and the backend failed (maybe this were specialised in a gen_code before)?

2025-01-20 09:37 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
> +        "call extract_psy_data%ReadVariable('m2_data', m2_data)",
@hiker The second issue are these commented out lines. Loop0_start and loop0_stop still don't exist in the symbol table when the psydata calls are created. But they also didn't exist when gen_code was called, so maybe there was a specific logic for this in gen_code that it is not in lower_to_language_level?

2025-01-21 01:03 UTC, hiker commented on src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
> +        "call extract_psy_data%ReadVariable('m2_data', m2_data)",
This is not a psydata issue, its ultimately caused by VariableAccessInfo not getting the loop boundaries - the `loop.start_expr` (and stop) are not defined at the time that the access info is collected, and therefore the values are missing from the list of variables. 
It took me a while to sort this out, I couldn't remember either:
In current master, lfric_loop overwrites `start_expr` (etc), and it automatically creates `loop{indx}_start` expr. So the value is always defined, will therefore get reported as access, and the code is created.

In your branch, the access information has the start expr `Literal[value:'NOT_INITIALISED', Scalar<INTEGER, UNDEFINED>]`, which will not report any access info. 

I couldn't immediately figure out how the loop boundaries are created  in your branch ... `lfric_loop.lower..`  just copies the values from `start_expr`. I think you know this part much better than me and where the loop boundaries are created, but am happy to discuss this further. Either overwriting `start_expr` in lfric_loop to return a proper value would work, or a custom `reference_access` method?

I checked with goloop, it apparently sets the loop boundaries when the node is created:
```
class GOLoop(PSyLoop):
...
    @staticmethod
    def create(parent, loop_type, field_name="", field_space="",
               iteration_space="", index_offset=""):
...
        # Add start, stop, step and body and Loop children
        node.addchild(node.lower_bound())
...
```
So that why it works there.

2025-01-21 03:48 UTC, hiker commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
Yes, that is indeed the problem. I've added what I think is a proper declaration of the symbol here. I also had to change the location where a `post` symbol is added. Can you try the following patch (it needs cleanup obviously):

At the very least the module_manager needs to be imported where it is, I had cyclic dependencies otherwise.
```
joerg@Joerg-Surface:~/work/psyclone/src/psyclone$ git diff psyir/nodes/psy_data_node.py
diff --git a/src/psyclone/psyir/nodes/psy_data_node.py b/src/psyclone/psyir/nodes/psy_data_node.py
index 3741a52af..b2b401b0b 100644
--- a/src/psyclone/psyir/nodes/psy_data_node.py
+++ b/src/psyclone/psyir/nodes/psy_data_node.py
@@ -498,6 +498,17 @@ class PSyDataNode(Statement):
         for (module_name, signature) in var_list:
             if module_name:
                 tag = f"{signature[0]}@{module_name}"
+                from psyclone.psyir import symbols
+                from psyclone.parse import ModuleManager
+                mod_man = ModuleManager.get()
+                mod_info = mod_man.get_module_info(module_name)
+                sym = mod_info.get_symbol(signature[0])
+                var_symbol = \
+                    symbol_table.find_or_create_tag(tag=f"{signature[0]}"
+                                                        f"@{module_name}",
+                                                    root_name=signature[0],
+                                                    symbol_type=symbols.DataSymbol,
+                                                    datatype = sym.datatype)
                 try:
                     var_symbol = symbol_table.lookup(signature.var_name)
                     if tag not in symbol_table.tags_dict:
@@ -678,7 +689,7 @@ class PSyDataNode(Statement):
                     module_name = f"@{module_name}"
                 call = gen_type_bound_call(
                     self._var_name, "PreDeclareVariable",
-                    [f"\"{sig}{module_name}{pre_suffix}\"", unique_sig])
+                    [f"\"{sig}{pre_suffix}{module_name}\"", unique_sig])
                 self.parent.children.insert(self.position, call)
 
             for module_name, sig, unique_sig in post_variable_list:
@@ -686,7 +697,7 @@ class PSyDataNode(Statement):
                     module_name = f"@{module_name}"
                 call = gen_type_bound_call(
                     self._var_name, "PreDeclareVariable",
-                    [f"\"{sig}{module_name}{post_suffix}\"", unique_sig])
+                    [f"\"{sig}{post_suffix}{module_name}\"", unique_sig])
                 self.parent.children.insert(self.position, call)
 
             call = gen_type_bound_call(self._var_name, "PreEndDeclaration")
@@ -697,7 +708,7 @@ class PSyDataNode(Statement):
                     module_name = f"@{module_name}"
                 call = gen_type_bound_call(
                     self._var_name, "ProvideVariable",
-                    [f"\"{sig}{module_name}{pre_suffix}\"", unique_sig])
+                    [f"\"{sig}{pre_suffix}{module_name}\"", unique_sig])
                 self.parent.children.insert(self.position, call)
 
             call = gen_type_bound_call(self._var_name, "PreEnd")
@@ -717,7 +728,7 @@ class PSyDataNode(Statement):
                     module_name = f"@{module_name}"
                 call = gen_type_bound_call(
                     self._var_name, "ProvideVariable",
-                    [f"\"{sig}{module_name}{post_suffix}\"", unique_sig])
+                    [f"\"{sig}{post_suffix}{module_name}\"", unique_sig])
                 self.parent.children.insert(self.position, call)
 
         # PSyData end call
```

I also had to patch one test (so far):
```
--- a/src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
+++ b/src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
@@ -622,7 +622,6 @@ def test_lfric_driver_field_array_inc():
 
 
 # ----------------------------------------------------------------------------
-@pytest.mark.xfail(reason="FIXME")
 @pytest.mark.usefixtures("change_into_tmpdir", "init_module_manager")
 def test_lfric_driver_external_symbols():
     '''Test the handling of symbols imported from other modules, or calls to
@@ -646,7 +645,7 @@ def test_lfric_driver_external_symbols():
     with open(filename, "r", encoding='utf-8') as my_file:
         driver = my_file.read()
 
-    assert ("call extract_psy_data % ReadVariable('module_var_a_post@"
+    assert ("call extract_psy_data%ReadVariable('module_var_a_post@"
             "module_with_var_mod', module_var_a_post)" in driver)
     assert ("call compare('module_var_a', module_var_a, module_var_a_post)"
             in driver)
```
which I would expect other tests need an update as well (since the output format has no spaces).

I'll try to continue tomorrow. I still have issues with the name clash test etc.

2025-01-21 04:27 UTC, hiker commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
Oops, I forgot, the symbol must be imported. So the following should be correct (only the first bit, changing the order of the module and prefix as above).
```
diff --git a/src/psyclone/psyir/nodes/psy_data_node.py b/src/psyclone/psyir/nodes/psy_data_node.py
index 3741a52af..884483d84 100644
--- a/src/psyclone/psyir/nodes/psy_data_node.py
+++ b/src/psyclone/psyir/nodes/psy_data_node.py
@@ -498,15 +498,20 @@ class PSyDataNode(Statement):
         for (module_name, signature) in var_list:
             if module_name:
                 tag = f"{signature[0]}@{module_name}"
-                try:
-                    var_symbol = symbol_table.lookup(signature.var_name)
-                    if tag not in symbol_table.tags_dict:
-                        symbol_table.tags_dict[tag] = var_symbol
-                    elif symbol_table.tags_dict[tag] is not var_symbol:
-                        raise ValueError("Already used tag")
-                except KeyError:
-                    print(f"Missing {signature.var_name}")
-                    continue
+                from psyclone.psyir import symbols
+                from psyclone.parse import ModuleManager
+                mod_man = ModuleManager.get()
+                mod_info = mod_man.get_module_info(module_name)
+                sym = mod_info.get_symbol(signature[0])
+                container = symbol_table.find_or_create(module_name,
+                                                    symbol_type=symbols.ContainerSymbol)
+                var_symbol = \
+                    symbol_table.find_or_create_tag(tag=f"{signature[0]}"
+                                                        f"@{module_name}",
+                                                    root_name=signature[0],
+                                                    symbol_type=symbols.DataSymbol,
+                                                    interface=ImportInterface(container),
+                                                    datatype = sym.datatype)
                 unique_sig = Signature(var_symbol.name, signature[1:])
             else:
                 # This is a local variable anyway, no need to rename:
```

2025-01-21 09:39 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
> +        "call extract_psy_data%ReadVariable('m2_data', m2_data)",
> I couldn't immediately figure out how the loop boundaries are created in your branch
> In current master, lfric_loop overwrites `start_expr` (etc), and it automatically creates `loop{indx}_start` expr.

Ah I see, I purposely did this because creating these variables at `start_expr`/... felt a bit like a hacky solution (the assignment to this value is not created until gen_code/lowering, and it's unclear what happens if we end up modifying this start-expression, e.g. changing it to a literal or by fusing loops). Also, the logic was repeated in the lowering/gen_code, so I left that one be the source of true.

I think the right solution is to generate them at the beginning, "at psy-layer creation", so we never have a "NOT_INITIALISED" literal to begin with, but this is too big of a change for this already big PR. So I may re-introduce a temporary/hacky solution until the.

2025-01-21 22:15 UTC, hiker commented on src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
> +        "call extract_psy_data%ReadVariable('m2_data', m2_data)",
> Ah I see, I purposely did this because creating these variables at `start_expr`/... felt a bit like a hacky solution (the assignment to this value is not created until gen_code/lowering, and it's unclear what happens if we end up modifying this start-expression, e.g. changing it to a literal or by fusing loops). Also, the logic was repeated in the lowering/gen_code, so I left that one be the source of true.

Yes, that might be an issue. But at the time psydata is running, everything is under the control of a user script already, right? So it's up to the user not to modify loop boundaries **after** determining the variables required.
But the same would be true for anything, e.g. if you modify kernel parameters or so)

And of course, to modify the loop boundaries you could just change the assignment to `loop0_start` etc, that will continue to work ... except if you also change step, which atm is not a variable.

2025-01-21 23:49 UTC, hiker commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
> 708:@pytest.mark.xfail(reason="FIXME")
> 709-@pytest.mark.usefixtures("change_into_tmpdir", "init_module_manager")
> 710-def test_lfric_driver_external_symbols_error(capsys):

Really no idea what is happening.  An fparser failure is expected, but on master this happens only later in the extraction and gets caught., here it appears already when parsing the x90 file. The file parsed in get_invoke itself is fine. Did you change anything in this PR that would trigger parsing of used modules (which is where the error would happen).

The import/use sequence is:
```
./invoke_kernel_with_imported_symbols_error.f90 -> testkern_import_symbols_error_mod.f90 ->module_with_error_mod.f90
```
Only the last module contains invalid Fortran syntax, so parsing the invoke file and kernel itself should be fine. Let me know if you are not aware of any changes in this PR that should affect the parsing of the invoke and testkern above (which should be fine), then I'll debug further.

Since this is invalid syntax, I am happy with changes in the behaviour here. The reason for this test is that (atm) I want to be able to process as much as possible from LFRic_atm without aborting (and the failures would be caused by us not supporting certain features in the UM of course) - i.e. printing the error, and otherwise ignoring it. There is a ticket open to fix that (i.e. properly abort with detailed error messages), but for now I really rely on being able to test the kernel extraction on all files, without the build process aborting at the first error. That is the only reason for this test.

2025-01-21 23:58 UTC, hiker commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
> src/psyclone/tests/psyir/nodes/psy_data_node_test.py
> 482:@pytest.mark.xfail(reason="FIXME")
> 483-@pytest.mark.usefixtures("change_into_tmpdir", "clear_module_manager_instance")
> 484-def test_psy_data_node_name_clash(fortran_writer):
> ```
One problem is a simple typo:
```
     assert ('CALL extract_psy_data % PreDeclareVariable("f1_data@'
-            'module_with_name_clash_mod", f1_data_1)' == code)
+            'module_with_name_clash_mod", f1_data_1)' in code)
```

2025-01-22 00:12 UTC, hiker commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
> 661:@pytest.mark.xfail(reason="FIXME")
> 662-@pytest.mark.usefixtures("change_into_tmpdir", "init_module_manager")
> 663-def test_lfric_driver_external_symbols_name_clash():

Some simple whitespace errors:
```
@@ -675,12 +673,11 @@ def test_lfric_driver_external_symbols_name_clash():
                   options={"create_driver": True,
                            "region_name": ("import", "test")})
     code = psy.gen
-
     # Make sure the imported, clashing symbol 'f1_data' is renamed:
     assert "use module_with_name_clash_mod, only : f1_data_1=>f1_data" in code
-    assert ('CALL extract_psy_data%PreDeclareVariable("f1_data@'
+    assert ('CALL extract_psy_data % PreDeclareVariable("f1_data@'
             'module_with_name_clash_mod", f1_data_1)' in code)
-    assert ('CALL extract_psy_data%ProvideVariable("f1_data@'
+    assert ('CALL extract_psy_data % ProvideVariable("f1_data@'
             'module_with_name_clash_mod", f1_data_1)' in code)
 
     # Even though PSyclone cannot find the variable, it should still be
```

I believe that should explain all failures you currently have ... please tag me on teams in case that I miss any update from you here.

2025-01-22 12:32 UTC, sergisiso commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
@hiker Thanks a lot, these are all now fixed, so I am resolving this conversation.

> Since this is invalid syntax, I am happy with changes in the behaviour here. The reason for this test is that (atm) I want to be able to process as much as possible from LFRic_atm without aborting (and the failures would be caused by us not supporting certain features in the UM of course) - i.e. printing the error, and otherwise ignoring it.

I could maintain the previous behaviour (printing errors and continue extraction) and kept this test as it was.

2025-01-22 12:46 UTC, hiker commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    continue
Hi, you can add a TODO #2120 at locations where we should abort. Once I made sufficient progress with kernel extraction that most of UM physics works (or as much as I can even hope to support :) ), I will then properly abort (or maybe add an option if a kernel failure should result in an abort or not). But for now it is really useful for me to just compile all of lfric_atm, to get a good feeling what improvement will have the most impact, so I can focus on that (it is surprisingly annoying to tell Fab to not abort. Make just has an option to keep on going, but Fab doesn't ... and it would take some time to implement this.

2025-01-22 15:45 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
> +        "call extract_psy_data%ReadVariable('m2_data', m2_data)",
@hiker Moving the symbol creation at the beginning was quite easy, it has fixed the remaining psy_data tests and in fact ended up cleaning up some other parts of the code (e.g. allowing NOT_INITIALISED as a valid Integer Literal). I am also resolving this comment.

2025-01-23 12:28 UTC, sergisiso commented
@arporter This is finally ready for review, it is huge because:
- It updates all remaining f2py/gen_code to psyir/lower_to_language_level (I coudn't find a way to split this process)
- It produced stylistic changes to the psy-layer output syntax, and therefore lots of tests had to be slightly updated

However, most of the PR is a 1-to-1 mapping to previous code, I decided to leave the:
- Final removal of f2py intrastructure, and other refactoring now possible (I am still abusing `find_or_create` instead of following a more predictable construction/lookup pattern) to avoid complicating the PR by moving things arround.

I am happy to do this in different review steps if it becomes too much (also Github slows down a lot when reviewing long PRs all at once)

There are a couple of coverage misses that I may need help constructing the LFRic examples that should trigger them.

2025-01-24 16:46 UTC, arporter requested changes
Great stuff Sergi, it's really good to see so much code being removed. I've made it through all the source files now and some of the tests.
Generally small things to tidy up although I'd like to get rid of `cursor` from all the `declaration` routines as it's not used. In fact, I'm not totally sure it's needed for the initialisation - did you have ordering issues?

2025-01-24 16:46 UTC, arporter commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    [f"\"{sig}{pre_suffix}{module_name}\"", unique_sig])
A 'suffix' should be appended, not prepended. What's the reason for this change?

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
>      assert 'USE compute_cv_mod, ONLY: compute_cv_code' not in gen
Not yours but this isn't a very good  test. It might be better just to check that `use compute_cv_mod` is not in `code.lower()`. Also, do we still need to test the `psy.gen` call?

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/lfric/dofkern_test.py
> +    type(field_type), intent(in) :: f1
It would be nice if we generated declarations grouped by type but that's definitely something for another time :-)

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/lfric/dyn_meshes_test.py
> +        assert isinstance(sym.datatype, UnsupportedFortranType)  # is a pointer
Would be good to check partial_type if/when we have it.

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_builtins_test.py
> +    assert "use constants_mod\n" in code
You can remove the comment above now.

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
> +from psyclone.domain.lfric.lfric_dofmaps import LFRicDofmaps
Please reorder

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
> +    stub_psyir = generate(os.path.join(BASE_PATH,
text again.

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_domain_kernels_test.py
> +    assert ("    call testkern_domain_code(nlayers_f1, ncell_2d_no_halos, "
Please extend to check that it is not within a loop.

2025-01-24 16:46 UTC, arporter commented on src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
> +    return
This needs attention.... :-)

2025-01-27 10:11 UTC, sergisiso commented on src/psyclone/domain/lfric/kern_call_arg_list.py
> -                    # TODO # 1910: These should be pointers
Yes, now if it has the wrong type is creates invalid (non-compilable) code, I had to fix a few of this to pass compilation tests and LFRic CI. Before it was ok being inconsistent because gen_code decided what it is again.

I actually don't like this "append_array_reference" that does all the magic under-the-hood, nor the LFRicSymbolTable helper methods in general. I would remove them add write PSyIR explicit instructions which are not much langer. But it is another big change for this PR, I suggest discussing it separately.

2025-01-27 10:13 UTC, sergisiso commented on src/psyclone/domain/lfric/kern_call_arg_list.py
> -                    # TODO # 1910: These should be pointers
There are no TODOs for 1910 left, so I will put it in the "closes"

2025-01-27 10:18 UTC, sergisiso commented on src/psyclone/domain/lfric/kern_call_arg_list.py
> +                self._kern.colourmap.name, symbol_type=DataSymbol,
Well spotted, removed lookup and updated docstring.

2025-01-27 11:31 UTC, sergisiso commented on src/psyclone/domain/lfric/kern_call_arg_list.py
> +            return (self._kern.colourmap.name + "(colour,cell)",
I use "debug_string" for now, but you are right that there is a lot of cleaning that we could do here, I made #2874

2025-01-27 11:34 UTC, sergisiso commented on src/psyclone/domain/lfric/kern_stub_arg_list.py
> -        # TODO 719 The stub_symtab is not connected to other parts of the
Yes, added to the title

2025-01-27 11:49 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_cell_iterators.py
> +                sym.interface = ArgumentInterface(
Not all symbols come from the "declaration" methods, some are created in arbitrary places and are thought for the "Invoke", so I had to guarantee (even if some already are) that they are Arguments in the stub context. This could be improved by I suggest doing in a different PR because it will require relocating code, making this PR diff very hard.

2025-01-27 11:51 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_cell_iterators.py
> +        :returns: Updated cursor value.
Done

2025-01-27 11:57 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_collection.py
>              # The list of Kernel calls we are responsible for
Done

2025-01-27 11:57 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_collection.py
> -            # TODO #719 The symbol table is not connected to other parts of
Done

2025-01-27 11:57 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_collection.py
>              # We only have a single Kernel call in this case
Done

2025-01-27 12:03 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_collection.py
> +        return self._kernel._stub_symbol_table
I think its resolved (at least how it is formulated as now they have their own symbol_table). The problem is that both stubs and invokes are created from the same collection components, so we need a way to know in which context we are, and this is what this function does.

2025-01-27 12:13 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_dofmaps.py
> +            dim.interface = ArgumentInterface(ArgumentInterface.Access.READ)
This is below a "find_or_create" so we need this here for the cases it is created also here.

2025-01-27 12:14 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_fields.py
> +        symtab = self._invoke.schedule.symbol_table
Done

2025-01-27 12:15 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_invoke.py
> -        reserved_names_list.extend(["omp_get_thread_num",
No, completely removed.

2025-01-27 12:15 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_invoke.py
> +        ''' Declare and initialise all symbols associated this this Invoke.
Fixed

2025-01-27 12:24 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +        self._stub_symbol_table = LFRicSymbolTable()
I am unsure. I would open a more specific issue if we need by then

2025-01-27 12:36 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +        # KernCallArgList creates symbols (sometimes with wrong type), we don't
I think it could be related to (and added a TODO for) #2874, moving all psy-layer symbols to the beginning will make the rationalisation of when symbols are created much simpler. (Maybe it cannot be done all in one step, but I will let that PR change the TODO is necessary)

2025-01-27 12:37 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +            symtab = self._stub_symbol_table
I am unsure about this

2025-01-27 12:43 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +            # Use the InvokeSchedule symbol_table to create a unique symbol
Done (this is also a method that creates symbols for both Invokes/Stubs and may not get interfaces right)

2025-01-27 12:44 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +                # TODO #719 we don't yet have a symbol table to prevent
Yes, deleted TODO

2025-01-27 12:49 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
>                  # We have to do this here as _init_colourmap (which calls this
We should, but we are not ready in this PR yet. First, we need to move the "declaration" and "initialisation" to when the psy-layer is created (before the transformations).

2025-01-27 12:50 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +        :rtype: :py:class:`psyclone.psyir.nodes.Container`
Done

2025-01-27 12:52 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_cell_iterators.py
> +                sym.interface = ArgumentInterface(
It could come from line 73 of this file?

2025-01-27 12:53 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +                tag = "AlgArgs_" + qr_arg.text
Done

2025-01-27 12:54 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
>          create_arg_list = KernStubArgList(self)
Agreed

2025-01-27 12:54 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +        # If a previous argument has not been given an order by KernStubArgList
Added TODO above

2025-01-27 13:30 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +            lbound = DataSymbol("undeclared_loop_start", datatype=INTEGER_TYPE)
I changed it for looking for a mandatory InvokeSchedule ancestor and added some tests. Let me know if this is ok?

2025-01-27 14:09 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +        from psyclone.psyGen import zero_reduction_variables
Moved up

2025-01-27 14:12 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +        :rtype: :py:class:`psyclone.psyir.node.Node`
Done

2025-01-27 14:38 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
>          if self._upper_bound_name == "inner":
Ok, I restored a test that monkeypatches the right values for this.

2025-01-27 14:40 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop_bounds.py
> +            if type(loop) is Loop or loop.loop_type == "null":
yes, done

2025-01-27 14:40 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop_bounds.py
> +                # Generic or 'null' loops don't need any bounds updates.
Done

2025-01-29 13:13 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_invoke.py
>          :type parent: :py:class:`psyclone.f2pygen.ModuleGen`
Done

2025-01-29 13:20 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop_bounds.py
> +                # We need to remove the now unneeded symbol (because LFRic is
This variable already exists most of the time (it is what is created at LFRicLoop init now).

The problem is that we needed those symbols before transformations (to avoid the hacky "NOT_INITIALISED" we had before), but this method is called after the transformations (because colouring only changes the loop_type). Ideally all this initialisation method should happen before transformations, and its transformation should modify/delete symbols from the tree at that point. But this change is for a different PR.

2025-01-29 13:20 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_psy.py
> +        :rtype: str
Done

2025-01-29 13:23 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_psy.py
> +        for invsch in self.container.walk(InvokeSchedule):
Done

2025-01-29 13:24 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_psy.py
> +        from psyclone.psyir.backend.fortran import FortranWriter
Yes, moved

2025-01-29 13:25 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_psy.py
> +        fortran_writer = FortranWriter(
Done

2025-01-29 13:26 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_psy.py
> +        for invsch in self.container.walk(InvokeSchedule):
Added a comment, let me know if you want more

2025-01-29 13:27 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +from psyclone.psyir.nodes import (
Done

2025-01-29 13:29 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
>          :rtype: str
Done

2025-01-29 14:32 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
>          '''
Done

2025-01-29 14:33 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param cursor: position where to add the next initialisation
Deleted

2025-01-29 14:33 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param cursor: position where to add the next initialisation
Deleted

2025-01-29 14:35 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +                self.symtab.append_argument(symbol)
Added note in docstring

2025-01-29 14:35 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        cursor = self._declare_unique_extent_vars(cursor)
Deleted

2025-01-29 14:37 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
>                  # Add declaration and look-up of stencil size
Done

2025-01-29 14:37 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-29 14:38 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-29 14:38 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +                    symtab.append_argument(max_length)
Added in docstring

2025-01-29 14:38 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
> +                symtab.append_argument(size_symbol)
Added in docstring

2025-01-29 14:40 UTC, sergisiso commented on src/psyclone/domain/lfric/transformations/lfric_extract_trans.py
> +        # TODO: Doing the variable collection here will miss all the symbols
Yes, we fixed these, I removed this TODO now.

2025-01-29 14:41 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            elif name_lower == "adjacent_face":
Done

2025-01-29 14:42 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        self._ref_elem_symbol = None
Done

2025-01-29 14:43 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            self.symtab.append_argument(sym)
Added docstring

2025-01-29 14:44 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            self.symtab.append_argument(arrsym)
Same docstring

2025-01-29 14:45 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            self.symtab.append_argument(arg)
Added docstring

2025-01-29 14:59 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_extract_driver_creator_test.py
> +    return
Fixed

2025-01-29 15:02 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_domain_kernels_test.py
> +    assert ("    call testkern_domain_code(nlayers_f1, ncell_2d_no_halos, "
Done

2025-01-29 15:08 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
> +    stub_psyir = generate(os.path.join(BASE_PATH,
Done

2025-01-29 15:09 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
> +    stub_psyir = generate(os.path.join(BASE_PATH,
Done

2025-01-30 13:23 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_cell_iterators.py
> +            statements.
pylint does not complain if the unused variable is an argument (but will explore removing cursor)

2025-01-30 14:00 UTC, sergisiso commented
Regarding cursor:
- I remove the shared "declarations" in favour of "stub_decalrations" and "invoke_declarations" as I think they are sufficiently different to be explicit about which one we are calling.
- I removed "cursor" from all declaration methods.
- I moved the check that it comes from invoke or kernel to the base implementations and call super() in all these methods, as this was not consistently checked.

However:
- I have not merged it with "initialisations" because I am not sure we were sure about it, but more importantly a quick test merging the loops below make many tests fails. Some with wrong output asserts (expected because we change the order that symbols are declared), some with symbol_table lookup errors. I expect we will change the order again when we move this logic to happen before the transformations, so I don't thing it is worth to change all test declaration order now to do it again soon.

https://github.com/stfc/PSyclone/blob/1a67f957034b30cd9dc68a21a3b87dc999dd6115/src/psyclone/domain/lfric/lfric_invoke.py#L285-L303

2025-01-30 14:02 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_collection.py
> +        :returns: Updated cursor value.
Done

2025-01-30 14:02 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_dofmaps.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:02 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_fields.py
> +        return cursor
Done

2025-01-30 14:08 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_psy.py
> +            invoke.declare()
I used `setup_psy_layer_invoke`, what do you think?

2025-01-30 14:13 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_run_time_checks.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:13 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_scalar_args.py
> +    def _create_declarations(self, cursor):
Done

2025-01-30 14:14 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_stencils.py
Done

2025-01-30 14:16 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:16 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:16 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:16 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:16 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:16 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:17 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:46 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            self.symtab.append_argument(arg_sym)
Done

2025-01-30 14:46 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:49 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:51 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:51 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 14:53 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
>          # Declare the operators
Yes, is there any context where the operator is not READ so we didn't commit at the symbol creation? or should I chase where the declaration comes from and make them always READ.

2025-01-30 14:54 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                symtab.append_argument(symbol)
Done

2025-01-30 15:01 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                    LFRicTypes("LFRicIntegerScalarDataType")(),
Good catch, fixed it here and in the tests

2025-01-30 15:07 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            op.interface = ArgumentInterface(
Do you know where to get this information from `self`:
```
(Pdb) dir(self)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_cma_ops', '_dofs_only', '_first_cma_arg', '_invoke', '_kernel', 'cma_diff_fs_params', 'cma_same_fs_params', 'initialise', 'invoke_declarations', 'kernel_calls', 'stub_declarations', 'symtab']
```
or is there any of the `src/psyclone/tests/dynamo0p3_cma_test.py` stub tests that the intent needs to be changed to "inout"?

2025-01-30 15:07 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        sym_tab = self._invoke.schedule.symbol_table
Done a big search and replace for this on this file.

2025-01-30 15:08 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            fine_mesh = self._invoke.schedule.symbol_table\
Done

2025-01-30 15:08 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                digmmap = self._invoke.schedule.symbol_table.lookup(dig.mmap)
Done

2025-01-30 15:08 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                digncellfine = self._invoke.schedule.symbol_table.lookup(
Done

2025-01-30 15:08 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                digncellpercellx = self._invoke.schedule.symbol_table.lookup(
Done

2025-01-30 15:10 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        self._invoke.schedule[comment_cursor].preceding_comment = (
Done

2025-01-30 15:10 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 15:10 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                self.symtab.append_argument(arg)
Done in the docstring

2025-01-30 15:11 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param cursor: position where to add the next initialisation
Done

2025-01-30 15:14 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
>          Create the declarations and assignments required for the
I still can not replace all "find_or_create" to "lookups", so I suggest leaving the declarations word for now but rationalise the order of symbol creation in another PR.

2025-01-30 15:14 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        symtab = self._invoke.schedule.symbol_table
Done

2025-01-30 15:16 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
>          for basis in basis_arrays:
Done

2025-01-30 15:20 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                        f"{name}_{qr_arg_name} => null()\n"
Added

2025-01-30 15:20 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        symtab = self._invoke.schedule.symbol_table
Done

2025-01-30 15:20 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param int cursor: position where to add the next initialisation
Done

2025-01-30 15:28 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                f":: {name}(:,:) => null()")
Done, I made a pass through this file adding it where possible.

2025-01-30 15:28 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param int cursor: position where to add the next initialisation
Done

2025-01-30 15:29 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        symtab = self._invoke.schedule.symbol_table
Done

2025-01-30 15:29 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        symtab = self.ancestor(InvokeSchedule).symbol_table
Done

2025-01-30 15:32 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param str method: name of the method to generate.
Done

2025-01-30 15:34 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        Generate a Reference accessing this object data.
Done

2025-01-30 15:36 UTC, sergisiso commented on src/psyclone/gen_kernel_stub.py
> +    :returns: the kernel stub of the given kernel file.
Done

2025-01-30 15:53 UTC, sergisiso commented on src/psyclone/psyGen.py
> +                        rhs=Literal(data_value, data_type))
Done the first, but for the second I am unsure how to do it for a generic API, api_conf().default_kind["integer"] just returns a string. Also note that the LHS of the assignment has the write precision, so (I think) it is effectively the same. But can investigate more if you want.

2025-01-30 16:15 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :param bool: if we generate the call by using the proxy as the base.
Done

2025-01-30 16:18 UTC, sergisiso commented on src/psyclone/psyGen.py
> +                ))
There is the same problem about creating the right datatype in a generic API way (we are in psyGen.py), and I want to bring this even to generic PSyIR. I suggest waiting for a "reductions" refactoring that I am planning if its ok.

2025-01-30 16:19 UTC, sergisiso commented on src/psyclone/psyGen.py
>          if var_arg.precision:
Done (I think)

2025-01-30 16:27 UTC, sergisiso commented on src/psyclone/psyGen.py
>              data_value = "0"
There was a test that needed this, but I think we just support reductions in LFRic builtins for now? So if they are all reals then no? I added a TODO in the docstring to improve/generalise this further, but let me know if you want some other change here.

2025-01-30 16:28 UTC, sergisiso commented on src/psyclone/psyGen.py
> +                        # pylint: disable=protected-access
tbh I don't think we need the "enable" or the "disable-next", this only affects this inner scope and there is nothing else in this scope, so I removed the "enable"

2025-01-31 12:03 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                raise NotImplementedError()
I couldn't trigger it because the "arg.intent" already does this check, so I replaced it with a comment

2025-01-31 12:05 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                digcellmap = self._invoke.schedule.symbol_table\
Done

2025-01-31 12:15 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                raise NotImplementedError()
I removed the if condition

2025-01-31 12:20 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                intr_type = ScalarType(ScalarType.Intrinsic.INTEGER, kind_sym)
I reverted to only REAL for now (I think we have to parse the relevant infrastructure file and propagate that type instead of defining it and check it in multiple places that can only become outdated)

2025-01-31 14:45 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                    f"(:,:) => null()"))
Done

2025-01-31 14:46 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            return Call.create(ArrayOfStructuresReference.create(
Done

2025-01-31 14:49 UTC, sergisiso commented on src/psyclone/psyir/backend/fortran.py
> +        if not isinstance(symbol, (TypedSymbol, StructureType.ComponentType)):
Done, I suppose you meant the raises docstring

2025-01-31 14:55 UTC, sergisiso commented on src/psyclone/psyir/nodes/directive.py
> -        TODO #1648 this method is only used by the gen_code() code-generation
It pretty much gets rid of all "real use" of f2pygen/gen_code, but there is still some references/tests/docs/TODOs about it. But since this PR is already huge and at a point where it passes all tests/integration. I thought doing #1646 separately in a follow up PR if its ok.

2025-01-31 14:56 UTC, sergisiso commented on src/psyclone/psyir/nodes/omp_directives.py
>                          found = True
Done

2025-01-31 14:57 UTC, sergisiso commented on src/psyclone/psyir/nodes/psy_data_node.py
> +                    [f"\"{sig}{pre_suffix}{module_name}\"", unique_sig])
@hiker suggested it to pass the tests. Was it maybe reverted between gen_code and lowering?

2025-01-31 14:58 UTC, sergisiso commented on src/psyclone/psyir/symbols/symbol_table.py
> +        if argument in self._argument_list:
Done

2025-01-31 15:05 UTC, sergisiso commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
>      assert 'USE compute_cv_mod, ONLY: compute_cv_code' not in gen
I agree with the assert.

I am unsure about the second, the "psy.gen" is what now does the copy/lower/psyir_backend, so its a valid way to use it. The second call to psy.gen just make sure the copy prevented changes to the original tree, otherwise we get symbols with indexing for the repeated kernels.

2025-01-31 15:16 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_dofmaps_test.py
> +from psyclone.domain.lfric.lfric_dofmaps import LFRicDofmaps
Done

2025-01-31 15:17 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_builtins_test.py
> +    assert "use constants_mod\n" in code
Done

2025-01-31 15:22 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/dyn_meshes_test.py
> +        assert isinstance(sym.datatype, UnsupportedFortranType)  # is a pointer
Well, this doesn't have one and it is not a pointer :) deleted the comment

2025-02-03 12:06 UTC, sergisiso commented
@arporter This is ready for another review. The PR has increased a bit from last time but mostly with the same syntax changes applied to GOcean tests and lots of deletions - which is satisfying. As a result, a few more issues can be closed (updated in the PR title).

2025-02-06 16:50 UTC, arporter requested changes
Phew, I've made it. There are a couple of changes that worry me a bit but other than that it's just small things. To cover myself, I have asked (a lot) for modified tests to have compilation checks added where possible.

2025-02-06 16:50 UTC, arporter commented on src/psyclone/tests/dynamo0p3_test.py
>          _ = psy.gen
Could we still check that it's the right VisitorError or does it not have a message associated with it?

2025-02-06 16:50 UTC, arporter commented on src/psyclone/tests/dynamo0p3_test.py
> +        print(generated_code)
Please rm

2025-02-06 16:50 UTC, arporter commented on src/psyclone/tests/psyir/nodes/psy_data_node_test.py
> +    already be generated by PSyIR).
You've shortened this docstring a bit too much :-)

2025-02-06 16:50 UTC, arporter commented on src/psyclone/tests/psyir/nodes/structure_reference_test.py
> +            " a structure, has been given a 'None' with name: 'unknown'")
"...but has been given a ..."

2025-02-06 16:50 UTC, arporter commented on src/psyclone/tests/psyir/nodes/structure_reference_test.py
> +            " a structure, has been given a 'Scalar' with name: 'unknown'")
"..., but has been given a ..."

2025-02-06 16:50 UTC, arporter commented on src/psyclone/tests/psyir/transformations/profile_test.py
> +    # groups = re.search(correct_re, code, re.I)
This needs reinstating?

2025-02-07 11:30 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_cell_iterators.py
> +                # Symbols are created thinking for the Invoke context, so make
Done

2025-02-07 11:33 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +        # KernCallArgList creates symbols (sometimes with wrong type), we don't
Ups, added now

2025-02-07 11:34 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
>          # Declare the operators
Done

2025-02-07 11:39 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
>          for basis in basis_arrays:
Ups, I put in in a different "for basis in basis_array" line, now moved to the right place

2025-02-07 11:46 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        symtab = self.ancestor(InvokeSchedule).symbol_table
Oh, sorry for the wrong response, but self.symtab is in LFRicCollections, this inherits from Node.

2025-02-07 11:49 UTC, sergisiso commented on src/psyclone/psyGen.py
>          if var_arg.precision:
Done

2025-02-07 11:50 UTC, sergisiso commented on src/psyclone/tests/domain/common/transformations/kernel_module_inline_trans_test.py
> +    assert 'use ru_kernel_mod, only : ru_code' not in gen
Done

2025-02-07 11:51 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +    def colourmap(self: DataSymbol):
Fixed

2025-02-07 12:02 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +            if ncols_sym is not None:
The behaviour change was unintended, I am returning None again.

(I think this needs refactoring - ideally the colour maps/symbols need be in inserted in the first colouring transformation with a unique tag, and reused by the next ones looking up the tag, no internal state references need to be stored)

2025-02-07 12:09 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +                "LFRic loops can only be inside a InvokeSchedule, a parent "
Done

2025-02-07 12:12 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +        # will produce sequencially ascending loop bound names.
Done

2025-02-07 12:23 UTC, sergisiso commented on src/psyclone/psyGen.py
> +                    f"{var_data_type}(kind={kind_type}), allocatable, "
Good catch, fixed

2025-02-10 09:50 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            op.interface = ArgumentInterface(
Done

2025-02-10 09:53 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            # All quatratures are REAL, the the PSyIR type
deleted after the comma

2025-02-10 10:21 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_field_codegen_test.py
> +            # "    ! Call kernels and communication routines\n"
Added back (when lowering from Haloex to If I forgot to keep the associated comments)

2025-02-10 10:30 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_field_codegen_test.py
>      assert output in generated_code
The compilation test was already there, before the big output assert, but I moved it down now to a more predicable location

2025-02-10 10:31 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_field_codegen_test.py
Again, was there but moved down now.

2025-02-10 10:32 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_field_codegen_test.py
>          assert halo2_flags in generated_code
Same :)

2025-02-10 10:37 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_field_stubgen_test.py
It has no psy-object

2025-02-10 10:37 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_field_stubgen_test.py
> +end module testkern_field_mod\n""" == generated_code
Same

2025-02-10 10:38 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_loop_test.py
> +    references (with names with a sequencially ascending index)
Done

2025-02-10 10:39 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_mesh_props_stubgen_test.py
> +
Not possible without psy-object

2025-02-10 10:42 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_ref_elem_stubgen_test.py
> +""" == gen
Not possible without psy-object

2025-02-10 10:43 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_ref_elem_stubgen_test.py
> +:: out_normals_to_faces""" in gen
Not possible without psy-object

2025-02-10 10:44 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
>      assert expected in generated_code
Already there, moved down

2025-02-10 10:45 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
>          "map_w3(:,cell))\n")
Already there, moved down

2025-02-10 10:45 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
>          "map_w2(:,cell), ndf_w3, undf_w3, map_w3(:,cell))\n")
Already there, moved down

2025-02-10 10:46 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
>          "ndf_w3, undf_w3, map_w3(:,cell))\n")
Already there, moved down

2025-02-10 10:46 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_scalar_codegen_test.py
>      assert expected in generated_code
Already there, moved down

2025-02-10 10:53 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_scalar_mdata_test.py
> +    return
I removed this test now, that it is part of a Kernel or Invoke is already tested by the public methods `invoke/stub_declarations` (in fact now we check this more consistently and the right one). The methods here are private and called from the mentioned ones, so they don't need to check again.

2025-02-10 10:53 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_scalar_stubgen_test.py
> +    assert expected == result
Not possible without psy-object

2025-02-10 10:54 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_stencil_test.py
>          "ndf_w1, undf_w1, map_w1(:,cell), ndf_w2, undf_w2, "
Already there, moved down

2025-02-10 10:59 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +@pytest.mark.xfail(reason="cma_op1_proxy symbol does not exist")
I could remove the xfail, it was a leftover

2025-02-10 10:59 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
Already there, moved down

2025-02-10 11:00 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
Already there, moved down

2025-02-10 11:04 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +@pytest.mark.xfail(reason="reduction name clashes not supported")
Removed (this is the same behaviour as before but VisitorError instead of GenerationError - I do hope to lift this restriction though)

2025-02-10 11:25 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +                "    global_sum%value = asum\n"
Done

2025-02-10 11:53 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +    assert "do cell = loop0_start, loop0_stop" in result
Ups, removed

2025-02-10 11:58 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
>      assert output in code
It fails with because the "extract_psy_data_mod" dependency cannot be found, I added it commented out as in another test

2025-02-10 12:30 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
> -      CALL extract_psy_data%PreDeclareVariable("last_edge_cell_all_colours", \
I will have to defer to @hiker because I am a bit confused about this, the list of symbols seems to be obtained in multiple places, for instance:
at `src/psyclone/domain/lfric/transformations/lfric_extract_trans.py::145` (but at transformation time the lfric initialisation variables and the lowering created symbols do not exist )
and `src/psyclone/psyir/nodes/extract_node.py::157` (now the initialisation variables and lowering above itself exists, but not the lowering inside its body - like you suggest the inner nodes still has "loop7_stop" instead of "last_edge_cell_all_colour")

I think this has to be done after lowering the children, e.g. `src/psyclone/psyir/nodes/psy_data_node.py::633`, if I go there with the debugger, "last_edge_cell_all_colours" exists, and the pre_var_list has still not been used until then.

The reason for the location maybe has to do with additional complexities of the gen_code that now are gone, but I suggest a different PR to re-factor this.

2025-02-10 12:32 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
Was already there, moved down

2025-02-10 12:34 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
> +    assert "    DEALLOCATE(basis_w2_on_w0, diff_basis_w3_on_w0)\n" in code
Was already there, moved down

2025-02-10 12:34 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
Was already there, moved down

2025-02-10 12:34 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
Was already there, moved down

2025-02-10 12:35 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
Cannot be done without a psy-object

2025-02-10 12:35 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
> +            ":: weights_z_qr_xyoz" in code)
Cannot be done without a psy-object

2025-02-10 12:35 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
Cannot be done without a psy-object

2025-02-10 12:36 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
Cannot be done without a psy-object

2025-02-10 12:36 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
Cannot be done without a psy-object

2025-02-10 15:53 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
> +    real(kind=r_solver), pointer, dimension(:,:,:) :: cma_op_3_cma_matrix \
Ah bad, the symbol creation was in the constructor instead of the invoke_declaration, so it ended everywhere, and I was not careful when updating the stub declarations.

2025-02-10 15:53 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
> +    real(kind=r_solver), pointer, dimension(:,:,:) :: cma_op_3_cma_matrix \
Gone now

2025-02-10 16:39 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
> +    real(kind=r_solver), pointer, dimension(:,:,:) :: cma_op_3_cma_matrix \
Gone now

2025-02-10 16:39 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
> +    real(kind=r_solver), pointer, dimension(:,:,:) :: cma_op_1_cma_matrix\
Gone now

2025-02-10 17:11 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_lma_test.py
> +    output2 = "boundary_dofs_op_a => op_a_proxy%fs_from%get_boundary_dofs()"
I need a bit of help here, this is set in dynamo3p0.py:5543:
```
if function_space.orig_name == self.descriptor.function_space_from:
    return "fs_from"
if function_space.orig_name == self.descriptor.function_space_to:
    return "fs_to"
```
(this logic has not been modified)
the debugger says:
```
(Pdb) function_space.orig_name
'any_space_2'
(Pdb) self.descriptor.function_space_from
'any_space_2'
(Pdb) self.descriptor.function_space_to
'any_space_1'
```
if I look at the kernel in `src/psyclone/tests/test_files/dynamo0p3/enforce_operator_bc_kernel_mod.F90` it seems the last 2 are correct.

If I look at the invoke `src/psyclone/tests/test_files/dynamo0p3/12.4_enforce_op_bc_kernel.f90`, I see no space, only that "op_a" is a "type(operator_type)". Do you reckon the "op_a_proxy" function space is wrong or I am going the wrong track?

2025-02-10 17:35 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_lma_test.py
> +
Not without a psy-object

2025-02-10 17:37 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_quadrature_test.py
Same

2025-02-10 17:38 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_quadrature_test.py
> +    print(code)
removed

2025-02-10 17:38 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_quadrature_test.py
Moved down

2025-02-10 17:38 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_quadrature_test.py
Not  without psy-object

2025-02-10 17:39 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_stubgen_test.py
Not without psy-object

2025-02-10 17:39 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_stubgen_test.py
Not without psy-object

2025-02-10 17:39 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_stubgen_test.py
Not without psy-object

2025-02-10 17:41 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_test.py
This, and almost all test are compiled (at the top of the test)

2025-02-10 17:53 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_test.py
>          _ = psy.gen
Ups, this shouldn't have been deleted, now is back

2025-02-10 17:53 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_test.py
> +        print(generated_code)
Removed

2025-02-10 17:55 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_test.py
> +        # "      f2_proxy = f2%get_proxy()\n"
Uncommented

2025-02-10 18:00 UTC, sergisiso commented on src/psyclone/tests/psyir/nodes/psy_data_node_test.py
> +    already be generated by PSyIR).
Reverted missing part

2025-02-10 18:04 UTC, sergisiso commented on src/psyclone/tests/psyir/nodes/structure_reference_test.py
> +            " a structure, has been given a 'None' with name: 'unknown'")
Ups, it was missing the "in" operator, and didn't spot that the original already had the "but"

2025-02-10 18:08 UTC, sergisiso commented on src/psyclone/tests/psyir/nodes/structure_reference_test.py
> +            " a structure, has been given a 'Scalar' with name: 'unknown'")
This is the right message (but was also missing the "in" operator), let me know if the current error string is ok

2025-02-10 18:18 UTC, sergisiso commented on src/psyclone/tests/psyir/transformations/profile_test.py
> +    # groups = re.search(correct_re, code, re.I)
I can see that the variables are different, but re.search returns 0 groups, I have stared at the expression for a while but I cannot see the issue, the generated output is:
```
subroutine invoke_0(a, f1, f2, m1, m2, f3)
  use mesh_mod, only : mesh_type
  use profile_psy_data_mod, only : profile_PSyDataType
  use testkern_mod, only : testkern_code
  real(kind=r_def), intent(inout) :: a
  type(field_type), intent(inout) :: f1
  type(field_type), intent(inout) :: f2
  type(field_type), intent(inout) :: m1
  type(field_type), intent(inout) :: m2
  type(field_type), intent(inout) :: f3
  integer(kind=i_def) :: cell
  integer(kind=i_def) :: loop0_start
  integer(kind=i_def) :: loop0_stop
  integer(kind=i_def) :: loop1_start
  integer(kind=i_def) :: loop1_stop
  type(mesh_type), pointer :: mesh => null()
  integer(kind=i_def) :: max_halo_depth_mesh
  real(kind=r_def), pointer, dimension(:) :: f1_data => null()
  real(kind=r_def), pointer, dimension(:) :: f2_data => null()
  real(kind=r_def), pointer, dimension(:) :: m1_data => null()
  real(kind=r_def), pointer, dimension(:) :: m2_data => null()
  real(kind=r_def), pointer, dimension(:) :: f3_data => null()
  integer(kind=i_def) :: nlayers_f1
  type(profile_PSyDataType), save, target :: profile_psy_data
  type(profile_PSyDataType), save, target :: profile_psy_data_1

  if (f1_proxy%is_dirty(depth=1)) then
    call f1_proxy%halo_exchange(depth=1)
  end if
  if (f2_proxy%is_dirty(depth=1)) then
    call f2_proxy%halo_exchange(depth=1)
  end if
  if (m1_proxy%is_dirty(depth=1)) then
    call m1_proxy%halo_exchange(depth=1)
  end if
  if (m2_proxy%is_dirty(depth=1)) then
    call m2_proxy%halo_exchange(depth=1)
  end if
  CALL profile_psy_data % PreStart("multi_invoke_psy", "invoke_0-testkern_code-r0", 0, 0)
  do cell = loop0_start, loop0_stop, 1
    call testkern_code(nlayers_f1, a, f1_data, f2_data, m1_data, m2_data, ndf_w1, undf_w1, map_w1(:,cell), ndf_w2, undf_w2, map_w2(:,cell), ndf_w3, undf_w3, map_w3(:,cell))
  enddo

  ! Set halos dirty/clean for fields modified in the above loop(s)
  call f1_proxy%set_dirty()
  CALL profile_psy_data % PostEnd
  if (f3_proxy%is_dirty(depth=1)) then
    call f3_proxy%halo_exchange(depth=1)
  end if
  CALL profile_psy_data_1 % PreStart("multi_invoke_psy", "invoke_0-testkern_code-r1", 0, 0)
  do cell = loop1_start, loop1_stop, 1
    call testkern_code(nlayers_f1, a, f1_data, f3_data, m2_data, m1_data, ndf_w1, undf_w1, map_w1(:,cell), ndf_w2, undf_w2, map_w2(:,cell), ndf_w3, undf_w3, map_w3(:,cell))
  enddo

  ! Set halos dirty/clean for fields modified in the above loop(s)
  call f1_proxy%set_dirty()
  CALL profile_psy_data_1 % PostEnd

end subroutine invoke_0
```

2025-02-10 18:26 UTC, sergisiso commented on src/psyclone/tests/utilities.py
> +            # Not everything is captured by PSyIR as Symbols (e.g. multiple
Updated the comment, let me know what you think.

2025-02-10 18:37 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_mesh_props_stubgen_test.py
> +    print(gen)
Done

2025-02-10 18:42 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
> +    real(kind=r_solver), pointer, dimension(:,:,:) :: cma_op_3_cma_matrix \
PS: I see that there is also a "nlayers" that wasn't here before, and indeed it is also a symbol created in the constructor instead of the invoke/stub_decl. However, trying to move the symbol creation made a few things fail. But I will come back to this before finishing the PR.

2025-02-10 19:02 UTC, sergisiso commented
@arporter This is ready for another review (but there are still a couple of comments with ongoing conversations and haven't removed the unused symbol that I need for the integration test)

2025-02-12 17:00 UTC, arporter requested changes
Thanks Sergi. It's getting pretty close now. Hopefully Joerg can help you solve the issue with the extraction code.

2025-02-12 17:00 UTC, arporter commented on src/psyclone/tests/psyir/nodes/structure_reference_test.py
> +            " a structure, has been given a 'None' with name: 'unknown'")
Oh yes, almost as good as Joerg's test :-)

2025-02-12 17:00 UTC, arporter commented on src/psyclone/tests/utilities.py
> +            # Not everything is captured by PSyIR as Symbols (e.g. multiple
Oh yes, I get it now, thanks.

2025-02-12 17:00 UTC, arporter commented on src/psyclone/tests/psyir/transformations/profile_test.py
> +    # groups = re.search(correct_re, code, re.I)
I vote for just re-writing the test to check for certain key statements using the `in` operator rather than this rather complicated regex.

2025-02-12 22:08 UTC, hiker commented on src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
> -      CALL extract_psy_data%PreDeclareVariable("last_edge_cell_all_colours", \
Yes, I had this duplicated variable setting at the back of my mind (and I actually re-discovered that recently, when it turns out that there was a difference between gocean and lfric (gocean would not pass the list into the driver creation, lfric would).

The original idea of giving the user an option (in the transformation) to provide their own list of variables was a way to support kernels where the automatic variable detection would not work (no static call tree analysis at that time), but was de-facto never used. So I am happy to remove this.

But, that might also require some refactoring, to make sure the variable lists used in extraction is the same as the one used in driver creation. I believe, the driver creation call could be moved into the extract node. That would at least make certain that the lists are identical, and the variables can be collected after lowering the body. 

The problem is, I am not sure how to do this best. I am not certain that this is an entirely trivial change (I didn't look into the details of this PR), so it might take some effort. At the same time, with people now starting to use kernel extraction, I am a bit concerned about merging this into master if it might break kernel extraction (till I fix it). Not sure how close this PR is to be merged: we could create a develop branch off master, merge this PR in, and keep on maintaining two branches (master and develop), and I create a PR to fix PSyKE to be merged in develop, and once this is done, we merge develop into main (and never do that again :) )

2025-02-13 11:17 UTC, sergisiso commented on src/psyclone/tests/psyir/transformations/profile_test.py
> +    # groups = re.search(correct_re, code, re.I)
Done

2025-02-14 09:51 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
> -    assert LFRicBuild(tmpdir).code_compiles(psy)
Ups, added back

2025-02-14 09:51 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_basis_test.py
> -    assert LFRicBuild(tmpdir).code_compiles(psy)
Added back

2025-02-14 11:04 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +            return ncols_sym.name if ncols_sym is not None else None
Ah, removed these lines now, it was a fallback for not all arguments have been given a proper interface. It's good that this is not the case anymore.

2025-02-14 11:05 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                    rhs=dofs.argument.generate_method_call(
Fixed, thanks for the help

2025-02-14 12:49 UTC, sergisiso commented on src/psyclone/tests/dynamo0p3_cma_test.py
> +    real(kind=r_solver), pointer, dimension(:,:,:) :: cma_op_3_cma_matrix \
Removed spurious nlayers, now only the argument declarations should be in stubs.

2025-02-19 09:16 UTC, sergisiso commented
@TeranIvy @hiker I merged the latest changes to this branch (split elements order and partially written extraction field), and is now passing all our compilation and integration tests. It would be great if you could check it with the LFRic tests (@TeranIvy ) and additional extraction test (@hiker ) and let me know if there is any problem that was not reported by our CI.

* I am aware of the colourmap symbol missing in the extraction, but let me know if anything else is missing

2025-02-24 09:39 UTC, sergisiso commented
@arporter Addressed the comments and brought to master, this is ready for another review.

@TeranIvy Let us know if there is any problems with your MO LFRic tests

2025-02-25 10:14 UTC, TeranIvy commented
> @arporter Addressed the comments and brought to master, this is ready for another review.
> 
> @TeranIvy Let us know if there is any problems with your MO LFRic tests

Hi @sergisiso, I installed the PSyclone test environment from your branch and ran comprehensive Rose stem tests (`--group=all`). The outcome is below.

* [LFRic Core trunk at r52139](https://code.metoffice.gov.uk/trac/lfric/browser/LFRic/trunk?rev=52139): All fine. 

* [LFRic Apps trunk at r7786 ](https://code.metoffice.gov.uk/trac/lfric_apps/browser/main/trunk?rev=7786): Failures in several jobs, mainly related to GungHo model, NG Arch, LFRic Atmosphere, LFRic Coupled, UM Physics Interface, LFRic JEDI interface and Adjoint tests.

* [LFRic Apps branch at r7649](https://code.metoffice.gov.uk/trac/lfric_apps/browser/main/branches/dev/joshuadendy/r7568_split_element_patches?rev=7649) from the [LFRic Apps ticket #549](https://code.metoffice.gov.uk/trac/lfric_apps/ticket/549) that contains patches for PSyAD compatible with PSyclone master: Same failures as on trunk.

The failures in LFRic Atmosphere, Coupled and UM Physics Interface seem to be failures to find/create a symbol (error report below).

```
Error, unexpected exception, please report to the authors:
Traceback (most recent call last):
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/symbols/symbol_table.py", line 965, in lookup
    symbol = self.get_symbols(scope_limit)[self._normalize(name)]
KeyError: 'height_wth_max_branch_length'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/symbols/symbol_table.py", line 417, in find_or_create
    symbol = self.lookup(name)
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/symbols/symbol_table.py", line 993, in lookup
    f"Table.") from err
KeyError: "Could not find 'height_wth_max_branch_length' in the Symbol Table."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/backend/visitor.py", line 203, in __call__
    lowered_node = node_copy.lower_to_language_level()
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/nodes/node.py", line 1481, in lower_to_language_level
    child.lower_to_language_level()
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/nodes/node.py", line 1481, in lower_to_language_level
    child.lower_to_language_level()
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/domain/lfric/lfric_loop.py", line 182, in lower_to_language_level
    child.lower_to_language_level()
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyGen.py", line 1513, in lower_to_language_level
    call_node = Call.create(rsymbol, self.arguments.psyir_expressions())
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/dynamo0p3.py", line 5325, in psyir_expressions
    create_arg_list.generate()
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/domain/lfric/arg_ordering.py", line 433, in generate
    arg, var_accesses=var_accesses)
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/domain/lfric/kern_call_arg_list.py", line 506, in stencil_2d_max_extent
    sym = self.append_integer_reference(root_name, tag=unique_tag)
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/domain/lfric/arg_ordering.py", line 207, in append_integer_reference
    datatype=LFRicTypes("LFRicIntegerScalarDataType")())
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/symbols/symbol_table.py", line 430, in find_or_create
    return self.new_symbol(name, **new_symbol_args)
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/symbols/symbol_table.py", line 400, in new_symbol
    self.add(symbol, tag)
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/symbols/symbol_table.py", line 580, in add
    f"This symbol table, or an outer scope ancestor symbol "
KeyError: "This symbol table, or an outer scope ancestor symbol table, already contains the tag 'lengthwthetacross2dsten_size' for the symbol 'exner_wth_max_branch_length', so it can not be associated with symbol 'height_wth_max_branch_length'."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/generator.py", line 583, in main
    kern_naming=args.kernel_renaming)
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/generator.py", line 403, in generate
    return alg_gen, psy.gen
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyGen.py", line 294, in gen
    result = fortran_writer(new_container)
  File "/project/extrasoftware/packages.rhel7/psyclone/test/python/3.7.0/lib/python3.7/site-packages/psyclone/psyir/backend/visitor.py", line 209, in __call__
    ) from err
psyclone.psyir.backend.visitor.VisitorError: Visitor Error: Failed to lower 'Container[pmsl_alg_mod_psy]
```

Failure in NG Arch job is similar to the above ones (same variable not in symbol table but manifests in another algorithm call, see below.
```
psyclone.psyir.backend.visitor.VisitorError: Visitor Error: Failed to lower 'Container[pmsl_alg_mod_psy]
```

The failures in LFRic JEDI and Adjoint tests builds return a different error which is not so obvious to debug.

```
make[3]: *** [cylc-run/r7568_split_element_patches/run2/share/source/apps/science/adjoint/build/post_patch.mk:126: /var/spool/jtmp/9533117.xcf00.e7RwQY/intel_fast-debug-64bit/r7568_split_element_patches/run2/jedi_lfric_tests/integration-tests/integration-tests/algorithm/core_dynamics/atlt_sample_eos_pressure_alg_mod.X90] Error 1
make[2]: *** [cylc-run/r7568_split_element_patches/run2/share/source/apps/science/adjoint/build/import.mk:15: import-adjoint] Error 2
make[1]: *** [cylc-run/r7568_split_element_patches/run2/share/source/core/infrastructure/build/lfric.mk:266: cylc-run/r7568_split_element_patches/run2/share/source/apps/science/adjoint/import] Error 2
make[1]: *** Waiting for unfinished jobs....
```

GungHo model failure is due to declarations of unused variables (seems to be MO issue).

```
algorithm/transport/ffsl/ffsl_advective_updates_alg_mod_psy.f90:191:38:

  191 |     integer(kind=i_def) :: loop1_start
      |                                      1
Error: Unused variable 'loop1_start' declared at (1) [-Werror=unused-variable]
algorithm/transport/ffsl/ffsl_advective_updates_alg_mod_psy.f90:192:37:

  192 |     integer(kind=i_def) :: loop1_stop
      |                                     1
Error: Unused variable 'loop1_stop' declared at (1) [-Werror=unused-variable]
algorithm/transport/ffsl/ffsl_advective_updates_alg_mod_psy.f90:193:38:

  193 |     integer(kind=i_def) :: loop2_start
      |                                      1
Error: Unused variable 'loop2_start' declared at (1) [-Werror=unused-variable]
algorithm/transport/ffsl/ffsl_advective_updates_alg_mod_psy.f90:194:37:

  194 |     integer(kind=i_def) :: loop [...]

2025-02-25 15:40 UTC, sergisiso commented
The issue with gungho is that lfric_apps uses a different script just for algorithm/transport/ffsl/ffsl_advective_updates_alg_mod.py
https://code.metoffice.gov.uk/trac/lfric_apps/browser/main/trunk/applications/gungho_model/optimisation/meto-xc40/algorithm/transport/ffsl/ffsl_advective_updates_alg_mod.py?rev=7786 this script fuses loops and leaves leftover PSyIR symbols that are not used anymore. I will update the fusetrans to clean up those symbols.

2025-02-26 15:34 UTC, arporter requested changes
A few small things to tidy and we need to decide what we're going to do about the kernel extraction.

2025-02-26 15:34 UTC, arporter commented on src/psyclone/tests/domain/lfric/transformations/lfric_extract_test.py
> -      CALL extract_psy_data%PreDeclareVariable("last_edge_cell_all_colours", \
Aside from the minor matter that various LFRic rose-stem tests are failing, I think this is the last remaining thing to resolve. @hiker have you had time to see how much work it is likely to be?

2025-02-26 17:12 UTC, sergisiso commented on src/psyclone/domain/lfric/arg_ordering.py
> +                sym = self._symtab.lookup_with_tag("tag")
Oh yes, that's embarrassing, that also fixes the first issue reported by @TeranIvy

2025-02-27 09:45 UTC, sergisiso commented on src/psyclone/tests/psyir/transformations/profile_test.py
> +    code = fortran_writer(invoke.schedule)
Ups deleted

2025-02-27 09:49 UTC, sergisiso commented on src/psyclone/psyir/transformations/omp_loop_trans.py
> +    OMPTeamsLoopDirective, OMPTeamsDistributeParallelDoDirective,
Reverted

2025-02-27 14:15 UTC, sergisiso commented on src/psyclone/psyir/transformations/loop_fuse_trans.py
> +                        node2.stop_expr.walk(Reference)]
Done

2025-02-27 14:19 UTC, sergisiso commented on src/psyclone/psyir/transformations/loop_fuse_trans.py
> +        # with '-Werror=unused-variable'
Done

2025-02-27 14:36 UTC, TeranIvy commented
> @TeranIvy Can you try again. I have been able to run them locally and now this are fixed: "> Some ngarch, lfric_atm, lfric_coupled and um_physics tests fail with Symbol errors",
> 
> The adjoint and jedi failures are when applying `lfric_apps/science/adjoint/build/post_patch.mk`. The problem is that LFRic Apps has patches applied to psyclone output code, since the output style has changed, some of the patches in `lfric_apps/science/adjoint/patches/*` will need to be re-done.

@sergisiso, thanks for fixig the issues! I retested both Core and Apps branches after bringing them up to heads of respective trunks.

* Core is fine.
* There are only Adjoint and JEDI-LFRic failures now, which as you said are probably due to different code generation style.

2025-02-27 15:13 UTC, sergisiso commented on src/psyclone/psyir/transformations/loop_fuse_trans.py
> +            remaining_syms = [r.symbol for r in routine.walk(Reference)]
I am slightly nervous that Signatures still operate on strings and can't differentiate between symbols with the same name in different scopes, but I think is the right thing to do here, so I updated to it.

2025-02-27 15:44 UTC, sergisiso commented
@arporter I addressed your latest comments, fixed the rose-stem test issues (I have all* lfric apps running locally now I will add these to the integration tests but in a different PR), brought to master and improved the coverage. This is ready for another review.

*all apps but the adjoint patches. @arporter @TeranIvy Relying on the exact output of psyclone will always be very brittle, I don't think we should be doing backwards-compatibility guarantees on this but the number of patches in that folder is big.  I know there is a PSyAD issues github project, but do we know if there is a set of issues that cause the need for most of the patches?

2025-02-28 08:35 UTC, arporter commented
> *all apps but the adjoint patches. @arporter @TeranIvy Relying on the exact output of psyclone will always be very brittle, I don't think we should be doing backwards-compatibility guarantees on this but the number of patches in that folder is big. I know there is a PSyAD issues github project, but do we know if there is a set of issues that cause the need for most of the patches?

This is a question for @DrTVockerodtMO really.

2025-03-01 14:54 UTC, hiker commented
Just for wider visibility, here my comment on teams:

I think Sergi is doing some complicated handling of variables on purpose, but I don't understand the reason for it - to me it seems to break the whole kernel extraction (and it is just not noticed, because the tests were I think incorrectly updated).
The example that causes a failure, starts with a loop:
 ```
do cell = loop0_start, loop0_end, 1
    kernel
```
After colouring, this loops is replaced with:
 ```
do colour = loop5_start, loop5_stop, 1
   do cell = loop0_start, loop0_stop, 1
      kernel
```
Then omp is applied and extraction is done (I'm leaving the omp directive out to keep the code shorter, I don't think it affects this at all). So at the time we determine the variables used, we only get loop5_start and loop5_stop.
 
But later in lfric_loop_bounds.initialise, the loop boundaries are changed, and we end up with the final loop:
 ```
do colour = loop0_start, loop0_stop, 1
   do cell = loop1_start, last_edge_cell_all_colours(colour), 1
      kernel
```
This explains why in the test the variables loop4 (ok, I just realised that I picked the wrong loop when writing this up, but it's basically the same) is changed to loop7, and loop5 is completely removed (and last_edge_cell_all_colours is totally missing).
I assume that there is a reason, I just don't know what it might be. Obviously, from my point of view, I would say to set the loop indices to the final values. 

Short of that, I am a bit at a loss what to do about this  Even if we run the variable access information later, when lowering the extraction (and I am having some problems with creating the driver there atm, though that can be fixed I think), no user-script would be able to use the variable access information anymore! Admittedly, I believe the loop indices are not really used for anything atm (they could be used to determine if two loops have overlapping indices), so it probably doesn't really matter - but I would really really prefer to fix this.

The only other option I see is to create a copy of the nodes in VariablesAccessInfo and lower them to get the right information. But that would then I believe run into the same problem I have with driver creation (in that there is no LFRicInvokeSchedule at the top of the copied nodes, and when you lower, it fails when lowering CodedKern:
```
symtab = self.ancestor(InvokeSchedule).symbol_table
```
since no ancestor is found.

2025-03-03 21:31 UTC, sergisiso commented
> I think Sergi is doing some complicated handling of variables on purpose, but I don't understand the reason for it - to me it seems to break the whole kernel extraction [...] I assume that there is a reason, I just don't know what it might be. 

I agree this is confusing and I will push a change to update this. I initially removed the "NOT_INITIALISED" literals and set loop bound variables at the beginning but then realised that this changed the loop names of the output code in several cases, which make the PR diff even more difficult to track. In addition, I would need to change them again in #2905, so I reverted to give the loop names indexes by their position at the invokeshcedule lowering (by replacing whatever they had at the beginning) but I didn't want to bring back the NOT_INITIALISED. What they have at he beginning is irrelevant for the PR, I could revert them to "NOT_INITIALISED" (which I prefer not to), or use a "integer :: not_initialised_{idx}" for now (which I could explore).

> But later in lfric_loop_bounds.initialise, the loop boundaries are changed, and we end up with the final loop

I think this is the main problem, the lfric_loop_bounds.initialise happens at lowering and change aspects of the PSyIR, in this case the loop bounds.

> Obviously, from my point of view, I would say to set the loop indices to the final values.

This doesn't solve the underlying problem. It just solves it in some cases because then the PSyIR is not modified. But there is no guarantee (in general) that the lowering doesn't add/replace symbols other than the loop bounds (e.g. the colourmap, the tiling symbols). And any node that adds lowering logic.

> Even if we run the variable access information later, when lowering the extraction (and I am having some problems with creating the driver there atm, though that can be fixed I think), no user-script would be able to use the variable access information anymore!

I don't understand this. "variable access information" will return the access information for all symbols in that point in time in the tree. Of course if there are future changes latter in the user-script or the lowering, in cannot know in advance. It cannot know about symbols that have not been created or used yet.

> Admittedly, I believe the loop indices are not really used for anything atm (they could be used to determine if two loops have overlapping indices), so it probably doesn't really matter - but I would really really prefer to fix this.

As you mention it doesn't matter, regardless of what they are: two Literals('NOT_INITIALISED') or two non-initialised variables which don't have any context when called non_initialised_{idx} or loop_start_{idx}, we cannot infer any information from them. The indices in LFRic have to be inferred from the Kernel Call inside.

> The only other option I see is to create a copy of the nodes in VariablesAccessInfo and lower them to get the right information. But that would then I believe run into the same problem I have with driver creation (in that there is no LFRicInvokeSchedule at the top of the copied nodes, and when you lower, it fails when lowering CodedKern

No, the problem here will be the same. I mentioned this before but a VariableAccessInfo cannot be stored, in needs to be consumed at the same point where it is created, because we don't invalidate/update them. So any tree update is not reflected. The problem with extraction for lfric is that we store information that becomes outdated.

> when lowering the extraction (and I am having some problems with creating the driver there atm, though that can be fixed I think)

I really think this is the generic solution, not just for loop bounds but for any possible posterior user-script or lowering modification. In fact, it thought the generic extract node (not LFRic) already worked like this.

> and it is just not noticed, because the tests were I think incorrectly updated.

I wouldn't discard this, I updated some of the extraction tests maybe without paying enough attention because I thought we could fix this latter.

@hiker I will probably not have time to work on it this week, but we could screenshare a possible solution next week, I started moving the extraction to the lowering some time ago, but I stopped because I was unfamiliar with some of the code and this PR was already big enough. But if this is a concern to get this PR merged, we can make sure we have a solution before it progresses.

2025-03-05 06:55 UTC, hiker commented
> I think this is the main problem, the lfric_loop_bounds.initialise happens at lowering and change aspects of the PSyIR, in this case the loop bounds.
> 
> > Obviously, from my point of view, I would say to set the loop indices to the final values.
> 
> This doesn't solve the underlying problem. It just solves it in some cases because then the PSyIR is not modified. But there is no guarantee (in general) that the lowering doesn't add/replace symbols other than the loop bounds (e.g. the colourmap, the tiling symbols). And any node that adds lowering logic.

Hmm - while I atm extract from files without any changes (except redundant computation, since this is required by the config file), we have tests that verify that extraction from colouring works as expected (e.g. the `last_edge_cell_all_colour` array is added etc.

We indeed need to sit together, but my main question is:
why can't the loop boundaries be created the moment the loop is added to the tree? Yes, that might mean that loop boundaries are set a couple of times only to be thrown away (e.g. first the original loop, the you do colouring, so you throw away the original loop node, and insert two new ones, both of which sets the loop bounds).

I remember that not having loop bounds at extraction time was a problem, and I believe I added this for gocean and lfric at that time (or somehow there was a function that would set the bounds when they are undefined automatically?? Can't remember now).

2025-04-03 13:20 UTC, DrTVockerodtMO commented
> > *all apps but the adjoint patches. @arporter @TeranIvy Relying on the exact output of psyclone will always be very brittle, I don't think we should be doing backwards-compatibility guarantees on this but the number of patches in that folder is big. I know there is a PSyAD issues github project, but do we know if there is a set of issues that cause the need for most of the patches?
> 
> This is a question for @DrTVockerodtMO really.

Apologies for not responding sooner. I have a list of the patch flavours that I can share in the relevant channels.

2025-04-09 15:04 UTC, sergisiso commented
> Apologies for not responding sooner. I have a list of the patch flavours that I can share in the relevant channels, I don't recall being aware of the PSyAd issues github project though. Can someone point me to where that is please?

Is at https://github.com/orgs/stfc/projects/12 but I didn't realise that it is probably only visible to stfc. No worries, just be aware that before the next psyclone version bump the patches will need some updates.

@arporter Note that since addressing the modifications in your last review I kept it up to master doing the eventual merge resolution commit, but https://github.com/stfc/PSyclone/pull/2834/commits/6e0f05b20730017433c41093c755d5e9281e4504 introduced a change: it has updated the LFRicLoop initial bound to have "uninitialised_" in their name because the final names are given by the lowering (it has the loop index at lowering time) and this renaming could easily confused to move symbols arround when in reality the bounds are just re-done by the LFRicLoopBound class, now the temporary initial symbols are easily distinguishable are completely deleted when lowering.

2025-04-28 15:37 UTC, sergisiso commented
@arporter I brought it to master, this is ready for another review now.

2025-04-28 19:54 UTC, arporter commented
Thanks Sergi. Please could you address the missed coverage and then I'll take a look.

2025-05-01 08:25 UTC, sergisiso commented
@arporter The patch coverage is now complete. Ready for review

2025-05-02 15:10 UTC, arporter requested changes
Thanks Sergi. I had a last pass through all the files modified since last time and found a few things. Mostly minor but we are now missing the precision on the literal "0.0" used to initialise reduction variables - this could cause a change in the answers.

2025-05-02 15:10 UTC, arporter commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +                "    asum = 0.0\n"
Strictly, this should still be `0.0_r_def`. If this is easy to fix then please add the precision, otherwise it could be delayed to another PR (with a TODO).

2025-05-02 15:17 UTC, sergisiso commented on src/psyclone/domain/lfric/arg_ordering.py
> +        if self._kern and self._kern.ancestor(psyGen.InvokeSchedule):
I would keep InvokeSchedule because we do `.invoke` in the if body

2025-05-02 15:18 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +        if self.ancestor(InvokeSchedule):
Done

2025-05-02 15:23 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_kern.py
> +        # kinds (precisions)
Good point, I added a TODO for an upcoming PR that may help

2025-05-02 15:28 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +        ischedule = self.ancestor(InvokeSchedule)
I left this one because the error message below is quite explicit about it, but I replaces the others in this file

2025-05-02 15:28 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +        mesh_obj = self.ancestor(InvokeSchedule).symbol_table.\
Done

2025-05-02 15:29 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +        sym_tab = self.ancestor(InvokeSchedule).symbol_table
Done

2025-05-02 15:29 UTC, sergisiso commented on src/psyclone/domain/lfric/lfric_loop.py
> +        sym_table = self.ancestor(InvokeSchedule).symbol_table
Done

2025-05-02 15:33 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +                self.symtab.find_or_create_tag("adjacent_face")
Yes, done

2025-05-02 15:36 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :returns: Updated cursor value.
Done

2025-05-02 15:36 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :returns: Updated cursor value.
Done

2025-05-02 15:37 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :returns: Updated cursor value.
Done

2025-05-02 15:37 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +            cma_name = self.symtab.find_or_create_tag(
Done

2025-05-02 15:38 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :returns: Updated cursor value.
Done

2025-05-02 15:39 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :returns: Updated cursor value.
Done

2025-05-02 15:39 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        :returns: Updated cursor value.
Done

2025-05-02 15:43 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        symtab = self._call.ancestor(InvokeSchedule).invoke.schedule\
I won't do this one because it has a `.invoke`

2025-05-02 15:43 UTC, sergisiso commented on src/psyclone/dynamo0p3.py
> +        symtab = self._call.ancestor(InvokeSchedule).invoke\
I won't do this one because it has a `.invoke`

2025-05-02 15:45 UTC, sergisiso commented on src/psyclone/psyGen.py
> +            _ = REDUCTION_OPERATOR_MAPPING[reduction_access]
Ah yes! Done

2025-05-02 15:51 UTC, sergisiso commented on src/psyclone/tests/core/variables_access_info_test.py
> +        "map_w3: READ, ncell_2d_no_halos: "
Because it is done before lowering and therefore before the invoke_declarations of any symbol that needs it. This may change again in #2905, but currently this symbol was not used anywhere in the DSL tree.

2025-05-02 15:54 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_builtins_test.py
> -    assert (f"INTEGER(KIND={kind_name}), pointer, dimension(:) :: "
yes done

2025-05-02 16:02 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/lfric_loop_test.py
> +def test_upper_bound_fortran_invalid_bound():
Done

2025-05-02 16:03 UTC, sergisiso commented on src/psyclone/tests/psyir/transformations/loop_fusion_test.py
> +    # For some reason (given by a DSL) this are find to fuse
Done

2025-05-02 16:03 UTC, sergisiso commented on src/psyclone/tests/psyir/transformations/loop_fusion_test.py
> +    # Raise the language-level PSyIR to NEMO PSyIR
Removed comment :)

2025-05-02 16:04 UTC, sergisiso commented on src/psyclone/tests/psyir/transformations/omp_target_trans_test.py
> +    print(psyir.view())
Done

2025-05-02 17:04 UTC, sergisiso commented on src/psyclone/tests/domain/lfric/transformations/dynamo0p3_transformations_test.py
> +                "    asum = 0.0\n"
Done (it was easier than I thought)

2025-05-02 20:04 UTC, sergisiso commented
@arporter This is ready for review again, I have also submitted an integration test job

2025-05-03 10:46 UTC, arporter approved these changes
Thanks for the speedy response Sergi.
This is all good now. The integration tests were all green.
I'll proceed to merge.

2025-05-03 10:46 UTC, merged