Update (virtually) all test kernels etc. to use operates_on (closes #866)
stfc/PSyclone pull request #902
Opened 2020-09-22 07:53 UTC by arporter

Only those test kernels required for coverage of the support for the old format are left unchanged.
They will be modified as part of #870.

2020-09-22 11:37 UTC, arporter commented
I have tried to tightly restrict this PR to only changing kernel metadata. Several of the test kernels also had to have their 'use' statements updated in order to bring in 'CELL_COLUMN' instead of 'CELLS'. Ready for review.

2020-09-22 12:42 UTC, TeranIvy requested changes
Please update `USE` statements in modified `examples/lfric` kernels 😃

2020-09-22 14:06 UTC, arporter commented
Oops, I'd made a typo in my grep. Should be fixed now.

2020-09-23 15:03 UTC, TeranIvy requested changes
Thanks for undertaking this giant effort. Thanks also for dilligently referencing issue #870 with the remaining instances of `iterates_over`. Most things look good and the remarks I have are for consistency with the existing code (inline).
- Tests with compilation pass.
- Examples run.
- Modified Python code is `pycodestyle` and `pylint` clean.
- Documentation builds (no change there).
- Coverage is fine and there are examples left for testing of `iterates_over`.

2020-09-28 10:47 UTC, arporter commented on examples/lfric/eg2/v1_kernel_mod.F90
> +                                   gh_inc, v1, fe, cell_column ! the enums
done

2020-09-28 10:47 UTC, arporter commented on examples/lfric/eg2/v2_kernel_mod.F90
> +                                   gh_inc, v2, fe, cell_column ! the enums
Done.

2020-09-28 11:01 UTC, arporter commented
As it was only a couple of sed's I've made the requested changes although please note we do not mandate any style for the test kernels.
Should be ready for second review assuming Travis is happy.

2020-10-01 10:26 UTC, TeranIvy commented
There is no mandated style for Fortran source and examples and there are many source changes. I think it would be good to keep some consistency in these bulk changes. Ideally this would be done on basis of individual examples, but there are many, we have no mandated style and it is ultimately not something critical. 

Looking at the changes and the overall style of the code in modified source, I suggest using the previous upper-case solution for `operates_on` and that is `operates_on = CELL_COLUMN`.  It is a single `grep` command so hopefully it should not be too onerous.

2020-10-01 16:11 UTC, arporter commented
Should be ready to review once Travis has reported.

2020-10-01 18:56 UTC, TeranIvy approved these changes
All well now, including the repeated tests with compilation, examples, etc. Proceeding to merge.

2020-10-01 19:28 UTC, merged