Correct RegionTrans.validate to always work on list of nodes (closes #952)
stfc/PSyclone pull request #953
Opened 2020-10-23 10:37 UTC by arporter

Small bug fix that uses the existing `RegionTrans.get_node_list()` at the beginning of the `validate` method so as to ensure we're always working with a list of nodes.

While looking at the tests, I discovered we had an old and duplicated test in transformations_test.py so I've removed that.

2020-10-23 10:39 UTC, arporter commented
Ready for first review (assuming Travis is happy).

2020-10-23 23:16 UTC, rupertford requested changes
Just one small suggestion. Please see inline comment.

2020-10-27 09:16 UTC, arporter commented on src/psyclone/psyir/transformations/region_trans.py
> +        :param node_list: list of PSyIR nodes or a single node.
Yes, that is better.

2020-11-14 20:54 UTC, rupertford approved these changes
The one small issue has been addressed.

2020-11-14 21:10 UTC, merged