Support scip ci with GitHub actions [closes #973]
stfc/PSyclone pull request #974
Opened 2020-11-15 00:35 UTC by rupertford

2020-11-15 22:58 UTC, rupertford commented
I can't seem to be able to get this to work :-(

2020-11-16 08:39 UTC, arporter commented
Is the issue to do with the fact that we don't have a `main:` section in our yml? Although, having said that, you'd have thought you'd either need toJson or you don't so it's weird that the solution at https://github.com/veggiemonk/skip-commit/issues/5 doesn't work.

2020-11-25 15:14 UTC, arporter commented
The yml now successfully gets the hash of the current commit. Next stage is to work out how to get the associated commit message.

2020-12-15 23:24 UTC, rupertford commented
Perhaps we could try this ... https://github.com/marketplace/actions/ci-skip-action

2021-01-07 16:02 UTC, arporter commented
The last commit did succeed in triggering the test suite - I just cancelled it manually for efficiency reasons. We therefore have a working solution!

2021-01-07 16:15 UTC, arporter commented
Since we have the codecov-reported coverage as a required check, we could choose to change fail-fast to `False` (so that the tests aren't reported as failing) and just ensure that no coverage was uploaded to codecov if skip-ci was supplied (as well as skipping the tests themselves, obviously). I'll let the reviewer decide :-)

2021-01-07 16:30 UTC, arporter commented
This is ready now but I realise that since @rupertford opened this PR, he isn't allowed to review it! I'll therefore request @hiker or @sergisiso to review but obviously @rupertford, feel free to informally review.

2021-01-08 08:45 UTC, sergisiso requested changes
@arporter See the inline comment.

> we could choose to change fail-fast to False (so that the tests aren't reported as failing) and [...] I'll let the reviewer decide :-)

I prefer it fails the test as it is right now.

2021-01-08 08:45 UTC, sergisiso commented on .github/workflows/python-package.yml
> +        commit-filter: 'skip ci'
I think the square brackets should be part of the filter to avoid false positives.

2021-01-08 13:59 UTC, arporter commented
Changed to include square brackets in filter, as suggested. Ready for another look.

2021-01-08 14:12 UTC, sergisiso approved these changes
@arporter PR approved. The changelog commit should bring the tests to pass again.

2021-01-08 15:04 UTC, merged